

<!DOCTYPE html>
<html>
<head><meta http-equiv="pragma" content="no-cache" /><meta name="renderer" content="webkit|ie-comp|ie-stand" /><meta http-equiv="cache-control" content="no-cache" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="expires" content="0" /><meta http-equiv="keywords" content="北京师范大学政府管理学院,政府管理学院,北师大政府管理学院,北师大政府管理学院,www.heu.edu.cn" /><meta http-equiv="description" content="欢迎访问北京师范大学政府管理学院" /><meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" /><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" /><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta http-equiv="X-UA-Compatible" content="IE=9" /><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" /><title>
	北京师范大学政府管理学院
</title>
    <script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/slider.js"></script>
    <script type="text/javascript" src="js/dropdown.js"></script>
    <script src="js/jquery-accordion-menu.js" type="text/javascript"></script>
    <script src="js/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="css/bootstrap.min.css" /><link rel="stylesheet" href="css/css.css" /><link rel="stylesheet" href="css/style.css" /><link rel="stylesheet" href="fonts/iconfont.css" /><link href="css/jquery-accordion-menu.css" rel="stylesheet" type="text/css" />
    <script src="js/responsive-util2.js"></script>
    <script src="js/scrolltopcontrol.js"></script>
    <script src="js/caidan.js"></script>
    <!--让bootstrap兼容ie8 
[if lte IE 8]-->
    <script type="text/javascript" src="js/respond.min.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <!--  [endif]
 [if lt IE 9]-->

    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <!-- [endif]-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <script type="text/javascript">
        $(function () {
            $('#demo01').flexslider({
                animation: "slide",
                direction: "horizontal",
                easing: "swing",
            });
            $('#demo02').flexslider({
                animation: "slide",
                direction: "vertical",
                easing: "swing"
            });

            // 使用说明
            /*
                animation: "slide", //转换方式 fade淡入淡出 slide滚动
                direction:"horizontal", //滚动方向 horizontal左右 vertical上下
                slideshowSpeed: 3000, //停留时间
                directionNav: true, //是否显示左右控制按钮 true&false
                controlNav: true, //是否显示下方控制按钮 true&false
                mousewheel: false, //是否允许鼠标控制滚动 true&fals
            */

        });
        function _openSelectLink(selecto, linkname, addclicktimename) {
            if (linkname == undefined || linkname == "")
                linkname = "value";


            var index = selecto.selectedIndex;
            var option = selecto.options[index];

            var url = option.getAttribute("value");
            if (addclicktimename != undefined && addclicktimename != "") {
                try {
                    eval(option.getAttribute(addclicktimename))
                }
                catch (e) {
                }
            }

            window.open(url);

            if (selecto.selectedIndex != 0) {
                selecto.selectedIndex = 0;
            }
        }
    </script>




    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery("#jquery-accordion-menu").jqueryAccordionMenu();

        });

        $(function () {
            //顶部导航切换

        })
        //banner轮播

    </script>
    <style>
.cex-list>li>a{
	color:#fff;
	padding:10px 19.8px;
}
</style>

</head>
<body style="background-color: #eee">
    <form name="form1" method="post" action="newshow.aspx?newid=2416&amp;wzlx=Masterbh" id="form1">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTAyOTU0NDI0OA9kFgICAw9kFg4CBQ8WAh4LXyFJdGVtQ291bnQCCBYQZg9kFgRmDxUCGmFib3V0LmFzcHg/Y2Rzcz0xOSZjZGJoPTE5DOWtpumZouS7i+e7jWQCAQ8WAh8AAgUWCmYPZBYCZg8VAhphYm91dC5hc3B4P2Nkc3M9MTkmY2RiaD0yMAzlrabpmaLmpoLov7BkAgEPZBYCZg8VAhxoaXN0b3J5LmFzcHg/Y2Rzcz0xOSZjZGJoPTIxDOWOhuWPsuayv+mdqWQCAg9kFgJmDxUCHnN0cnVjdHVyZS5hc3B4P2Nkc3M9MTkmY2RiaD0yMgznu4Tnu4fmnLrmnoRkAgMPZBYCZg8VAhxTdWJqZWN0LmFzcHg/Y2Rzcz0xOSZjZGJoPTIzDOWtpuenkeiuvue9rmQCBA9kFgJmDxUCH0RlcGFydG1lbnQuYXNweD9jZHNzPTE5JmNkYmg9MjQM57O75omA5LuL57uNZAIBD2QWBGYPFQIecGVyc29ubmVsLmFzcHg/Y2Rzcz0yNSZjZGJoPTI1DOS6uuaJjeWfueWFu2QCAQ8WAh8AAgcWDmYPZBYCZg8VAiJ1bmRlcmdyYWR1YXRlLmFzcHg/Y2Rzcz0yNSZjZGJoPTI2CeacrOenkeeUn2QCAQ9kFgJmDxUCG01hc3Rlci5hc3B4P2Nkc3M9MjUmY2RiaD0yNwnnoZXlo6vnlJ9kAgIPZBYCZg8VAhxNYXN0ZXJiLmFzcHg/Y2Rzcz0yNSZjZGJoPTI4CeWNmuWjq+eUn2QCAw9kFgJmDxUCHU1hc3RlcmJoLmFzcHg/Y2Rzcz0yNSZjZGJoPTI5CeWNmuWjq+WQjmQCBA9kFgJmDxUCHmluZGV4LW1wYS5hc3B4P2Nkc3M9MjUmY2RiaD0zMANNUEFkAgUPZBYCZg8VAh1wcmFjdGljZS5hc3B4P2Nkc3M9MjUmY2RiaD0zMQzlrp7kuaDln7rlnLBkAgYPZBYCZg8VAh9sYWJvcmF0b3J5LmFzcHg/Y2Rzcz0yNSZjZGJoPTMyCeWunumqjOWupGQCAg9kFgRmDxUCHHItYWJvdXQuYXNweD9jZHNzPTMzJmNkYmg9MzMM5oub55Sf5bCx5LiaZAIBDxYCHwACBBYIZg9kFgJmDxUCHHItYWJvdXQuYXNweD9jZHNzPTMzJmNkYmg9MzQM5a2m6Zmi566A5LuLZAIBD2QWAmYPFQIhcHJvZmVzc2lvbmFsLmFzcHg/Y2Rzcz0zMyZjZGJoPTM1DOS4k+S4muS7i+e7jWQCAg9kFgJmDxUCHXJlZ2lzdGVyLmFzcHg/Y2Rzcz0zMyZjZGJoPTM2DOaKpeiAg+aMh+WNl2QCAw9kFgJmDxUCH2VtcGxveW1lbnQuYXNweD9jZHNzPTMzJmNkYmg9MzcM5bCx5Lia5oyH5a+8ZAIDD2QWBGYPFQIhdGVhY2hlcnN0YWZmLmFzcHg/Y2Rzcz0zOCZjZGJoPTM4DOW4iOi1hOmYn+S8jWQCAQ8WAh8AAgcWDmYPZBYCZg8VAiRUYWRtaW5pc3RyYXRpdmUuYXNweD9jZHNzPTM4JmNkYmg9MzkM6KGM5pS/566h55CGZAIBD2QWAmYPFQIbVGh1bWFuLmFzcHg/Y2Rzcz0zOCZjZGJoPTQwDOS6uuWKm+i1hOa6kGQCAg9kFgJmDxUCIVRpbmZvcm1hdGlvbi5hc3B4P2Nkc3M9MzgmY2RiaD00MQzkv6Hmga/nrqHnkIZkAgMPZBYCZg8VAiBUbWFuYWdlbWVudC5hc3B4P2Nkc3M9MzgmY2RiaD00MhXnrqHnkIbnp5HlrabkuI7lt6XnqItkAgQPZBYCZg8VAhpUbGFuZC5hc3B4P2Nkc3M9MzgmY2RiaD00MxLlnJ/lnLDotYTmupDnrqHnkIZkAgUPZBYCZg8VAh9UcG9saXRpY2FsLmFzcHg/Y2Rzcz0zOCZjZGJoPTQ0CeaUv+ayu+WtpmQCBg9kFgJmDxUCI1RpbnRlcm5hdGlvbmFsLmFzcHg/Y2Rzcz0zOCZjZGJoPTQ1DOWbvemZheWFs+ezu2QCBA9kFgRmDxUCHXJlc2VhcmNoLmFzcHg/Y2Rzcz00NiZjZGJoPTQ2DOWtpuacr+enkeeglGQCAQ8WAh8AAgUWCmYPZBYCZg8VAhxwcm9qZWN0LmFzcHg/Y2Rzcz00NiZjZGJoPTQ3DOenkeeglOmhueebrmQCAQ9kFgJmDxUCHWFjYWRlbWljLmFzcHg/Y2Rzcz00NiZjZGJoPTQ4DOWtpuacr+iuuuaWh2QCAg9kFgJmDxUCHm1vbm9ncmFwaC5hc3B4P2Nkc3M9NDYmY2RiaD00OQzkuJPokZfmlZnmnZBkAgMPZBYCZg8VAiRyZXNlYXJjaC1yZXBvcnQuYXNweD9jZHNzPTQ2JmNkYmg9NTAM56CU56m25oql5ZGKZAIED2QWAmYPFQIbc3lzdGVtLmFzcHg/Y2Rzcz00NiZjZGJoPTUxDOenkeeglOWItuW6pmQCBQ9kFgRmDxUCIlN0dWRlbnRzLXdvcmsuYXNweD9jZHNzPTUyJmNkYmg9NTIM5a2m55Sf5bel5L2cZAIBDxYCHwACBxYOZg9kFgJmDxUCIWFubm91bmNlbWVudC5hc3B4P2Nkc3M9NTImY2RiaD01MwzpgJrnn6XlhazlkYpkAgEPZBYCZg8VAiFvcmdhbml6YXRpb24uYXNweD9jZHNzPTUyJmNkYmg9NTQM56S+5Zui6aOO6YeHZAICD2QWAmYPFQIjUGFydHktQnVpbGRpbmcuYXNweD9jZHNzPTUyJmNkYmg9NTUM5YWa5peX6aOY6aOYZAIDD2QWAmYPFQIkc3R1ZGVudGFjdGl2aXR5LmFzcHg/Y2Rzcz01MiZjZGJoPTU2DOePree6p+W7uuiuvmQCBA9kFgJmDxUCI1lvdXRoLWFjdGl2aXR5LmFzcHg/Y2Rzcz01MiZjZGJoPTU3DOWbouWnlOW3peS9nGQCBQ9kFgJmDxUCIHN0dWRlbnQtYWN0LmFzcHg/Y2Rzcz01MiZjZGJoPTU4DOWtpueUn+a0u+WKqGQCBg9kFgJmDxUCG3hpYXphaS5hc3B4P2Nkc3M9NTImY2RiaD01OQzluLjnlKjkuIvovb1kAgYPZBYEZg8VAh1zZXJ2aWNlcy5hc3B4P2Nkc3M9NjAmY2RiaD02MAznpL7kvJrmnI3liqFkAgEPFgIfAAIDFgZmD2QWAmYPFQIfY29udGludWluZy5hc3B4P2Nkc3M9NjAmY2RiaD02MQznu6fnu63mlZnogrJkAgEPZBYCZg8VAh10cmFpbmluZy5hc3B4P2Nkc3M9NjAmY2RiaD02MgznpL7kvJrln7norq1kAgIPZBYCZg8VAh1leGNoYW5nZS5hc3B4P2Nkc3M9NjAmY2RiaD02Mwzlr7nlpJbkuqTmtYFkAgcPZBYEZg8VAhthbHVtbmkuYXNweD9jZHNzPTY0JmNkYmg9NjQM6Zmi5Y+L5LmL56qXZAIBDxYCHwACAxYGZg9kFgJmDxUCG2FsdW1uaS5hc3B4P2Nkc3M9NjQmY2RiaD02NQzpmaLlj4vmtLvliqhkAgEPZBYCZg8VAiBhbHVtbmlzdHlsZS5hc3B4P2Nkc3M9NjQmY2RiaD02NgzpmaLlj4vpo47ph4dkAgIPZBYCZg8VAiJhbHVtbmlzZXJ2aWNlLmFzcHg/Y2Rzcz02NCZjZGJoPTY3DOmZouWPi+acjeWKoWQCBw8WAh4EaHJlZgUSc2RkbGlzdC5hc3B4P2NkaWQ9ZAIIDw8WAh4EVGV4dAUJ5Y2a5aOr5ZCOZGQCCg8PFgIfAgUw5LiO6Zmi57O75omA55u45YWz55qE5Y2a5aOr5ZCO566h55CG5bel5L2c5rWB56iLZGQCDA8PFgIfAgUKMjAxNC0wMy0wNWRkAg4PDxYCHwIFAzMyNGRkAhAPDxYCHwIF78kBPHAgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyOyI+DQoJPHRhYmxlIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJ3aWR0aDo0MTguNXB0O3RleHQtYWxpZ246Y2VudGVyO21hcmdpbjowIGF1dG87Ij4NCgkJPHRib2R5Pg0KCQkJPHRyPg0KCQkJCTx0ZCB3aWR0aD0iNDEiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuNTAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojRkZGRkZGOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5ZCN56ewIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCQk8dGQgd2lkdGg9IjQ2IiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjUwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0ZGRkZGRjsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0iY2VudGVyIiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpjZW50ZXI7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuaXtumXtCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQkJPHRkIHdpZHRoPSI0NzAiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuNTAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojRkZGRkZGOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5bel5L2c5rWB56iLIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCTwvdHI+DQoJCQk8dHI+DQoJCQkJPHRkIHdpZHRoPSI0MSIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNEQkVFRjM7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImNlbnRlciIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246Y2VudGVyOyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7ljZrlo6vlkI7mi5vmlLbkuI7mi5vogZggPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJCTx0ZCB3aWR0aD0iNDYiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojREJFRUYzOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+My025pyIIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCQk8dGQgd2lkdGg9IjQ3MCIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNEQkVFRjM7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249Imp1c3RpZnkiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmp1c3RpZnk7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPmw8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Jm5ic3A7PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWNmuWjq+WQjuiuoeWIku+8muS6uuS6i+WkhOWNmueuoeWKniDnu5/orqHlkITlubTluqbljZrlo6vlkI7orqHliJLkuI7mi5vmlLbmg4XlhrXjgIHlnKjnq5nkuI7mu57nq5nmg4XlhrUi5ZCE6Zmi57O75omA55Sz5oql5oub5pS26K6h5YiSPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+57uT5ZCI5Y6G5bm05Y2a5aOr5ZCO6K6h5YiS5LiO5oub5pS25oOF5Ya15ZKM5pys5bm05bqm55Sz5oql5oOF5Ya15YiG6YWN5oub5pS25oyH5qCHPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5oql6aKG5a+85a6h5om5IDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7ljZrlo6vlkI7mi5vogZjvvJrlkITpmaLns7vnu4Tnu4fmi5vogZg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7noa7lrprov5vnq5nkurrpgIk8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7kurrkuovlpITlrqHmibkgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJPC90cj4NCgkJCTx0cj4NCgkJCQk8dGQgd2lkdGg9IjQxIiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjAwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0ZGRkZGRjsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0iY2VudGVyIiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpjZW50ZXI7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPui/m+ermeaJi+e7rSA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQkJPHRkIHdpZHRoPSI0NiIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNGRkZGRkY7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImNlbnRlciIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246Y2VudGVyOyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij435pyI44CBOeaciOS4pOasoSA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQkJPHRkIHdpZHRoPSI0NzAiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojRkZGRkZGOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7ljZrlo6vlkI7ov5vnq5nvvJrlrqHmn6Xlhajlm73ljZrnrqHkvJrlt7LlrqHmibnnmoTmnZDmlpnvvIjlrqHmibnmibnku7bjgIHljZrlo6vlkI7nlLPor7fooajjgIHljZrlo6vlrabkvY3or4HkuablpI3ljbDku7bjgIHmlL/lrqHor4HmmI7vvIk8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lvIDmja7ov5vnq5npgJrnn6XkuaY8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7liIbphY3lt6XkvZzor4Hlj7c8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7loavlhpnov5vnq5nnmbvorrDooag8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lrqHmoLjlhbbkuKrkurrkv6Hmga88L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7kuLrljZrlo6vlkI7lu7rmoaMgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249Imp1c3RpZnkiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmp1c3RpZnk7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPmwgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWNmuWjq+WQjuaKpeWIsO+8muWNmueuoeS8muWNmuWjq+WQjuaJueS7tuaKpeWIsDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuiwg+aho+W5tuWuoeaguDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuetvuiuouWQiOWQjOS5puWSjOS7u+WKoeS5pjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWNmuWjq+WQjui/m+ermeS/oeaBr+W9leWFpTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWKs+i1hOWKnuWumuiWquWQr+iWqu+8iOS6uuS6i+aho+ahiOi9rOWFpeWQjuaWueWPr+i1t+iWqu+8iTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiZuYnNwO+W8gOaNruWFpeagoei9rOWNlTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWIsOS4reWbvemTtuihjOWMl+S6rOaWh+aFp+WbreaUr+ihjOWKnueQhuW3pei1hOWNoTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPui0oue7j+WkhOi/m+ihjOW3pei1hOWFs+iBlDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWIsOagoeWbreWNoeS4reW/g+WKnueQhiLmoKHlm63kuIDljaHpgJoiPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5qCh5Yy76Zmi6K+B5Lu2566h55CG5aSE5Yqe55CG5YWs6LS55Yy755aXPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Yiw5YyX5aSq5bmz5bqE5rS+5Ye65omA5ZKM5oiR5qCh5L+d5Y2r5aSE5oi357GN5a6k5Yqe55CG6JC95oi35omL57utIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCTwvdHI+DQoJCQk8dHI+DQoJCQkJPHRkIHdpZHRoPSI0MSIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNEQkVFRjM7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImNlbnRlciIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246Y2VudGVyOyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lh7rnq5nmiYvnu60gPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJCTx0ZCB3aWR0aD0iNDYiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojREJFRUYzOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5YWo5bm0IDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCQk8dGQgd2lkdGg9IjQ3MCIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNEQkVFRjM7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249Imp1c3RpZnkiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmp1c3RpZnk7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPmwgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuato+W4uOWHuuerme+8muaMgeemu+agoei9rOWNleWKnueQhuemu+agoeaJi+e7rTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuaJgOacieWHuuermeadkOaWmemZouezu+WuoeaJuTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS6uuS6i+WkhOWuoeaJuTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPue9keS4iumihOe6pjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS4reWbveWNmuWjq+WQjuWfuumHkeS8muivhOS8sOS4juacjeWKoeWkhOWKnueQhuWHuuermeaJi+e7rTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuW9kuahozwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWKs+i1hOWKnu+8iOadjueHlee6ouiAgeW4iO+8ieWKnueQhuW3pei1hOi9rOenu+ivgeaYju+8iOW3pei1hOWFs+ezu+acqui9rOWFpeWMl+W4iOWkp+eahOWNmuWjq+WQjuS4jeeUqOW8gOWFt++8iSA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ianVzdGlmeSIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246anVzdGlmeTsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+bCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5o+Q5YmN5Ye656uZ77ya5o+Q5YmN5Ye656uZ55Sz6K+3PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Lq65LqL5aSE5a6h5om5PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5oyB56a75qCh6L2s5Y2V5Yqe55CG56a75qCh5omL57utPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5omA5pyJ5Ye656uZ5p2Q5paZ6Zmi57O75a6h5om5PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Lq65LqL5aSE5a6h5om5PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+572R5LiK6aKE57qmPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Lit5Zu95Y2a5aOr5ZCO5Z+66YeR5Lya6K+E5Lyw5LiO5pyN5Yqh5aSE5Yqe55CG5Ye656uZ5omL57utPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5b2S5qGjPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Yqz6LWE5Yqe77yI5p2O54eV57qi6ICB5biI77yJ5Yqe55CG5bel6LWE6L2s56e76K+B5piO77yI5bel6LWE5YWz57O75pyq6L2s5YWl5YyX5biI5aSn55qE5Y2a5aOr5ZCO5LiN55So5byA5YW377yJIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lu7bmnJ/lh7rnq5nvvJrkuIvovb3ljZrlo6vlkI7nvZHnq5nnmoQ8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PGEgaHJlZj0iaHR0cDovL3BlcnNvbm5lbC5ibnUuZWR1LmNuL2JzaC9odG1sL3RhYmxlL2JzaHlhbnFpLmRvYyI+44CK5YyX5Lqs5biI6IyD5aSn5a2m5Y2a5aOr5ZCO5bu25pyf5Ye656uZ55Sz6K+36KGo44CLPC9hPjwvc3Bhbj4iPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5a+85biI5a6h5om5PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+6Zmi57O75a6h5om5PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Lq65LqL5aSE5a6h5om5IDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7pgIDnq5nvvJog5oyB56a75qCh6L2s5Y2V5Yqe55CG56a75qCh5omL57utPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5LiL6L295Y2a5aOr5ZCO572R56uZ55qEPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjxhIGhyZWY9Imh0dHA6Ly9wZXJzb25uZWwuYm51LmVkdS5jbi9ic2gvaHRtbC90YWJsZS9ic2h5anJ5dHpiLmRvYyI+44CK5YyX5Lqs5biI6IyD5aSn5a2m5Y2a5aOr5ZCO56CU56m25Lq65ZGY6YCA56uZ6KGo44CLPC9hPjwvc3Bhbj7lkozljZrnrqHkvJrnvZHnq5nnmoTjgIrljZrlo6vlkI7noJTnqbbkurrlkZjpgIDnq5nooajjgIs8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWvvOW4iOetvuWtlzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuaJgOWcqOWNleS9jeWuoeaguDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWhq+WGmeebuOWFs+S/oeaBr+e9keS4iumihOe6pjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS4reWbveWNmuWjq+WQjuWfuumHkeS8muivhOS8sOS4juacjeWKoeWkhOWKnueQhumAgOermeaJi+e7rTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPui/lOWbnuadkOaWmeW9kuahozwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPui9rOahoyA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQk8L3RyPg0KCQkJPHRyPg0KCQkJCTx0ZCB3aWR0aD0iNDEiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojRkZGRkZGOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Zyo56uZ566h55CGIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCQk8dGQgd2lkdGg9IjQ2IiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjAwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0ZGRkZGRjsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0iY2VudGVyIiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpjZW50ZXI7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWFqOW5tCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQkJPHRkIHdpZHRoPSI0NzAiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojRkZGRkZGOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lvIDpopjvvJrpmaLns7vnu4Tnu4flvIDpopg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7kuIvovb3lubbloavlhpnljZrlo6vlkI7nvZHnq5nnmoQ8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PGEgaHJlZj0iaHR0cDovL3BlcnNvbm5lbC5ibnUuZWR1LmNuL2JzaC9odG1sL3RhYmxlL3N0dWR5LmRvYyI+44CK5YyX5Lqs5biI6IyD5aSn5a2m5Y2a5aOr5ZCO5byA6aKY55m76K6w6KGo44CLPC9hPjwvc3Bhbj4iPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Lqk5Lq65LqL5aSE5b2S5qGjIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7kuK3mnJ/ogIPmoLjvvJrpmaLns7vnu4Tnu4fkuK3mnJ/ogIPmoLg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7kuIvovb3lubbloavlhpnljZrlo6vlkI7nvZHnq5nnmoQ8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PGEgaHJlZj0iaHR0cDovL3BlcnNvbm5lbC5ibnUuZWR1LmNuL2JzaC9odG1sL3RhYmxlL3pob25ncWlraC5kb2MiPuOAiuWMl+S6rOW4iOiMg+Wkp+WtpuWNmuWjq+WQjueglOeptuS6uuWRmOS4reacn+iAg+aguOihqOOAizwvYT48L3NwYW4+IjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS6pOS6uuS6i+WkhOW9kuahoyA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ianVzdGlmeSIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246anVzdGlmeTsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+bCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5a2m5pyv5rS75Yqo77ya5YWz5rOo5Lit5Zu95Y2a5aOr5ZCO572R56uZPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+6YKu566x77yI5oiW572R56uZ77yJ5Y+R5biD5ZCE5a2m56eR5Y2a5aOr5ZCO6K665Z2b5L+h5oGvPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+6YCa55+l55u45YWz6Zmi57O75ZKM5Liq5Lq6IDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lh7rnq5nogIPmoLjvvJrlnKjljZrlo6vlkI7miYDlnKjpmaLns7vmtYHliqjnq5nlrozmiJDjgIrljZrlo6vlkI7noJTnqbblt6XkvZzmiqXlkYrjgIs8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lsIbnoJTnqbbmiqXlkYrpgIHkuKTkvY3moKHlpJbkuJPlrrbor4TlrqE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lkIzml7bljZrlo6vlkI7lupTkuL7ooYzigJzmiqXlkYrkvJrigJ08L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7ljZrlo6vlkI7miYDlnKjorr7nq5nljZXkvY3otJ/otKPnu4Tnu4fnlLHlm5voh7PkupTkvY3kuJPlrrbmlZnmjojvvIjlhbbkuK3oh7PlsJHkuIDkvY3kuLrmoKHlpJbkuJPlrrbvvInnu4TmiJDnmoTljZrlo6vlkI7lh7rnq5nmiqXlkYror4Torq7lsI/nu4TvvIzotJ/otKPlr7njgIrljZrlo6vlkI7noJTnqbblt6XkvZzmiqXlkYrjgIvov5vooYzor4Tlrpo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lh7rnq5nmiqXlkYror4Torq7lsI/nu4TlsIbor4TlrprmhI/op4HlhpnlhaXjgIrljJfkuqzluIjojIPlpKflrabljZrlo6vlkI7noJTnqbbmiqXlkYrkuJPlrrbmhI/op4HooajjgIsgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249Imp1c3RpZnkiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmp1c3RpZnk7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPmwgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWHuuWbveaJueS7tu+8muWHuuWbvemCgOivt+S/oeWkjeWNsOS7tuS4gOS7vTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS4i+i9veW5tuWhq+WGmeWbvemZheS6pOa1geS4juWQiOS9nOWkhOe9keermeeahOOAiuWMl+S6rOW4iOiMg+Wkp+WtpuWboOWFrOWHuuWbvS/otbTmuK/mvrPlj7DlrqHmibnooajjgIs8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7pgoDor7fkv6HlpI3ljbDku7bkuIDku708L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7pmaLns7vlrqHmibk8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7otKLnu4/lpITokL3lrp7nu4/otLnmnaXmupA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7kurrkuovlpITlrqHmibkgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJPC90cj4NCgkJCTx0cj4NCgkJCQk8dGQgd2lkdGg9IjQxIiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjAwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0RCRUVGMzsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0iY2VudGVyIiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpjZW50ZXI7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWfuumHkeeUs+aKpSA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQkJPHRkIHdpZHRoPSI0NiIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNEQkVFRjM7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImNlbnRlciIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246Y2VudGVyOyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4z5pyI44CBNOaciOOAgTbmnIggPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJCTx0ZCB3aWR0aD0iNDcwIiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjAwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0RCRUVGMzsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ianVzdGlmeSIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246anVzdGlmeTsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+bCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Y2a5aOr5ZCO56eR5a2m5Z+66YeR6Z2i5LiK6LWE5Yqp5ZKM54m55Yir6LWE5Yqp77ya5Lq65LqL5aSE57uZ5ZCE55u45YWz6Zmi57O75Y+R6YCa55+lPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Y2a5aOr5ZCO572R5LiK55Sz6K+3PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5ZCI5L2c5a+85biI5oyH5a+8PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+6Zmi57O75a6h5qC457q46LSo5p2Q5paZ5bm2562+5a2X55uW56ugPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Lq65LqL5aSE5rGH5oC75bm25aSN5qC455uW56ugPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Zyo5Y2a5aOr5ZCO5Z+66YeR572R5LiK5Yqe5YWs57O757uf5o+Q5LqkPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5rGH5oC75oOF5Ya15oql5Lit5Zu95Y2a5aOr5ZCO5Z+66YeR5LyaPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Z+66YeR5Lya57uE57uH5LiT5a62572R5LiK6K+E5a6h5ZKM5Lya5a6h6K6o6K665Yaz6K6uPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Z+66YeR6K+E5a6h57uT5p6c6YCa5oql77yI5LiA6Iis5Zyo55Sz5oqlMuS4quaciOWQjumAmuaKpe+8iTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS6uuS6i+WkhOWcqOWtpuagoeWNmuWjq+WQjue9keermeS4iuWFrOW4g+iOt+mAieWfuumHkeWQjeWNlTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWfuumHkeasvuWIsOWtpuagoeWQju+8jOeUseS6uuS6i+WkhOeri+mhueaLqOS7mOe7meWNmuWjq+WQjuacrOS6ujwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWNmuWjq+WQjumAmui/h+mZouezu+i0ouWKoeaKpei0puOAgiA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ianVzdGlmeSIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246anVzdGlmeTsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+bCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Y2a5aOr5ZCO56eR5a2m5Z+66YeR6K+E5a6h5LiT5a625bqT77ya57u05oqk5Y2a5aOr5ZCO56eR5a2m5Z+66YeR6K+E5a6h5LiT5a625bqTPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5Y2P5Yqp6IGU57O75LiT5a626L+b6KGM6K+E5a6hIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCTwvdHI+DQoJCQk8dHI+DQoJCQkJPHRkIHdpZHRoPSI0MSIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNGRkZGRkY7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImNlbnRlciIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246Y2VudGVyOyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7mtYHliqjnq5nlop7orr4gPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJCTx0ZCB3aWR0aD0iNDYiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojRkZGRkZGOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5q+P5Lik5bm05byA5bGV5LiA5qyhIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCQk8dGQgd2lkdGg9IjQ3MCIgdmFsaWduPSJjZW50ZXIiIHN0eWxlPSJib3JkZXI6MS4wMDAwcHQgc29saWQgIzRCQUNDNjtiYWNrZ3JvdW5kOiNGRkZGRkY7Ij4NCgkJCQkJPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249Imp1c3RpZnkiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmp1c3RpZnk7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPmwgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWuoeaJueeoi+W6j++8muaLn+iuvuermeWNleS9jeaPkOWHuueUs+ivtzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuWuoeaguOaxh+aAu+WQjuaKpeS6uuWKm+i1hOa6kOWSjOekvuS8muS/nemanOmDqDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS4k+Wutue7hOivhOWuoe+8iOivhOiuru+8iTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij4iPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPuS6uuWKm+i1hOa6kOWSjOekvuS8muS/nemanOmDqO+8iOWFqOWbveWNmuWjq+WQjueuoeeQhuWnlOWRmOS8mu+8ieWuoeaguOaJueWHhuOAgiA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQk8L3RyPg0KCQkJPHRyPg0KCQkJCTx0ZCB3aWR0aD0iNDEiIHZhbGlnbj0iY2VudGVyIiBzdHlsZT0iYm9yZGVyOjEuMDAwMHB0IHNvbGlkICM0QkFDQzY7YmFja2dyb3VuZDojREJFRUYzOyI+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJtYXJnaW4tbGVmdDowLjAwMDBwdDt0ZXh0LWFsaWduOmNlbnRlcjsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5rWB5Yqo56uZ6K+E5LywIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJPC90ZD4NCgkJCQk8dGQgd2lkdGg9IjQ2IiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjAwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0RCRUVGMzsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0iY2VudGVyIiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpjZW50ZXI7Ij4NCgkJCQkJCTxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPue7vOWQiOivhOS8sOavjzXlubTnu4Tnu4fkuIDmrKHjgILmlrDorr7nq5nor4TkvLDmr4/lubTnu4Tnu4flvIDlsZXkuIDmrKHjgIIgPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPjwvc3Bhbj4gDQoJCQkJCTwvcD4NCgkJCQk8L3RkPg0KCQkJCTx0ZCB3aWR0aD0iNDcwIiB2YWxpZ249ImNlbnRlciIgc3R5bGU9ImJvcmRlcjoxLjAwMDBwdCBzb2xpZCAjNEJBQ0M2O2JhY2tncm91bmQ6I0RCRUVGMzsiPg0KCQkJCQk8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ianVzdGlmeSIgc3R5bGU9Im1hcmdpbi1sZWZ0OjAuMDAwMHB0O3RleHQtYWxpZ246anVzdGlmeTsiPg0KCQkJCQkJPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+bCA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+57u85ZCI6K+E5Lyw77ya77yI6K+E5Lyw5YaF5a6577ya5rWB5Yqo56uZ5bu66K6+5oOF5Ya144CB5Y2a5aOr5ZCO5oub5pS25oOF5Ya144CB56eR56CU5oOF5Ya144CB56eR56CU5oiQ5p6c44CB5Lq65omN5Z+55YW75oOF5Ya177yJ5Lq65LqL5aSE57uZ5ZCE55u45YWz6Zmi57O75Y+R6YCa55+lPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5bel5L2c5YeG5aSHPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5pWw5o2u6YeH6ZuG5LiO6Ieq5p+lPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5pWw5o2u5rGH5oC75LiO5qC45p+lPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Zm9udC1zaXplOjlwdDsiPiI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+5pWw5o2u57uf6K6h5LiO6K+E5a6aIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij48L3NwYW4+IA0KCQkJCQk8L3A+DQoJCQkJCTxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJqdXN0aWZ5IiBzdHlsZT0ibWFyZ2luLWxlZnQ6MC4wMDAwcHQ7dGV4dC1hbGlnbjpqdXN0aWZ5OyI+DQoJCQkJCQk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij5sIDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7mlrDnq5nor4TkvLDvvJrvvIjor4TkvLDlhoXlrrnvvJrmtYHliqjnq5nliLbluqblu7rorr7jgIHlt6XkvZznjq/looPku6Xlj4rljZrlo6vlkI7noJTnqbbkurrlkZjmi5vmlLblkoznp5HnoJTlt6XkvZzmg4XlhrXvvInkurrkuovlpITnu5nlkITnm7jlhbPpmaLns7vlj5HpgJrnn6U8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7lt6XkvZzlh4blpIc8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7mlbDmja7ph4fpm4bkuI7oh6rmn6U8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7mlbDmja7msYfmgLvkuI7moLjmn6U8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+Ijwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TO2ZvbnQtc2l6ZTo5cHQ7Ij7mlbDmja7nu5/orqHkuI7or4TlrpombmJzcDs8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kztmb250LXNpemU6OXB0OyI+PC9zcGFuPiANCgkJCQkJPC9wPg0KCQkJCTwvdGQ+DQoJCQk8L3RyPg0KCQk8L3Rib2R5Pg0KCTwvdGFibGU+DQo8L3A+ZGQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgEFDEltYWdlQnV0dG9uMQTjV2nsePhN8D89d6r+qQtL4aqd" />
</div>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="1951E080" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEWAwLO09awCALs0bLrBgLSwpnTCHdS8xNj6e9K3xbJ54mtBr+14KHa" />
</div>
        <header>
            <!--top end-->
            <div class="logo-bg" style="padding: 0">
                <div class=" container" style="width: 980px; background-color: #fff">
                    <div class="row clearfix" style="margin: 1% 0">
                        <div class="col-md-4 column logo-box ">
                            <a href="index.aspx">
                                <img src="images/logo.png" title="logo" class="img-responsive" alt="Cinque Terre" /></a>
                        </div>
                        <div class="col-md-5 column"></div>
                        <div class="col-md-3 column pn">
                            <div class="top-tell">
                                <p>
                                    <a href="http://www.sg.bnu.edu.cn:8082/eng/eindex.jsp" target="_blank">English Version</a>
                                </p>
                            </div>
                            <!--中文版 英文版-->
                            <div class="top-search">

                                <div class="input-group">
                                      <input name="TextBox1" type="text" id="TextBox1" class="form-control input1" />
                                    <span class="input-group-addon">

                                        <input type="image" name="ImageButton1" id="ImageButton1" src="images/sousou.png" style="border-width:0px;" />
                                    </span>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row clearfix" style="background-color: #0035B4">
                        <nav class="navbar topnav" role="navigation" style="min-height: 0; padding: 10px 0">
                            <div class="container-fluid top-nav">
                                <div class="collapse navbar-collapse top-nav" id="example-navbar-collapse">
                                    <ul class=" navbar-nav cex-list">
                                      <li class=""><a href="index.aspx">首页</a></li>
                                            
                                                    <li class="dropdown">
                                                        <a href="about.aspx?cdss=19&cdbh=19" class="dropdown-toggle">学院介绍 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="about.aspx?cdss=19&cdbh=20">学院概述</a></li>
                                                                
                                                                    <li><a href="history.aspx?cdss=19&cdbh=21">历史沿革</a></li>
                                                                
                                                                    <li><a href="structure.aspx?cdss=19&cdbh=22">组织机构</a></li>
                                                                
                                                                    <li><a href="Subject.aspx?cdss=19&cdbh=23">学科设置</a></li>
                                                                
                                                                    <li><a href="Department.aspx?cdss=19&cdbh=24">系所介绍</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="personnel.aspx?cdss=25&cdbh=25" class="dropdown-toggle">人才培养 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="undergraduate.aspx?cdss=25&cdbh=26">本科生</a></li>
                                                                
                                                                    <li><a href="Master.aspx?cdss=25&cdbh=27">硕士生</a></li>
                                                                
                                                                    <li><a href="Masterb.aspx?cdss=25&cdbh=28">博士生</a></li>
                                                                
                                                                    <li><a href="Masterbh.aspx?cdss=25&cdbh=29">博士后</a></li>
                                                                
                                                                    <li><a href="index-mpa.aspx?cdss=25&cdbh=30">MPA</a></li>
                                                                
                                                                    <li><a href="practice.aspx?cdss=25&cdbh=31">实习基地</a></li>
                                                                
                                                                    <li><a href="laboratory.aspx?cdss=25&cdbh=32">实验室</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="r-about.aspx?cdss=33&cdbh=33" class="dropdown-toggle">招生就业 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="r-about.aspx?cdss=33&cdbh=34">学院简介</a></li>
                                                                
                                                                    <li><a href="professional.aspx?cdss=33&cdbh=35">专业介绍</a></li>
                                                                
                                                                    <li><a href="register.aspx?cdss=33&cdbh=36">报考指南</a></li>
                                                                
                                                                    <li><a href="employment.aspx?cdss=33&cdbh=37">就业指导</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="teacherstaff.aspx?cdss=38&cdbh=38" class="dropdown-toggle">师资队伍 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="Tadministrative.aspx?cdss=38&cdbh=39">行政管理</a></li>
                                                                
                                                                    <li><a href="Thuman.aspx?cdss=38&cdbh=40">人力资源</a></li>
                                                                
                                                                    <li><a href="Tinformation.aspx?cdss=38&cdbh=41">信息管理</a></li>
                                                                
                                                                    <li><a href="Tmanagement.aspx?cdss=38&cdbh=42">管理科学与工程</a></li>
                                                                
                                                                    <li><a href="Tland.aspx?cdss=38&cdbh=43">土地资源管理</a></li>
                                                                
                                                                    <li><a href="Tpolitical.aspx?cdss=38&cdbh=44">政治学</a></li>
                                                                
                                                                    <li><a href="Tinternational.aspx?cdss=38&cdbh=45">国际关系</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="research.aspx?cdss=46&cdbh=46" class="dropdown-toggle">学术科研 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="project.aspx?cdss=46&cdbh=47">科研项目</a></li>
                                                                
                                                                    <li><a href="academic.aspx?cdss=46&cdbh=48">学术论文</a></li>
                                                                
                                                                    <li><a href="monograph.aspx?cdss=46&cdbh=49">专著教材</a></li>
                                                                
                                                                    <li><a href="research-report.aspx?cdss=46&cdbh=50">研究报告</a></li>
                                                                
                                                                    <li><a href="system.aspx?cdss=46&cdbh=51">科研制度</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="Students-work.aspx?cdss=52&cdbh=52" class="dropdown-toggle">学生工作 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="announcement.aspx?cdss=52&cdbh=53">通知公告</a></li>
                                                                
                                                                    <li><a href="organization.aspx?cdss=52&cdbh=54">社团风采</a></li>
                                                                
                                                                    <li><a href="Party-Building.aspx?cdss=52&cdbh=55">党旗飘飘</a></li>
                                                                
                                                                    <li><a href="studentactivity.aspx?cdss=52&cdbh=56">班级建设</a></li>
                                                                
                                                                    <li><a href="Youth-activity.aspx?cdss=52&cdbh=57">团委工作</a></li>
                                                                
                                                                    <li><a href="student-act.aspx?cdss=52&cdbh=58">学生活动</a></li>
                                                                
                                                                    <li><a href="xiazai.aspx?cdss=52&cdbh=59">常用下载</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="services.aspx?cdss=60&cdbh=60" class="dropdown-toggle">社会服务 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="continuing.aspx?cdss=60&cdbh=61">继续教育</a></li>
                                                                
                                                                    <li><a href="training.aspx?cdss=60&cdbh=62">社会培训</a></li>
                                                                
                                                                    <li><a href="exchange.aspx?cdss=60&cdbh=63">对外交流</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="alumni.aspx?cdss=64&cdbh=64" class="dropdown-toggle">院友之窗 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="alumni.aspx?cdss=64&cdbh=65">院友活动</a></li>
                                                                
                                                                    <li><a href="alumnistyle.aspx?cdss=64&cdbh=66">院友风采</a></li>
                                                                
                                                                    <li><a href="alumniservice.aspx?cdss=64&cdbh=67">院友服务</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                        <!--8-->
                                    </ul>
                                </div>
                            </div>
                        </nav>
                        <!--顶部导航-->
                    </div>
                </div>


            </div>
            <!--logo-bg-->

        </header>
        <section>
            <div class="container" style="width: 980px; margin: 0% auto; background-color: #fff; border-radius: 3px">
                <div style="width: 97%; margin: 1% auto; text-align: right">当前位置：<a href="index.aspx">首页</a>-><span id="Label5">博士后</span>->正文</div>

                <div id="right_center" class="right_center3 anli_lineheight" style="background: #fff; width: 97%; margin: 2% auto; border-radius: 5px; border: 1px solid #DCE6F0;">
                       <div class="program_dl" style="width: 90%; margin: 0 auto">
                        <div class="kec_s ">   
                            <h3 class="program_title" style="font-weight:bold;">
                                <span style="text-align: center; display: block; border-bottom: 1px solid #DCE6F0; color: #2C4A7E; padding-bottom: 1%">
                                    <span id="Label1">与院系所相关的博士后管理工作流程</span></span>
                            </h3>
                            <h5 class="program_title" style="color: #999; padding-bottom: 2%;">
                                <span style="text-align: center; display: block;">
                                    <span id="Label2">2014-03-05</span>
                                    点击率：<span id="Label4">324</span>
                                </span>
                            </h5>
                            <span id="Label3"><p style="text-align:center;">
	<table align="center" style="width:418.5pt;text-align:center;margin:0 auto;">
		<tbody>
			<tr>
				<td width="41" valign="center" style="border:1.5000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">名称 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.5000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">时间 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.5000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">工作流程 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">博士后招收与招聘 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">3-6月 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l</span><span style="font-family:宋体;font-size:9pt;">&nbsp;</span><span style="font-family:宋体;font-size:9pt;">博士后计划：人事处博管办 统计各年度博士后计划与招收情况、在站与滞站情况"各院系所申报招收计划</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">结合历年博士后计划与招收情况和本年度申报情况分配招收指标</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">报领导审批 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">博士后招聘：各院系组织招聘</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">确定进站人选</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处审批 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">进站手续 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">7月、9月两次 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">博士后进站：审查全国博管会已审批的材料（审批批件、博士后申请表、博士学位证书复印件、政审证明）</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">开据进站通知书</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">分配工作证号</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">填写进站登记表</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">审核其个人信息</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">为博士后建档 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">博士后报到：博管会博士后批件报到</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">调档并审核</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">签订合同书和任务书</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">博士后进站信息录入</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">劳资办定薪启薪（人事档案转入后方可起薪）</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">&nbsp;开据入校转单</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">到中国银行北京文慧园支行办理工资卡</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">财经处进行工资关联</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">到校园卡中心办理"校园一卡通"</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">校医院证件管理处办理公费医疗</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">到北太平庄派出所和我校保卫处户籍室办理落户手续 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">出站手续 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">全年 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">正常出站：持离校转单办理离校手续</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">所有出站材料院系审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">网上预约</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">中国博士后基金会评估与服务处办理出站手续</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">归档</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">劳资办（李燕红老师）办理工资转移证明（工资关系未转入北师大的博士后不用开具） </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">提前出站：提前出站申请</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">持离校转单办理离校手续</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">所有出站材料院系审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">网上预约</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">中国博士后基金会评估与服务处办理出站手续</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">归档</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">劳资办（李燕红老师）办理工资转移证明（工资关系未转入北师大的博士后不用开具） </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">延期出站：下载博士后网站的</span><span style="font-family:宋体;font-size:9pt;"><a href="http://personnel.bnu.edu.cn/bsh/html/table/bshyanqi.doc">《北京师范大学博士后延期出站申请表》</a></span>"<span style="font-family:宋体;font-size:9pt;">导师审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">院系审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处审批 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">退站： 持离校转单办理离校手续</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">下载博士后网站的</span><span style="font-family:宋体;font-size:9pt;"><a href="http://personnel.bnu.edu.cn/bsh/html/table/bshyjrytzb.doc">《北京师范大学博士后研究人员退站表》</a></span>和博管会网站的《博士后研究人员退站表》<span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">导师签字</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">所在单位审核</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">填写相关信息网上预约</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">中国博士后基金会评估与服务处办理退站手续</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">返回材料归档</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">转档 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">在站管理 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">全年 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">开题：院系组织开题</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">下载并填写博士后网站的</span><span style="font-family:宋体;font-size:9pt;"><a href="http://personnel.bnu.edu.cn/bsh/html/table/study.doc">《北京师范大学博士后开题登记表》</a></span>"<span style="font-family:宋体;font-size:9pt;">交人事处归档 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">中期考核：院系组织中期考核</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">下载并填写博士后网站的</span><span style="font-family:宋体;font-size:9pt;"><a href="http://personnel.bnu.edu.cn/bsh/html/table/zhongqikh.doc">《北京师范大学博士后研究人员中期考核表》</a></span>"<span style="font-family:宋体;font-size:9pt;">交人事处归档 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">学术活动：关注中国博士后网站</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">邮箱（或网站）发布各学科博士后论坛信息</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">通知相关院系和个人 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">出站考核：在博士后所在院系流动站完成《博士后研究工作报告》</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">将研究报告送两位校外专家评审</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">同时博士后应举行“报告会”</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">博士后所在设站单位负责组织由四至五位专家教授（其中至少一位为校外专家）组成的博士后出站报告评议小组，负责对《博士后研究工作报告》进行评定</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">出站报告评议小组将评定意见写入《北京师范大学博士后研究报告专家意见表》 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">出国批件：出国邀请信复印件一份</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">下载并填写国际交流与合作处网站的《北京师范大学因公出国/赴港澳台审批表》</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">邀请信复印件一份</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">院系审批</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">财经处落实经费来源</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处审批 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">基金申报 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">3月、4月、6月 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">博士后科学基金面上资助和特别资助：人事处给各相关院系发通知</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">博士后网上申请</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">合作导师指导</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">院系审核纸质材料并签字盖章</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处汇总并复核盖章</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">在博士后基金网上办公系统提交</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">汇总情况报中国博士后基金会</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">基金会组织专家网上评审和会审讨论决议</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">基金评审结果通报（一般在申报2个月后通报）</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人事处在学校博士后网站上公布获选基金名单</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">基金款到学校后，由人事处立项拨付给博士后本人</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">博士后通过院系财务报账。 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">博士后科学基金评审专家库：维护博士后科学基金评审专家库</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">协助联系专家进行评审 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">流动站增设 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">每两年开展一次 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#FFFFFF;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">审批程序：拟设站单位提出申请</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">审核汇总后报人力资源和社会保障部</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">专家组评审（评议）</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">人力资源和社会保障部（全国博士后管理委员会）审核批准。 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="41" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">流动站评估 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="46" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="center" style="margin-left:0.0000pt;text-align:center;">
						<span style="font-family:宋体;font-size:9pt;">综合评估每5年组织一次。新设站评估每年组织开展一次。 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
				<td width="470" valign="center" style="border:1.0000pt solid #4BACC6;background:#DBEEF3;">
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">综合评估：（评估内容：流动站建设情况、博士后招收情况、科研情况、科研成果、人才培养情况）人事处给各相关院系发通知</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">工作准备</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">数据采集与自查</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">数据汇总与核查</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">数据统计与评定 </span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
					<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-align:justify;">
						<span style="font-family:宋体;font-size:9pt;">l </span><span style="font-family:宋体;font-size:9pt;">新站评估：（评估内容：流动站制度建设、工作环境以及博士后研究人员招收和科研工作情况）人事处给各相关院系发通知</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">工作准备</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">数据采集与自查</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">数据汇总与核查</span><span style="font-family:宋体;font-size:9pt;">"</span><span style="font-family:宋体;font-size:9pt;">数据统计与评定&nbsp;</span><span style="font-family:宋体;font-size:9pt;"></span> 
					</p>
				</td>
			</tr>
		</tbody>
	</table>
</p></span>
                        </div>
                        <div style="border-top: 1px solid #DCE6F0; padding: 1% 0; width: 100%; overflow: hidden; margin-top: 5%">
                            
                            
                        </div>


                        
                    </div>

                </div>
            </div>
        </section>
        <!--section中间部分-->
        <footer>
            <div class="container">
                <div class="row clearfix">
                    <div class="col-md-12 column">
                        <div class="row clearfix">
                            <div class="col-md-9 column">
                               <p>
                                    学院地址：北京市海淀区新街口外大街19号 北京师范大学前主楼A区5层 
                                </p>
                                <p>
                                    联系电话：010-58808256 &nbsp; MPA咨询电话：010-58808176
                                </p>
                                <p>
                                    Copyright@2016 北京师范大学政府管理学院版权所有 &nbsp;All Rights Reserved 
                                </p>
                                <p>
                                    设计与开发：<a href="http://www.ixingzhi.cn" target="_blank" style="color:white">行知睿思 </a> 
                                </p>
                            </div>
                         <div class="col-md-3 column ">
                                <dl class="caption">
                                    <dt>
                                        <img src="images/weixin.png" alt="Cinque Terre" class="img-responsive" />
                                    </dt>
                                    <dd>公众号
                                    </dd>
                                </dl>
                                <dl class="caption">
                                    <dt>
                                        <img src="images/er.png" alt="Cinque Terre" class="img-responsive" />
                                    </dt>
                                    <dd>手机版
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </footer>
    </form>
</body>
</html>
