

<!DOCTYPE html>
<html>
<head><meta http-equiv="pragma" content="no-cache" /><meta name="renderer" content="webkit|ie-comp|ie-stand" /><meta http-equiv="cache-control" content="no-cache" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="expires" content="0" /><meta http-equiv="keywords" content="北京师范大学政府管理学院,政府管理学院,北师大政府管理学院,北师大政府管理学院,www.heu.edu.cn" /><meta http-equiv="description" content="欢迎访问北京师范大学政府管理学院" /><meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" /><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" /><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta http-equiv="X-UA-Compatible" content="IE=9" /><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" /><title>
	北京师范大学政府管理学院
</title>
    <script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/slider.js"></script>
    <script type="text/javascript" src="js/dropdown.js"></script>
    <script src="js/jquery-accordion-menu.js" type="text/javascript"></script>
    <script src="js/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="css/bootstrap.min.css" /><link rel="stylesheet" href="css/css.css" /><link rel="stylesheet" href="css/style.css" /><link rel="stylesheet" href="fonts/iconfont.css" /><link href="css/jquery-accordion-menu.css" rel="stylesheet" type="text/css" />
    <script src="js/responsive-util2.js"></script>
    <script src="js/scrolltopcontrol.js"></script>
    <script src="js/caidan.js"></script>
    <!--让bootstrap兼容ie8 
[if lte IE 8]-->
    <script type="text/javascript" src="js/respond.min.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <!--  [endif]
 [if lt IE 9]-->

    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <!-- [endif]-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <script type="text/javascript">
        $(function () {
            $('#demo01').flexslider({
                animation: "slide",
                direction: "horizontal",
                easing: "swing",
            });
            $('#demo02').flexslider({
                animation: "slide",
                direction: "vertical",
                easing: "swing"
            });

            // 使用说明
            /*
                animation: "slide", //转换方式 fade淡入淡出 slide滚动
                direction:"horizontal", //滚动方向 horizontal左右 vertical上下
                slideshowSpeed: 3000, //停留时间
                directionNav: true, //是否显示左右控制按钮 true&false
                controlNav: true, //是否显示下方控制按钮 true&false
                mousewheel: false, //是否允许鼠标控制滚动 true&fals
            */

        });
        function _openSelectLink(selecto, linkname, addclicktimename) {
            if (linkname == undefined || linkname == "")
                linkname = "value";


            var index = selecto.selectedIndex;
            var option = selecto.options[index];

            var url = option.getAttribute("value");
            if (addclicktimename != undefined && addclicktimename != "") {
                try {
                    eval(option.getAttribute(addclicktimename))
                }
                catch (e) {
                }
            }

            window.open(url);

            if (selecto.selectedIndex != 0) {
                selecto.selectedIndex = 0;
            }
        }
    </script>




    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery("#jquery-accordion-menu").jqueryAccordionMenu();

        });

        $(function () {
            //顶部导航切换

        })
        //banner轮播

    </script>
    <style>
.cex-list>li>a{
	color:#fff;
	padding:10px 19.8px;
}
</style>

</head>
<body style="background-color: #eee">
    <form name="form1" method="post" action="newshow.aspx?newid=4839&amp;wzlx=indexmpa" id="form1">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTAyOTU0NDI0OA9kFgICAw9kFhICBQ8WAh4LXyFJdGVtQ291bnQCCBYQZg9kFgRmDxUCGmFib3V0LmFzcHg/Y2Rzcz0xOSZjZGJoPTE5DOWtpumZouS7i+e7jWQCAQ8WAh8AAgUWCmYPZBYCZg8VAhphYm91dC5hc3B4P2Nkc3M9MTkmY2RiaD0yMAzlrabpmaLmpoLov7BkAgEPZBYCZg8VAhxoaXN0b3J5LmFzcHg/Y2Rzcz0xOSZjZGJoPTIxDOWOhuWPsuayv+mdqWQCAg9kFgJmDxUCHnN0cnVjdHVyZS5hc3B4P2Nkc3M9MTkmY2RiaD0yMgznu4Tnu4fmnLrmnoRkAgMPZBYCZg8VAhxTdWJqZWN0LmFzcHg/Y2Rzcz0xOSZjZGJoPTIzDOWtpuenkeiuvue9rmQCBA9kFgJmDxUCH0RlcGFydG1lbnQuYXNweD9jZHNzPTE5JmNkYmg9MjQM57O75omA5LuL57uNZAIBD2QWBGYPFQIecGVyc29ubmVsLmFzcHg/Y2Rzcz0yNSZjZGJoPTI1DOS6uuaJjeWfueWFu2QCAQ8WAh8AAgcWDmYPZBYCZg8VAiJ1bmRlcmdyYWR1YXRlLmFzcHg/Y2Rzcz0yNSZjZGJoPTI2CeacrOenkeeUn2QCAQ9kFgJmDxUCG01hc3Rlci5hc3B4P2Nkc3M9MjUmY2RiaD0yNwnnoZXlo6vnlJ9kAgIPZBYCZg8VAhxNYXN0ZXJiLmFzcHg/Y2Rzcz0yNSZjZGJoPTI4CeWNmuWjq+eUn2QCAw9kFgJmDxUCHU1hc3RlcmJoLmFzcHg/Y2Rzcz0yNSZjZGJoPTI5CeWNmuWjq+WQjmQCBA9kFgJmDxUCHmluZGV4LW1wYS5hc3B4P2Nkc3M9MjUmY2RiaD0zMANNUEFkAgUPZBYCZg8VAh1wcmFjdGljZS5hc3B4P2Nkc3M9MjUmY2RiaD0zMQzlrp7kuaDln7rlnLBkAgYPZBYCZg8VAh9sYWJvcmF0b3J5LmFzcHg/Y2Rzcz0yNSZjZGJoPTMyCeWunumqjOWupGQCAg9kFgRmDxUCHHItYWJvdXQuYXNweD9jZHNzPTMzJmNkYmg9MzMM5oub55Sf5bCx5LiaZAIBDxYCHwACBBYIZg9kFgJmDxUCHHItYWJvdXQuYXNweD9jZHNzPTMzJmNkYmg9MzQM5a2m6Zmi566A5LuLZAIBD2QWAmYPFQIhcHJvZmVzc2lvbmFsLmFzcHg/Y2Rzcz0zMyZjZGJoPTM1DOS4k+S4muS7i+e7jWQCAg9kFgJmDxUCHXJlZ2lzdGVyLmFzcHg/Y2Rzcz0zMyZjZGJoPTM2DOaKpeiAg+aMh+WNl2QCAw9kFgJmDxUCH2VtcGxveW1lbnQuYXNweD9jZHNzPTMzJmNkYmg9MzcM5bCx5Lia5oyH5a+8ZAIDD2QWBGYPFQIhdGVhY2hlcnN0YWZmLmFzcHg/Y2Rzcz0zOCZjZGJoPTM4DOW4iOi1hOmYn+S8jWQCAQ8WAh8AAgcWDmYPZBYCZg8VAiRUYWRtaW5pc3RyYXRpdmUuYXNweD9jZHNzPTM4JmNkYmg9MzkM6KGM5pS/566h55CGZAIBD2QWAmYPFQIbVGh1bWFuLmFzcHg/Y2Rzcz0zOCZjZGJoPTQwDOS6uuWKm+i1hOa6kGQCAg9kFgJmDxUCIVRpbmZvcm1hdGlvbi5hc3B4P2Nkc3M9MzgmY2RiaD00MQzkv6Hmga/nrqHnkIZkAgMPZBYCZg8VAiBUbWFuYWdlbWVudC5hc3B4P2Nkc3M9MzgmY2RiaD00MhXnrqHnkIbnp5HlrabkuI7lt6XnqItkAgQPZBYCZg8VAhpUbGFuZC5hc3B4P2Nkc3M9MzgmY2RiaD00MxLlnJ/lnLDotYTmupDnrqHnkIZkAgUPZBYCZg8VAh9UcG9saXRpY2FsLmFzcHg/Y2Rzcz0zOCZjZGJoPTQ0CeaUv+ayu+WtpmQCBg9kFgJmDxUCI1RpbnRlcm5hdGlvbmFsLmFzcHg/Y2Rzcz0zOCZjZGJoPTQ1DOWbvemZheWFs+ezu2QCBA9kFgRmDxUCHXJlc2VhcmNoLmFzcHg/Y2Rzcz00NiZjZGJoPTQ2DOWtpuacr+enkeeglGQCAQ8WAh8AAgUWCmYPZBYCZg8VAhxwcm9qZWN0LmFzcHg/Y2Rzcz00NiZjZGJoPTQ3DOenkeeglOmhueebrmQCAQ9kFgJmDxUCHWFjYWRlbWljLmFzcHg/Y2Rzcz00NiZjZGJoPTQ4DOWtpuacr+iuuuaWh2QCAg9kFgJmDxUCHm1vbm9ncmFwaC5hc3B4P2Nkc3M9NDYmY2RiaD00OQzkuJPokZfmlZnmnZBkAgMPZBYCZg8VAiRyZXNlYXJjaC1yZXBvcnQuYXNweD9jZHNzPTQ2JmNkYmg9NTAM56CU56m25oql5ZGKZAIED2QWAmYPFQIbc3lzdGVtLmFzcHg/Y2Rzcz00NiZjZGJoPTUxDOenkeeglOWItuW6pmQCBQ9kFgRmDxUCIlN0dWRlbnRzLXdvcmsuYXNweD9jZHNzPTUyJmNkYmg9NTIM5a2m55Sf5bel5L2cZAIBDxYCHwACBxYOZg9kFgJmDxUCIWFubm91bmNlbWVudC5hc3B4P2Nkc3M9NTImY2RiaD01MwzpgJrnn6XlhazlkYpkAgEPZBYCZg8VAiFvcmdhbml6YXRpb24uYXNweD9jZHNzPTUyJmNkYmg9NTQM56S+5Zui6aOO6YeHZAICD2QWAmYPFQIjUGFydHktQnVpbGRpbmcuYXNweD9jZHNzPTUyJmNkYmg9NTUM5YWa5peX6aOY6aOYZAIDD2QWAmYPFQIkc3R1ZGVudGFjdGl2aXR5LmFzcHg/Y2Rzcz01MiZjZGJoPTU2DOePree6p+W7uuiuvmQCBA9kFgJmDxUCI1lvdXRoLWFjdGl2aXR5LmFzcHg/Y2Rzcz01MiZjZGJoPTU3DOWbouWnlOW3peS9nGQCBQ9kFgJmDxUCIHN0dWRlbnQtYWN0LmFzcHg/Y2Rzcz01MiZjZGJoPTU4DOWtpueUn+a0u+WKqGQCBg9kFgJmDxUCG3hpYXphaS5hc3B4P2Nkc3M9NTImY2RiaD01OQzluLjnlKjkuIvovb1kAgYPZBYEZg8VAh1zZXJ2aWNlcy5hc3B4P2Nkc3M9NjAmY2RiaD02MAznpL7kvJrmnI3liqFkAgEPFgIfAAIDFgZmD2QWAmYPFQIfY29udGludWluZy5hc3B4P2Nkc3M9NjAmY2RiaD02MQznu6fnu63mlZnogrJkAgEPZBYCZg8VAh10cmFpbmluZy5hc3B4P2Nkc3M9NjAmY2RiaD02MgznpL7kvJrln7norq1kAgIPZBYCZg8VAh1leGNoYW5nZS5hc3B4P2Nkc3M9NjAmY2RiaD02Mwzlr7nlpJbkuqTmtYFkAgcPZBYEZg8VAhthbHVtbmkuYXNweD9jZHNzPTY0JmNkYmg9NjQM6Zmi5Y+L5LmL56qXZAIBDxYCHwACAxYGZg9kFgJmDxUCG2FsdW1uaS5hc3B4P2Nkc3M9NjQmY2RiaD02NQzpmaLlj4vmtLvliqhkAgEPZBYCZg8VAiBhbHVtbmlzdHlsZS5hc3B4P2Nkc3M9NjQmY2RiaD02NgzpmaLlj4vpo47ph4dkAgIPZBYCZg8VAiJhbHVtbmlzZXJ2aWNlLmFzcHg/Y2Rzcz02NCZjZGJoPTY3DOmZouWPi+acjeWKoWQCBw8WAh4EaHJlZgUac2RkbGlzdC5hc3B4P2NkaWQ9aW5kZXhtcGFkAggPDxYCHgRUZXh0BQNNUEFkZAIKDw8WAh8CBSrljJfkuqzluIjojIPlpKflrablrabnlJ/ov53nuqrlpITliIblip7ms5VkZAIMDw8WAh8CBQoyMDE3LTA0LTA3ZGQCDg8PFgIfAgUDMjk4ZGQCEA8PFgIfAgWMpwI8cCBhbGlnbj0iY2VudGVyIiBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJMjAwNeW5tDnmnIg05pel5qCh6ZW/5Yqe5YWs5Lya6K6o6K666YCa6L+H77yMMjAxMuW5tDbmnIgxM+aXpeS/ruiuou+8iQ0KPC9wPg0KPHAgYWxpZ249ImNlbnRlciIgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCSZuYnNwOw0KPC9wPg0KPHAgYWxpZ249ImNlbnRlciIgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCTxzdHJvbmc+56ys5LiA56ugJm5ic3A75oC7IOWImTwvc3Ryb25nPiANCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuIDmnaEmbmJzcDvkuLrnu7TmiqTlrabmoKHnmoTmlZnogrLmlZnlrabnp6nluo/lkoznlJ/mtLvnp6nluo/vvIznu7TmiqTlrabmoKHlkozlrabnlJ/nmoTlkIjms5XmnYPnm4rvvIzkv53pmpzlhazlhbHlronlhajvvIzmoLnmja7jgIrkuK3ljY7kurrmsJHlhbHlkozlm73mlZnogrLms5XjgIvjgIHjgIrkuK3ljY7kurrmsJHlhbHlkozlm73pq5jnrYnmlZnogrLms5XjgIvjgIHjgIrmma7pgJrpq5jnrYnlrabmoKHlrabnlJ/nrqHnkIbop4TlrprjgIvvvIjmlZnogrLpg6hbMjAwNV3nrKwyMeWPt+S7pO+8ieOAgeOAiumrmOetieWtpuagoeWtpueUn+ihjOS4uuWHhuWImeOAiyjmlZnogrLpg6jmlZnlraZbMjAwNV015Y+3KeOAgeOAiuWbveWutuaVmeiCsuiAg+ivlei/neinhOWkhOeQhuWKnuazleOAi++8iOaVmeiCsumDqFsyMDEyXeesrDMz5Y+35Luk77yJ77yM5Yi25a6a5pys5Yqe5rOV44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5LqM5p2hJm5ic3A75pys5Yqe5rOV6YCC55So5LqO5YW35pyJ5YyX5Lqs5biI6IyD5aSn5a2m5a2m57GN55qE5a2m55Sf44CB5bey57uP5YWl5a2m5oql5Yiw5bCa5aSE5Zyo5a2m57GN5a6h5p+l5pyf5Lit55qE5paw55Sf44CC6Z2e5a2m5Y6G5pWZ6IKy55qE5a2m55Sf5Y+C54Wn5omn6KGM44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5LiJ5p2hJm5ic3A75pys5Yqe5rOV5Lit55qE6L+d57qq6KGM5Li677yM5piv5oyH6L+d5Y+N5rOV5b6L44CB5rOV6KeE44CB6KeE56ug5oiW6ICF5a2m5qCh5ZCE6aG5566h55CG5Yi25bqm55qE6KGM5Li644CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Zub5p2hJm5ic3A75a2m5qCh5a+56L+d57qq5a2m55Sf5Z2a5oyB5om56K+E5pWZ6IKy5LiO5oOp5oiS55u457uT5ZCI55qE5Y6f5YiZ44CC5a+56L+d57qq5a2m55Sf55qE5aSE55CG6KaB5ZCI5rOV44CB5YWs5byA44CB5YWs5bmz44CB5YWs5q2j77yM5YGa5Yiw56iL5bqP5q2j5b2T44CB6K+B5o2u5YWF5YiG44CB5L6d5o2u5piO56Gu44CB5a6a5oCn5YeG56Gu44CB5aSE5YiG6YCC5b2T44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5LqU5p2hJm5ic3A75a2m55Sf5a+56L+d57qq5aSE5YiG5pyJ5oyJ56iL5bqP6L+b6KGM6ZmI6L+w44CB55Sz6L6p44CB55Sz6K+J55qE5p2D5Yip44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJJm5ic3A7DQo8L3A+DQo8cCBhbGlnbj0iY2VudGVyIiBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJPHN0cm9uZz7nrKzkuoznq6AmbmJzcDvov53nuqrlpITliIbnmoTnp43nsbvkuI7pgILnlKg8L3N0cm9uZz4gDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5YWt5p2hJm5ic3A76L+d57qq5aSE5YiG5YyF5ous5Lul5LiL5LqU56eN77yaDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5LiA77yJ6K2m5ZGK77yb77yI5LqM77yJ5Lil6YeN6K2m5ZGK77yb77yI5LiJ77yJ6K6w6L+H77yb77yI5Zub77yJ55WZ5qCh5a+f55yL77yb77yI5LqU77yJ5byA6Zmk5a2m57GN44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5LiD5p2hJm5ic3A755WZ5qCh5a+f55yL5aSE5YiG55qE5a+f55yL5pyf5LuO5YGa5Ye65aSE5YiG5Yaz5a6a5LmL5pel6LW36K6h566X77yM5pyf6ZmQ5Li65LiA5bm044CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ55WZ5qCh5a+f55yL5pyf5ruh6aG755Sx5a2m55Sf5pys5Lq65o+Q5Lqk55Sz6K+377yM6Zmi77yI57O744CB5omA77yJ5o+Q5Ye65oSP6KeB77yM5a2m55Sf5aSE44CB56CU56m255Sf5bel5L2c6YOo5oiW6ICF56CU56m255Sf6Zmi5Yaz5a6a5oyJ5pe25oiW5bu25pyf6Kej6Zmk5a+f55yL44CC55WZ5qCh5a+f55yL5pyf6Ze05Y+I5Y+R55Sf6L+d57qq6KGM5Li655qE77yM57uZ5LqI5byA6Zmk5a2m57GN5aSE5YiG44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ55WZ5qCh5a+f55yL5pyf6Ze06L+b5q2l5piO5pi+5bm25pyJ56qB5Ye66KGo546w55qE77yM5Y+v55Sz6K+35o+Q5YmN6Kej6Zmk5a+f55yL44CC55WZ5a+f5pyf5Y6f5YiZ5LiK5LiN5b6X5bCR5LqO5Y2K5bm044CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ6Kej6Zmk55WZ5qCh5a+f55yL5LiN5piv5pKk6ZSA5aSE5YiG44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5YWr5p2hJm5ic3A76L+d57qq5oOF6IqC54m55Yir6L275b6u77yM57uP5om56K+E5pWZ6IKy5pS55q2j55qE77yM5Y+v5Lul5YWN5LqI57qq5b6L5aSE5YiG44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Lmd5p2hJm5ic3A76L+d57qq5ZCO5Li75Yqo5om/6K6k6ZSZ6K+v55qE77yM5Li75Yqo5raI6Zmk5b2x5ZON5oiW6ICF5YeP6L276L+d57qq6KGM5Li65ZCO5p6c55qE77yM5oiW6ICF5Li75Yqo6YWN5ZCI6L+d57qq6LCD5p+l5LiU5a+56LCD5p+l5Y+W6K+B5pyJ6LSh54yu55qE77yM5Y+v5Lul5LuO6L275oiW6ICF5YeP6L275aSE5YiG44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Y2B5p2hJm5ic3A7Jm5ic3A75Y+X6IOB6L+r5oiW6ICF5Y+X6K+x6aqX6L+d57qq55qE77yM5oiW6ICF5Zug6L+H5aSx6L+d57qq55qE77yM5Y+v5Lul5LuO6L2744CB5YeP6L275oiW6ICF5YWN5LqI5aSE5YiG44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Y2B5LiA5p2hJm5ic3A75Y+X5aSE5YiG55qE5a2m55Sf77yM57uP5pWZ6IKy5ZCO77yM5a+56Ieq5bex5omA54qv6ZSZ6K+v5pyJ5rex5Yi76K6k6K+G77yM5bm25pyJ55yf6K+a5pS55q2j6ZSZ6K+v55qE6KGM5Yqo77yM5LiU6KGo546w56qB5Ye655qE77yM5Y+v6YWM5oOF5YeP6L275aSE5YiG44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Y2B5LqM5p2hJm5ic3A75pyJ5Lul5LiL5oOF5b2i5LmL5LiA55qE77yM5bqU5b2T5LuO6YeN5aSE5YiG77yaDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5LiA77yJ6L+d57qq6KGM5Li65b2x5ZON5oG25Yqj5oiW6ICF5Lil6YeN56C05Z2P5a2m5qCh5aOw6KqJ55qE77ybDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5LqM77yJ6L+d57qq5ZCO5oG25oSP5Liy6YCa77yM5pWF5oSP5o+Q5L6b6Jma5YGH6K+B5o2u77yM5aao56KN6LCD5p+l5Y+W6K+B55qE77ybDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5LiJ77yJ5a+55qOA5Li+5Lq644CB6K+B5Lq65oiW6ICF5YW25LuW5pyJ5YWz5Lq65ZGY6L+b6KGM5aiB6IOB44CB5L6u6L6x44CB6K+96LCk44CB6K+s6Zm35oiW6ICF5omT5Ye75oql5aSN55qE77ybDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5Zub77yJ5pWZ5ZSG44CB6IOB6L+r44CB6K+x6aqX44CB5oyH5L2/5LuW5Lq66L+d57qq55qE77ybDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5LqU77yJ562W5YiS5oiW6ICF57uE57uH576k5L2T6L+d57qq55qE77ybDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5YWt77yJ5Y+C5Yqg5raJ5aSW5rS75Yqo6L+d57qq55qE77ybDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ77yI5LiD77yJ5Zyo5qCh5pyf6Ze05pu+5Y+X6L+H5aSE5YiG55qE44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Y2B5LiJ5p2hJm5ic3A76L+d57qq5a2m55Sf5bqU6LWU5YG/6L+d57qq6KGM5Li66YCg5oiQ55qE57uP5rWO5o2f5aSx44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJJm5ic3A7DQo8L3A+DQo8cCBhbGlnbj0iY2VudGVyIiBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJPHN0cm9uZz7nrKzkuInnq6AmbmJzcDvov53nuqrooYzkuLrkuI48L3N0cm9uZz48c3Ryb25nPuWkhOWIhjwvc3Ryb25nPiANCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzljYHlm5vmnaEmbmJzcDvmnInku6XkuIvmg4XlvaLkuYvkuIDnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInov53lj43lrqrms5XvvIzlj43lr7nlm5vpobnln7rmnKzljp/liJnvvIznoLTlnY/lronlrprlm6Lnu5PvvIzmibDkubHnpL7kvJrnp6nluo/nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInmlYXmhI/ljbHlrrPlm73lrrblronlhajvvIzms4TpnLLlm73lrrbmnLrlr4bvvIzpoqDopoblm73lrrbmlL/mnYPvvIznoLTlnY/lm73lrrbnu5/kuIDnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInop6bniq/lm73lrrbms5XlvovvvIzmnoTmiJDliJHkuovniq/nvarnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzljYHkupTmnaEmbmJzcDvov53lj43lm73lrrbmnInlhbPms5XlvovjgIHms5Xop4TvvIzlj5fliLDmsrvlronnrqHnkIblpITnvZrnmoTvvIznu5nkuojku6XkuIvlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInooqvlpITku6XorablkYrlpITnvZrnmoTvvIznu5nkuojorablkYrlpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInooqvlpITku6XnvZrmrL7lpITnvZrnmoTvvIzop4blhbbmg4XoioLnu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInooqvlpITku6Xmi5jnlZnkupTlpKnku6XkuIvlpITnvZrnmoTvvIznu5nkuojorrDov4flpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInooqvlpITku6Xmi5jnlZnlha3lpKnku6XkuIrljYHlpKnku6XkuIvlpITnvZrnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInooqvlpITku6Xmi5jnlZnljYHkuIDlpKnku6XkuIrlpITnvZrmiJbogIXlirPliqjmlZnlhbvnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzljYHlha3mnaEmbmJzcDvlsIbmnqrmlK/jgIHlvLnoja/jgIHnrqHliLbliIDlhbfmiJbogIXmmJPnh4PjgIHmmJPniIbjgIHmnInmr5LjgIHmlL7lsITmgKfjgIHohZDomoDmgKfnianotKjmiJbogIXkvKDmn5Pnl4Xnl4Xljp/kvZPnrYnljbHpmanlk4Hmk4Xoh6rluKblhaXlrabmoKHmiJbogIXluKblh7rlrp7pqozlrqTjgIHku5PlupPnrYnop4Tlrprkv53nrqHlnLrmiYDvvIzpgKDmiJDkuKXph43lhazlhbHlronlhajpmpDmgqPnmoTvvIznu5nkuojorrDov4flpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvpgKDmiJDkurrouqvotKLkuqfmjZ/lpLHnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzljYHkuIPmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojorrDov4flpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvnlLHmraTpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInnp7vliqjmiJbogIXnoLTlnY/mtojpmLLorr7mlr3miJbogIXlkITnp43lronlhajjgIHmjIfnpLrmoIflv5fnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInloLXloZ7mtojpmLLpgJrpgZPjgIHml6Dngavmg4XlhrXkuIvop6blj5HmiqXoraboo4Xnva7jgIHosI7miqXngavmg4XnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInpmLvnoo3mtojpmLLovabovobjgIHkurrlkZjpgJrooYznmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInmibDkubHngavngb7njrDlnLrnp6nluo/nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInlnKjph43ngrnpmLLngavljZXkvY3miJbogIXlnLrmiYDmk4Xoh6rkvb/nlKjmmI7ngavnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzljYHlhavmnaEmbmJzcDvlnKjlrr/oiI3jgIHmlZnlrqTjgIHlm77kuabppobnrYnlnLrmiYDlkLjng5/jgIHnp4Hmi4nnlLXnur/miJbogIXov53nq6Dkvb/nlKjnlLXlmajkuI3lkKzlip3pmLvnmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvlm6DmraTlr7zoh7Tngavngb7pmanmg4XnmoTvvIznu5nkuojorrDov4fmiJbogIXnlZnmoKHlr5/nnIvlpITliIbvvJvpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzljYHkuZ3mnaEmbmJzcDvmiYDlnKjlnLDljLrmiJbogIXlrabmoKHlj5HnlJ/ngavngb7jgIHlnLDpnIfjgIHnlqvmg4XnrYnntKfmgKXmg4XlhrXml7bvvIzkuI3mnI3ku47mlL/lupzmiJbogIXlrabmoKHkvp3ms5Xlj5HluIPnmoTlkb3ku6TjgIHlhrPlrprjgIHop4TlrprvvIzkuJTkuI3lkKzlip3pmLvnmoTvvIznu5nkuojorrDov4flpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvkuKXph43mibDkubHntKfmgKXnirbmgIHkuIvlhazlhbHnp6nluo/nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHmnaEmbmJzcDvmnInkuIvliJfmibDkubHmlofljJbjgIHkvZPogrLjgIHlrabmnK/miqXlkYrnrYnlpKflnovmtLvliqjmiJbogIXpo5/loILjgIHkvJrlnLrnrYnlhazlhbHlnLrmiYDnp6nluo/jgIHljbHlrrPlhazlhbHlronlhajooYzkuLrkuYvkuIDnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4flpITliIbvvJvnlLHmraTpgKDmiJDkurrouqvotKLkuqfmjZ/lpLHnmoTvvIznu5nkuojorrDov4foh7PlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInlvLrooYzov5vlhaXlnLrlhoXvvIzkuI3lkKzlip3pmLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInov53lj43op4TlrprvvIzlnKjlnLrlhoXnh4PmlL7ng5/oirHniIbnq7nmiJbogIXlhbbku5bnianlk4HnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInlsZXnpLrkvq7ovrHmgKfmoIfor63jgIHmnaHluYXnrYnnianlk4HnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInmlYXmhI/ku6Xmi6XmjKTjgIHotbflk4TjgIHmlaPluIPosKPoqIDnrYnmlrnlvI/pgKDmiJDlhazlhbHlnLrmiYDnp6nluo/mt7fkubHnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInlkJHlnLrlhoXmipXmjrfmnYLnianvvIzkuI3lkKzlip3pmLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInlhbbku5blnKjlpKflnovpm4bkvZPmtLvliqjkuK3miJbogIXlhazlhbHlnLrmiYDph4flj5blj6/og73ljbHlrrPlhazlhbHlronlhajooYzkuLrnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHkuIDmnaEmbmJzcDvnhb3liqjmsJHml4/ku4fmgajjgIHmsJHml4/mrafop4bvvIzmiJbogIXlnKjlh7rniYjnianjgIHorqHnrpfmnLrkv6Hmga/nvZHnu5zkuK3liIrovb3mnInmsJHml4/mrafop4bjgIHkvq7ovrHlhoXlrrnnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHkuozmnaEmbmJzcDvnhb3liqjjgIHnrZbliJLpnZ7ms5Xpm4bkvJrjgIHmuLjooYzjgIHnpLrlqIHvvIzkuI3lkKzlip3pmLvnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHkuInmnaEmbmJzcDvnu4Tnu4fjgIHmlZnllIbjgIHog4Hov6vjgIHor7HpqpfjgIHnhb3liqjku5bkurrku47kuovpgqrmlZnjgIHkvJrpgZPpl6jmtLvliqjmiJbogIXlj4LkuI7jgIHliKnnlKjpgqrmlZnjgIHkvJrpgZPpl6jjgIHov7fkv6HmtLvliqjvvIzmibDkubHnpL7kvJrnp6nluo/jgIHmjZ/lrrPku5bkurrouqvkvZPlgaXlurfnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHlm5vmnaEmbmJzcDvlnKjmoKHlhoXov5vooYzlrpfmlZnmtLvliqjvvIzkuI3lkKzlip3pmLvnmoTvvIznu5nkuojkuKXph43orablkYrmiJbogIXorrDov4flpITliIbvvJvpgKDmiJDkuKXph43kuI3oia/lvbHlk43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHkupTmnaEmbmJzcDvlj4LliqDmiJbogIXmiJDnq4vpnZ7ms5Xnu4Tnu4fjgIHliIrljbDpnZ7ms5XliIrniannmoTvvIzmiJbogIXliKnnlKjmn5Dnp43mtLvliqjmiJbogIXnu4Tnu4flj5HlsZXjgIHmjqfliLbmiJDlkZjvvIzljbHlrrPlrabmoKHlj4rnpL7kvJrmraPluLjnp6nluo/nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHlha3mnaEmbmJzcDvlnKjmoKHlhoXnp4Horr7lub/mkq3nq5njgIHnlLXlj7DnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHkuIPmnaEmbmJzcDvmlYXmhI/mlaPluIPosKPoqIDvvIznoLTlnY/npL7kvJrlkozmoKHlm63nqLPlrprnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvnhb3liqjmiJbogIXnu4Tnu4fogZrkvJfpl7nkuovnmoTvvIznu5nkuojorrDov4flpITliIbjgILlhbbkuK3lhbfmnInmmrTlipvjgIHkvq7ovrHor73osKTjgIHov7fkv6HnrYnkuKXph43mg4XoioLnmoTvvIzmiJbogIXnlLHmraTkuKXph43mibDkubHnpL7kvJrnp6nluo/nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHlhavmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIzlr7nlvZPkuovkurrmiJbogIXlrabnlJ/lm6LkvZPotJ/otKPkurrnu5nkuojorablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvpgKDmiJDkuI3oia/lkI7mnpznmoTvvIznu5nkuojorrDov4fmiJbogIXnlZnmoKHlr5/nnIvlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInmnKrms6jlhozmiJDnq4vlrabnlJ/lm6LkvZPvvIzku6XlrabnlJ/lm6LkvZPlkI3kuYnku47kuovlkITnp43mtLvliqjnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlt7Lms6jlhozmiJDnq4vnmoTlrabnlJ/lm6LkvZPmiJDlkZjlkozotJ/otKPkurrvvIzkuKXph43ov53lj43npL7lm6LnrqHnkIbop4TlrprnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInmnKrnu4/lrqHmibnmk4Xoh6rnu4Tnu4fli5/mjZDjgIHmlLblj5bmtLvliqjnu4/otLnjgIHljY/kvJrkvJrotLnnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuozljYHkuZ3mnaEmbmJzcDvmnInkuIvliJfmibDkubHlrabmoKHlhazlhbHnp6nluo/ooYzkuLrkuYvkuIDnmoTvvIznu5nkuojku6XkuIvlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInmnKrnu4/mibnlh4bvvIzlnKjmlZnlrabmpbzjgIHlrr/oiI3mpbznrYnlhazlhbHlnLrmiYDllqflk5fmiJbogIXkuL7ooYzlqLHkuZDmtLvliqjvvIzlpqjnoo3ku5bkurrlt6XkvZzjgIHlrabkuaDlkozkvJHmga/vvIzkuJTkuI3lkKzlip3pmLvnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4foh7PnlZnmoKHlr5/nnIvlpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInkuKXph43mibDkubHor77loILjgIHlrp7pqozlrqTnrYnlnLrmiYDmlZnlrabnp6nluo/miJbogIXpo5/loILjgIHlrr/oiI3nrYnnlJ/mtLvlnLrmiYDnp6nluo/kuI3lkKzlip3pmLvnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIzmiJbogIXlsaHmrKHmibDkubHkuIrov7DlnLrmiYDnmoTmlZnlrabnp6nluo/jgIHnlJ/mtLvnp6nluo/vvIzkuI3lkKzlip3pmLvnmoTvvIznu5nkuojorrDov4foh7PlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInkuL7vvIjmib/vvInlip7lpKflnovmtLvliqjvvIzmnKrmjInopoHmsYLov5vooYzmiqXmibnnmoTvvIzmiJbogIXomb3nu4/mibnlh4bvvIzkuI3mjInopoHmsYLph4flj5blv4XopoHnmoTlronlhajnrqHnkIbmjqrmlr3nmoTvvIznu5nkuojkuL7vvIjmib/vvInlip7mtLvliqjnmoTotJ/otKPkurrkuKXph43orablkYrlpITliIbvvJvnlLHmraTpgKDmiJDkuI3oia/lkI7mnpznmoTvvIzmoLnmja7mg4XoioLovbvph43vvIznu5nkuojlhbborrDov4foh7PlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInliKnnlKjlhbbku5blvaLlvI/mibDkubHlrabmoKHnp6nluo/nmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4foh7PlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojorablkYrlpITliIbvvJvmg4XoioLovoPph43nmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInlnKjpnZ7mjIflrprlnLDngrnlvKDotLTpgJrnn6XjgIHot6/moIfjgIHmtbfmiqXjgIHlkK/kuovjgIHpgJrlkYrnrYnlkITnsbvlrqPkvKDlk4HvvIzkuI3lkKzlip3pmLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlnKjor77moYzjgIHljpXmiYDku6Xlj4rmoKHlhoXlu7rnrZHniannrYnlhazlhbHlnLrmiYDliLvliJLjgIHmtoLnlLvvvIzmiJbogIXmjZ/lnY/ojYnlnarjgIHoirHljYnmoJHmnKjvvIzkuI3lkKzlip3pmLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInlsIblrqDnianluKblhaXmlZnlrqTjgIHlip7lhazlrqTjgIHlrp7pqozlrqTjgIHlrr/oiI3nrYnlnLrmiYDvvIzkuI3lkKzlip3pmLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInlnKjlrr/oiI3jgIHmlZnlrqTjgIHlm77kuabppobmiJbogIXlhbbku5bnpoHmraLlkLjng5/nmoTlnLDmlrnlkLjng5/vvIzkuI3lkKzlip3pmLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInlnKjmoKHlhoXml6Dnhafnu4/okKXnmoTvvIzmiJbogIXmnKrlnKjlrabmoKHmjIflrprlnLDngrnorr7mkYrovazljZbkuKrkurrnianlk4HnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInmk4Xoh6rosIPmjaLmiJbogIXljaDnlKjlrabnlJ/lrr/oiI3nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInmk4Xoh6rlnKjlrr/oiI3kuK3nlZnlrr/moKHlpJbkurrlkZjnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHkuIDmnaEmbmJzcDvlnKjlrabnlJ/lrr/oiI3lhoXnlZnlrr/lvILmgKfmiJbogIXlnKjlvILmgKflrabnlJ/lrr/oiI3lhoXnlZnlrr/nmoTvvIznu5nkuojorrDov4flpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvpgKDmiJDmgbbliqPlvbHlk43nmoTvvIzmiJbogIXlsaHmrKHov53lj43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHkuozmnaEmbmJzcDvppa7phZLmu4vkuovvvIzmibDkubHnpL7kvJrlnLrmiYDmiJbogIXlrabmoKHnp6nluo/nmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4foh7PnlZnmoKHlr5/nnIvlpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHkuInmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvmg4XoioLovoPph43nmoTvvIznu5nkuojorrDov4fmiJbogIXnlZnmoKHlr5/nnIvlpITliIbvvJvnlLHmraTpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInlhpnmgZDlkJPkv6HmiJbogIXku6Xlhbbku5bmlrnms5XlqIHog4Hku5bkurrkurrouqvlronlhajnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlhaznhLbkvq7ovrHku5bkurrmiJbogIXmjY/pgKDkuovlrp7or73osKTku5bkurrnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInlj5HpgIHmt6vnp73jgIHkvq7ovrHjgIHmgZDlkJPmiJbogIXlhbbku5bkv6Hmga/vvIzlubLmibDku5bkurrmraPluLjnlJ/mtLvnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInlgbfnqqXjgIHlgbfmi43jgIHnqoPlkKzjgIHmlaPluIPmiJbogIXku6Xlhbbku5bmlrnlvI/kvrXniq/ku5bkurrpmpDnp4HnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInnjKXkurXku5bkurrnmoTvvIzmiJbogIXlnKjlhazlhbHlnLrmiYDmlYXmhI/oo7jpnLLouqvkvZPvvIzmg4XoioLmgbbliqPnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInnuqDnvKDmiJbogIXpqprmibDku5bkurrvvIzlvbHlk43ku5bkurrmraPluLjnlJ/mtLvjgIHlrabkuaDnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInmnInlhbbku5blubLmibDku5bkurrmraPluLjnlJ/mtLvooYzkuLrnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHlm5vmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojku6XkuIvlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInmlYXmhI/kvKTlrrPku5bkurrouqvkvZPnmoTvvIznu5nkuojorrDov4flpITliIbvvJvpgKDmiJDovbvlvq7kvKTnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvpgKDmiJDovbvkvKTnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInomb3mnKrliqjmiYvmiZPkurrvvIzkvYblr7vooYXmu4vkuovjgIHmjJHotbfmiZPmnrbnrYnkuovnq6/nmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4flpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInliqjmiYvmiZPkurrvvIzop4blhbbmg4XoioLvvIznu5nkuojkuKXph43orablkYrlpITliIbvvIznm7Toh7PlvIDpmaTlrabnsY3vvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInku6XigJzlip3mnrbigJ3kuLrlkI3vvIzlgY/oopLkuIDmlrnvvIzkv4Pkvb/kuovmgIHmianlpKfnmoTvvIznu5nkuojorrDov4flpITliIbvvJvnlLHmraTpgKDmiJDku5bkurrovbvlvq7kvKTlrrPnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInmjIHmorDmiZPkurrmiJbogIXkuLrmiZPkurrogIXmj5Dkvpvlh7blmajvvIzmnKrpgKDmiJDkvKTlrrPnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvoh7Tku5bkurrovbvlvq7kvKTlrrPnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInlpJrmrKHmrrTmiZPjgIHkvKTlrrPku5bkurrmiJbogIXkuIDmrKHmrrTmiZPjgIHkvKTlrrPlpJrkurrnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInnu5PkvJnmlpfmrrTvvIzmnKrnm7TmjqXpgKDmiJDku5bkurrkvKTlrrPnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvnm7TmjqXpgKDmiJDku5bkurrkurrouqvkvKTlrrPnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJvnu5PkvJnmlpfmrrTkuLrpppbmiJbogIXlhYjliqjmiYvmiZPkurrnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHkupTmnaEmbmJzcDvpmpDljL/jgIHmr4HlvIPjgIHpnZ7ms5XljaDmnInjgIHnp4Hoh6rlvIDmi4bmiJbogIXku6Xlhbbku5bmlrnlvI/pnZ7ms5XlpITnkIbku5bkurrpgq7ku7bnmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojorrDov4fmiJbogIXnlZnmoKHlr5/nnIvlpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHlha3mnaEmbmJzcDvlhpLnlKjku5bkurrlkI3kuYnku47kuovov53ms5Xov53nuqrmiJbogIXlhbbku5bkuI3mraPlvZPooYzkuLrvvIznu5nku5bkurrpgKDmiJDlkI3oqonmiJbogIXnu4/mtY7mjZ/lpLHnmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojorrDov4fku6XkuIrlpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHkuIPmnaEmbmJzcDvljZbmt6vjgIHlq5blqLznmoTvvIzlvJXor7HmiJbogIXku4vnu43ku5bkurrljZbmt6vnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHlhavmnaEmbmJzcDvliLbkvZzjgIHov5DovpPjgIHlpI3liLbjgIHlh7rllK7jgIHlh7rnp5/jgIHlj5HluIPmiJbogIXmkq3mlL7mt6vnp73kuabliIrjgIHlm77niYfjgIHlvbHniYfjgIHpn7Plg4/liLblk4HnrYnmt6vnp73nianlk4HnmoTvvIzmiJbogIXliKnnlKjorqHnrpfmnLrkv6Hmga/nvZHnu5zjgIHnlLXor53ku6Xlj4rlhbbku5bpgJrorq/lt6XlhbfkvKDmkq3mt6vnp73kv6Hmga/nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuInljYHkuZ3mnaEmbmJzcDvlj4LkuI7otYzljZrnmoTvvIznu5nkuojorrDov4flpITliIbvvJvlj4LkuI7otYzljZrotYzotYTovoPlpKfnmoTvvIzku6XokKXliKnkuLrnm67nmoTkuLrotYzljZrmj5DkvpvmnaHku7bnmoTvvIzogZrkvJfotYzljZrnmoTvvIzmiJbogIXli77nu5PmoKHlpJbkurrlkZjotYzljZrnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHmnaEmbmJzcDvlkLjpo5/jgIHms6jlsITmiJbogIXlj4LkuI7pnZ7ms5XliLbpgKDjgIHkubDljZbjgIHkvKDmkq3mr5Llk4HmiJbogIXlhbbku5bnpoHnlKjoja/lk4HnmoTvvIzop4bmg4XoioLovbvph43vvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHkuIDmnaEmbmJzcDvlj4LliqDmiJbogIXku4vnu43ku5bkurrlj4LliqDpnZ7ms5XkvKDplIDnrYnpnZ7ms5XllYbkuJrmtLvliqjvvIzkuI3lkKzlip3pmLvnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvnlLHmraTpgKDmiJDmgbbliqPlvbHlk43nmoTvvIznu5nkuojorrDov4foh7PlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHkuozmnaEmbmJzcDvnm5fnqoPjgIHor4jpqpfjgIHlk4TmiqLjgIHmlbLor4jli5LntKLlhaznp4HotKLnianvvIzlnKjlm73lrrbnq4vmoYjmoIflh4bku6XkuIvnmoTvvIznu5nkuojorrDov4flpITliIbvvJvlnKjlm73lrrbnq4vmoYjmoIflh4bku6XkuIrlrprnvarmoIflh4bku6XkuIvnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvlnKjlm73lrrblrprnvarmoIflh4bku6XkuIrnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHkuInmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLovoPph43nmoTvvIznu5nkuojorrDov4flpITliIbvvJvnlLHmraTpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInlvITomZrkvZzlgYfvvIzosI7miqXlrrbluq3nu4/mtY7nirblhrXvvIzpqpfpooblpZbliqnlrabph5HjgIHlm7Dpmr7ooaXliqnmiJbogIXliqnlrabotLfmrL7nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInnm5fnlKjku5bkurrvvIjlkKvljZXkvY3vvInlkITnp43or4HljaHotKblj7flkozlr4bnoIHvvIjlkKvnvZHnu5znlKjmiLfnmoTotKblj7flkozlr4bnoIHvvInnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInovazlgJ/lrabnlJ/or4HjgIHmoKHlm63ljaHmiJbogIXlhbbku5bku4XpmZDmoKHlhoXkuKrkurrkvb/nlKjnmoTor4HljaHotKblj7flkozlr4bnoIHvvIjlkKvnvZHnu5znlKjmiLfnmoTotKblj7flkozlr4bnoIHvvInlubbpgKDmiJDkuI3oia/lkI7mnpznmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInlgbfnqoPlhaznq6DjgIHkv53lr4bmlofku7bjgIHmoaPmoYjnrYnnianlk4HnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInnp4Hoh6rmtoLmlLnjgIHkvKrpgKDor4Hku7bjgIHlhaznq6DnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInkvKrpgKDjgIHnr6HmlLnmiJbogIXlhpLnlKjlrabmoKHmlofku7bmiJbogIXorrDlvZXnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInosI7miqXkuKLlpLHlj4rlhpLlkI3ooaXlip7or4Hku7bnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlhavvvInkvKrpgKDmiJbogIXpnZ7ms5XlgJLljZblrabmoKHlkITnp43or4HljaHnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHlm5vmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLovoPph43nmoTvvIznu5nkuojorrDov4flpITliIbvvJvnlLHmraTpgKDmiJDkuKXph43lkI7mnpznmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInmlYXmhI/mjZ/lnY/lhazlhbHpl6jnqpfjgIHnjrvnkoPjgIHnhafmmI7orr7lpIfjgIHlhazlhbHorqHnrpfmnLrlj4rnvZHnu5zorr7mlr3jgIHpn7Plg4/mkq3mlL7orr7lpIfnrYnlkITnp43lrabmoKHlhazlhbHnianlk4HnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlgbfnqoPmiJbogIXmlYXmhI/mkpXmr4HjgIHmjZ/lnY/lm77kuabppobjgIHotYTmlpnlrqTnmoTlm77kuabjgIHmiqXliIrnmoTvvIzmiJbogIXmnKrnu4/orrjlj6/mgbbmhI/kuIvovb3lm77kuabnlLXlrZDotYTmupDnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInmnKrnu4/lhYHorrjvvIzkvrXlhaXku5bkurrmiJbogIXlhazlhbHorqHnrpfmnLrnvZHnu5zns7vnu5/vvIzlr7norqHnrpfmnLrkv6Hmga/ns7vnu5/jgIHlupTnlKjnqIvluo/jgIHmlbDmja7jgIHkv6Hmga/lrZjlgqjmiJbogIXnvZHnu5znrYnov5vooYzmk43kvZzvvIzpgKDmiJDmjZ/lrrPnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInmlYXmhI/liLbkvZzjgIHkvKDmkq3orqHnrpfmnLrnl4Xmr5LnrYnnoLTlnY/mgKfnqIvluo/vvIzlvbHlk43orqHnrpfmnLrnvZHnu5zns7vnu5/mraPluLjov5DooYznmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInkuLrkvrXniq/lm73lrrbjgIHpm4bkvZPmiJbogIXku5bkurrotKLkuqfogIXmj5Dkvpvkv6Hmga/jgIHlt6XlhbfnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInmmI7nn6XmmK/otYPnianogIzotK3kubDnmoTvvIzluK7liqnmiJbogIXmnInmjqnnm5bjgIHnqp3ol4/jgIHplIDmr4HjgIHovaznp7votYPniannrYnooYzkuLrnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInmnKrlsL3nrqHnkIbotKPku7vvvIzoh7Tkvb/lhaznianmr4HmjZ/jgIHkuKLlpLHmiJbogIXnrqHnkIblhaznianmnInmta7miqXjgIHmjKrnlKjjgIHotKbnm67kuI3muIXnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlhavvvInlhbbku5bkvrXniq/lhaznp4HotKLkuqfmnYPliKnnmoTooYzkuLrjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHkupTmnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojku6XkuIvlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInms4TpnLLlrabmoKHnp5HmioDmiJDmnpzjgIHmioDmnK/otYTmlpnnrYnnp5jlr4botYTmlpnnmoTvvIznu5nkuojkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4fku6XkuIrlpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInmnKrnu4/orrjlj6/vvIznp4Hoh6rovazorqnjgIHkvb/nlKjlrabmoKHnn6Xor4bkuqfmnYPnmoTvvIznu5nkuojorrDov4flpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInmnKrnu4/lhYHorrjvvIzmk4Xoh6rlsIbku5bkurrnmoTmiJbogIXoh6rlt7Hlj6rmmK/kvZzkuLrmiJDlkZjkuYvkuIDnmoTpm4bkvZPnmoTnp5HnoJTmiJDmnpzjgIHlrp7pqozmlbDmja7jgIHnoJTnqbbmiqXlkYrnrYnku6Xoh6rlt7HkuKrkurrlkI3kuYnlhazlvIDlj5HooajnmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4foh7PlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHlha3mnaEmbmJzcDvmnInkuIvliJfooYzkuLrkuYvkuIDnmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4flpITliIbvvJvku47kuK3osIvlj5bkuKrkurrliKnnm4rnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvmiJbogIXlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInmnKrnu4/mibnlh4bmk4Xoh6rku6XlrabmoKHlkI3kuYnlr7nlpJblj5HluIPlhazlkYrjgIHmlrDpl7vvvIzmiJbogIXmk4Xoh6rku6PooajlrabmoKHlgZrlh7rmib/or7rvvIzmiJbogIXmk4Xoh6rku6PooajlrabmoKHlnKjnpL7kvJrkuIrlj4LliqDmtLvliqjnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlnKjkuKrkurrnmoTllYbkuJrmtLvliqjkuK3vvIzlhazlvIDlnKjmi5vniYzjgIHlub/lkYrjgIHmtbfmiqXjgIHmlofku7bnrYnmnInlhbPlrqPkvKDmnZDmlpnkuIrkvb/nlKjlrabmoKHnmoTlkI3np7DmiJbogIXmoIfor4bvvIzpgKDmiJDkuI3oia/lvbHlk43nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInmnKrnu4/mibnlh4bmk4Xoh6rku6XlrabmoKHjgIHpmaLvvIjns7vjgIHmiYDvvInnrYnmnLrmnoTmiJbogIXlrabnlJ/nu4Tnu4fnmoTlkI3kuYnlnKjnpL7kvJrkuIrmtLvliqjvvIzpgKDmiJDkuI3oia/lvbHlk43nmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHkuIPmnaEmbmJzcDvlpqjnoo3lrabmoKHmlZnogYzlkZjlt6XmjInnhafop4Tlrprlrp7mlr3nrqHnkIbvvIznoLTlnY/lrabmoKHnrqHnkIbnp6nluo/nmoTvvIznu5nkuojorablkYrmiJbogIXkuKXph43orablkYrlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojorrDov4fmiJbogIXnlZnmoKHlr5/nnIvlpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlm5vljYHlhavmnaEmbmJzcDvml7for77vvIzkuIDlrabmnJ/lhoXnrKzkuIDmrKHntK/orqHovr7liLAyMOWtpuaXtueahO+8jOe7meS6iOitpuWRiuWkhOWIhu+8m+esrOS6jOasoee0r+iuoeaXt+ivvjIw5a2m5pe255qE77yM57uZ5LqI6K6w6L+H5aSE5YiG77yb56ys5LiJ5qyh57Sv6K6h5pe36K++MjDlrabml7bnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbjgILnlZnmoKHlr5/nnIvmnJ/pl7Tml7for77ntK/orqHovr7liLAyMOWtpuaXtueahO+8jOe7meS6iOW8gOmZpOWtpuexjeWkhOWIhuOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeaMieWRqOiuoeeul+eahOWunui3teeOr+iKguWcqOe0r+iuoeWtpuaXtuaXtu+8jOavj+WkqeaMiTblrabml7borqHnrpfjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnml6Dor77mnJ/pl7TmnKrnu4/mibnlh4bmk4Xoh6rnprvmoKHnmoTvvIzmjInnhafml7for77lpITnkIbjgILml7for77ml7bmlbDmjInmr4/lpKk15a2m5pe26K6h566X44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5Zub5Y2B5Lmd5p2hJm5ic3A75pyq57uP5om55YeG77yM6L+e57ut56a75qCh5aSp5pWwNOWkqeS7peS4i+eahO+8jOe7meS6iOitpuWRiuWkhOWIhu+8m+i+vuWIsDXoh7M25aSp55qE77yM57uZ5LqI5Lil6YeN6K2m5ZGK5aSE5YiG77yb6L6+5YiwN+iHszjlpKnnmoTvvIznu5nkuojorrDov4flpITliIbvvJvovr7liLA56IezMTDlpKnnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvovr7liLAxMeWkqeS7peS4iueahO+8jOe7meS6iOW8gOmZpOWtpuexjeWkhOWIhuOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCei/nue7reWkqeaVsOeahOiuoeeul+S4reS4jeiuoeWRqOWFreOAgeWRqOaXpeOAgeazleWumuiKguWBh+aXpeWSjOWtpuagoeinhOWumueahOWBh+acn+OAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS6lOWNgeadoSZuYnNwO+Wxoeasoei/n+WIsOOAgeaXqemAgOetiei/neWPjeiAg+WLpOe6quW+i+eahO+8jOe7meS6iOitpuWRiuWkhOWIhu+8m+aDheiKguS4pemHjeeahO+8jOe7meS6iOiusOi/h+WkhOWIhuOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS6lOWNgeS4gOadoSZuYnNwO+acieS4i+WIl+ihjOS4uuS5i+S4gOeahO+8jOe7meS6iOS7peS4i+WkhOWIhu+8mg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS4gO+8ieS4juWtpuagoee6puWumuaJv+aLheWKqeaVmeOAgeWKqeeuoeOAgeWKqeeglOaIluiAheWFtuS7luaVmeWtpuenkeeglOa0u+WKqO+8jOacque7j+aJueWHhu+8jOaTheiHquS4jeWPguWKoOaIluiAhee7iOatouWPguWKoO+8jOaDheiKguS4pemHjeeahO+8jOe7meS6iOitpuWRiuaIluiAheS4pemHjeitpuWRiuWkhOWIhu+8m+eUseatpOe7meebuOWFs+W3peS9nOW4puadpemHjeWkp+aNn+WkseeahO+8jOe7meS6iOiusOi/h+iHs+W8gOmZpOWtpuexjeWkhOWIhu+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS6jO+8ieWPguWKoOWtpuagoee7hOe7h+eahOekvuS8muWunui3teetiea0u+WKqO+8jOacque7j+aJueWHhu+8jOaTheiHquS4jeWPguWKoOaIluiAhee7iOatouWPguWKoO+8jOaDheiKguS4pemHjeeahO+8jOe7meS6iOitpuWRiuaIluiAheS4pemHjeitpuWRiuWkhOWIhu+8m+eUseatpOe7meebuOWFs+a0u+WKqOmAoOaIkOmHjeWkp+aNn+WkseeahO+8jOinhuaDheiKgui9u+mHje+8jOe7meS6iOiusOi/h+iHs+W8gOmZpOWtpuexjeWkhOWIhu+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS4ie+8ieWPguWKoOS4iui/sOa0u+WKqOacn+mXtOaVheaEj+i/neWPjeacieWFs+inhOWumuOAgeW9seWTjea0u+WKqOato+W4uOW8gOWxle+8jOaDheiKguS4pemHjeeahO+8jOe7meS6iOitpuWRiuiHs+iusOi/h+WkhOWIhuOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS6lOWNgeS6jOadoSZuYnNwO+iAg+ivleS4reS4jemBteWuiOiAg+ivlee6quW+i++8jOS4jeacjeS7juiAg+ivleW3peS9nOS6uuWRmOeahOWuieaOkuWSjOimgeaxgu+8jOacieS4i+WIl+i/nee6quihjOS4uuS5i+S4gOeahO+8jOe7meS6iOitpuWRiuaIluiAheS4pemHjeitpuWRiuWkhOWIhu+8m+Wxoeasoei/neWPje+8jOS4jeWQrOWKnemYu+eahO+8jOaIluiAheaDheiKguS4pemHjeeahO+8jOe7meS6iOiusOi/h+S7peS4iuWkhOWIhu+8mg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS4gO+8ieacquaQuuW4puinhOWumueahOWHhuiAg+ivgeOAgeWtpueUn+ivgeOAgei6q+S7veivgeetiei6q+S7veivgeS7tuW8uuihjOi/m+WFpeiAg+WcuuWPguWKoOiAg+ivle+8jOS4jeWQrOWKnemYu+eahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS6jO+8ieaQuuW4puinhOWumuS7peWklueahOeJqeWTgei/m+WFpeiAg+WcuuaIluiAheacquaUvuWcqOaMh+WumuS9jee9rueahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS4ie+8ieacquWcqOinhOWumueahOW6p+S9jeWPguWKoOiAg+ivle+8jOS4jeWQrOWKnemYu+eahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOWbm++8ieiAg+ivleW8gOWni+S/oeWPt+WPkeWHuuWJjeetlOmimOaIluiAhee7k+adn+S/oeWPt+WPkeWHuuWQjue7p+e7reetlOmimOeahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS6lO+8ieWcqOiAg+ivlei/h+eoi+S4reaXgeeqpeOAgeS6pOWktOaOpeiAs+OAgeS6kuaJk+aal+WPt+aIluiAheaJi+WKv+eahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOWFre+8ieWcqOiAg+WcuuaIluiAheWtpuagoeemgeatoueahOiMg+WbtOWGhe+8jOWWp+WTl+OAgeWQuOeDn+aIluiAheWunuaWveWFtuS7luaJsOS5seiAg+WcuuenqeW6j+eahOihjOS4uueahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS4g++8ieacque7j+iAg+ivleW3peS9nOS6uuWRmOWQjOaEj+WcqOiAg+ivlei/h+eoi+S4reaTheiHquemu+W8gOiAg+WcuueahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOWFq++8ieacque7j+WFgeiuuO+8jOWwhuivleWNt+OAgeetlOWNt++8iOWQq+etlOmimOWNoeOAgeetlOmimOe6uOetie+8jOS4i+WQjO+8ieOAgeiNieeov+e6uOetieiAg+ivleeUqOe6uOW4puWHuuiAg+WcuueahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOS5ne+8ieeUqOinhOWumuS7peWklueahOeslOaIluiAhee6uOetlOmimOaIluiAheWcqOivleWNt+inhOWumuS7peWklueahOWcsOaWueS5puWGmeWnk+WQjeOAgeiAg+WPt+aIluiAheS7peWFtuS7luaWueW8j+WcqOetlOWNt+S4iuagh+iusOS/oeaBr+eahO+8mw0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCe+8iOWNge+8iSDkuqTljbflkI7lvLrooYzmi7/lm57or5Xljbfkv67mlLnnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjljYHkuIDvvInmlYXmhI/mibDkubHogIPngrnjgIHogIPlnLrjgIHor4TljbflnLrmiYDnrYnogIPor5Xlt6XkvZzlnLrmiYDnp6nluo/vvIzmi5Lnu53miJbogIXlpqjnoo3ogIPor5Xlt6XkvZzkurrlkZjlsaXooYzlt6XkvZzogYzotKPnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjljYHkuozvvInlhbbku5bov53lj43ogIPlnLrop4TliJnkvYblsJrmnKrmnoTmiJDkvZzlvIrnmoTooYzkuLrjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkupTljYHkuInmnaEmbmJzcDvogIPor5XkuK3ov53og4zogIPor5XlhazlubPjgIHlhazmraPljp/liJnvvIzmnInkuIvliJfkvZzlvIrooYzkuLrkuYvkuIDnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInlnKjpl63ljbfogIPor5XkuK3vvIzmkLrluKbkuI7ogIPor5XlhoXlrrnnm7jlhbPnmoTmnZDmlpnmiJbogIXlrZjlgqjmnInkuI7ogIPor5XlhoXlrrnnm7jlhbPotYTmlpnnmoTnlLXlrZDorr7lpIflj4LliqDogIPor5XnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlnKjpl63ljbfogIPor5XkuK3vvIzkvb/nlKjnm7jlhbPorr7lpIfmkJzntKLjgIHmtY/op4jkuI7ogIPor5XlhoXlrrnnm7jlhbPnmoTnvZHnu5zkv6Hmga/nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInlnKjpl63ljbfogIPor5XkuK3vvIzmkLrluKblhbfmnInlj5HpgIHmiJbogIXmjqXmlLbkv6Hmga/lip/og73nmoTorr7lpIfnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInmioTooq3miJbogIXljY/liqnku5bkurrmioTooq3or5XpopjnrZTmoYjmiJbogIXkuI7ogIPor5XlhoXlrrnnm7jlhbPnmoTotYTmlpnnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInmiqLlpLrjgIHnqoPlj5bku5bkurror5XljbfjgIHnrZTljbfmiJbogIXog4Hov6vku5bkurrkuLroh6rlt7HmioTooq3mj5Dkvpvmlrnkvr/nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInogIPor5XmnJ/pl7TlnKjogIPlnLrlpJblgbfnnIvmiJbogIXkuI7ku5bkurrkuqTmtYHogIPor5XmnInlhbPlhoXlrrnnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInmlYXmhI/plIDmr4Hor5XljbfjgIHnrZTljbfmiJbogIXogIPor5XmnZDmlpnnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlhavvvInlnKjnrZTljbfkuIrloavlhpnkuI7mnKzkurrouqvku73kuI3nrKbnmoTlp5PlkI3jgIHlrablj7fnrYnkv6Hmga/nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuZ3vvInkvKDjgIHmjqXnianlk4HmiJbogIXkuqTmjaLor5XljbfjgIHnrZTljbfjgIHojYnnqL/nurjnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjljYHvvInlhbbku5bku6XkuI3mraPlvZPmiYvmrrXojrflvpfmiJbogIXor5Xlm77ojrflvpfor5XpopjnrZTmoYjjgIHogIPor5XmiJDnu6nnmoTooYzkuLrjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkupTljYHlm5vmnaEmbmJzcDvogIPor5XkuK3mnInkuIvliJfkvZzlvIrooYzkuLrkuYvkuIDnmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvIkmbmJzcDsmbmJzcDvogIPor5Xov4fnqIvkuK3vvIzlkJHlnLrlpJblj5HpgIHjgIHkvKDpgJLor5Xpopjkv6Hmga/nmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvIkmbmJzcDsmbmJzcDvogIPor5Xov4fnqIvkuK3vvIzkvb/nlKjnm7jlhbPorr7lpIfmjqXmlLbkv6Hmga/lrp7mlr3kvZzlvIrnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInnlLHku5bkurrku6Pmm7/lj4LliqDogIPor5XnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInku6Pmm7/ku5bkurrlj4LliqDogIPor5XnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInnu4Tnu4flm6LkvJnkvZzlvIrnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInkuLrkvZzlvIrnu4Tnu4fogIXmj5Dkvpvor5Xpopjkv6Hmga/jgIHnrZTmoYjlj4rnm7jlupTorr7lpIfnrYnlj4LkuI7lm6LkvJnkvZzlvIrooYzkuLrnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInlgbfnm5for5XljbfnmoTvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlhavvvInnrKzkuozmrKHkvZzlvIrnmoTjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkupTljYHkupTmnaEmbmJzcDvlnKjlkITnp43kvZPogrLnq57otZvkuK3mnInmnI3nlKjov53npoHoja/niannrYnmrLrpqpfooYzkuLrnmoTvvIznu5nkuojorrDov4flpITliIbvvJvlhbbkuK3lnKjmoKHnuqfku6XkuIrmr5TotZvkuK3lj5HnlJ/nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkupTljYHlha3mnaEmbmJzcDvnlLHku5bkurrku6Pmm7/miJbogIXku6Pmm7/ku5bkurrlj4LliqDlkITnp43kvZPogrLnq57otZvnmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbvvJvlnKjmoKHnuqfku6XkuIrmr5TotZvkuK3lj5HnlJ/nmoTvvIznu5nkuojlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkupTljYHkuIPmnaEmbmJzcDvmnInkuIvliJfov53lj43lrabmnK/op4TojIPooYzkuLrkuYvkuIDnmoTvvIznu5nkuojku6XkuIvlpITliIbvvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInlnKjor77nqIvkvZzkuJrjgIHnp5HlrabnoJTnqbbmiqXlkYrmiJbogIXlhbbku5bmnKrmraPlvI/lj5HooajnmoTlrabmnK/miJDmnpzkuK3vvIzmnInlib3nqoPjgIHpgKDlgYfnrYnov53lj43lrabmnK/op4TojIPooYzkuLrnmoTvvIzop4blhbbmg4XoioLovbvph43vvIznu5nkuojkuKXph43orablkYroh7PlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInlnKjmkrDlhpnmr5XkuJrorrrmlofvvIjorr7orqHvvInmiJbogIXlrabkvY3orrrmlofov4fnqIvkuK3mnInlib3nqoPjgIHpgKDlgYfnrYnov53lj43lrabmnK/op4TojIPooYzkuLrnmoTvvIzop4bmg4XoioLovbvph43vvIznu5nkuojorrDov4foh7PlvIDpmaTlrabnsY3lpITliIbvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInlnKjmoKHlrabkuaDmnJ/pl7Tlj5HooajnmoTlrabmnK/orrrmlofjgIHkuJPokZfvvIzkuLvnvJbjgIHlj4LnvJbkuabnsY3kuK3mnInlib3nqoPjgIHpgKDlgYfnrYnooYzkuLrnmoTvvIzop4blhbbmg4XoioLovbvph43vvIznu5nkuojorrDov4fku6XkuIrlpITliIbvvJvlnKjlrabmnK/nlYzlkoznpL7kvJrkuIrkuqfnlJ/mgbbliqPlvbHlk43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvoh7PlvIDpmaTlrabnsY3lpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkupTljYHlhavmnaEmbmJzcDvmtoLmlLnjgIHkvKrpgKDmiJDnu6nljZXjgIHnrb7lrZfjgIHljbDnq6DjgIHmjqjojZDkv6HmiJbogIXlhbbku5bmnInlhbPlrabkuJrjgIHlrabmnK/msLTlubPor4HmmI7nmoTvvIznu5nkuojorrDov4flpITliIbvvJvmg4XoioLkuKXph43nmoTvvIznu5nkuojnlZnmoKHlr5/nnIvlpITliIbjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgkmbmJzcDsNCjwvcD4NCjxwIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgk8c3Ryb25nPuesrOWbm+eroCZuYnNwO+WkhOWIhjwvc3Ryb25nPjxzdHJvbmc+56iL5bqPPC9zdHJvbmc+IA0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS6lOWNgeS5neadoSZuYnNwO+WtpueUn+WkhOi0n+i0o+WkhOeQhuacrOenkeeUn+i/nee6quihjOS4uu+8m+eglOeptueUn+W3peS9nOmDqOOAgeeglOeptueUn+mZoui0n+i0o+WkhOeQhueglOeptueUn+i/nee6quihjOS4uuOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOWFreWNgeadoSZuYnNwO+WPkeeOsOWtpueUn+i/nee6quS6i+S7tuWQju+8jOeUseebuOWFs+mDqOmXqOaMh+WumuS6uuWRmOe7hOaIkOiwg+afpeWwj+e7hO+8iOaIkOWRmOS4jeWwkeS6jjLkurrvvInvvIzph4flj5blkIjms5XnmoTmlrnlvI/mn6XmuIXkuovlrp7vvIzmlLbpm4bor4Hmja7vvIzlubbkvZzosIPmn6XorrDlvZXjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnkuI7lrabnlJ/mnInliKnlrrPlhbPns7vmiJbogIXnm7TmjqXmtonlj4rov53nuqrkuovku7bnmoTlvZPkuovkurrlupTlvZPlm57pgb/jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlha3ljYHkuIDmnaEmbmJzcDvlrabnlJ/ov53lj43lrabkuaDnuqrlvovnmoTooYzkuLrvvIzmnKznp5HnlJ/nlLHmlZnliqHlpITotJ/otKPosIPmn6XjgIHlj5bor4HvvIzlubblkJHlrabnlJ/lpITmj5Dlh7rlpITnkIblu7rorq7vvJvnoJTnqbbnlJ/nlLHnoJTnqbbnlJ/pmaLosIPmn6XjgIHlj5bor4HvvIzlubbmj5Dlh7rlpITnkIblu7rorq7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnlrabnlJ/ov53lj43lrr/oiI3nrqHnkIbop4TlrprnmoTooYzkuLrvvIznlLHmoKHlrr/oiI3nrqHnkIbkuK3lv4PotJ/otKPosIPmn6XjgIHlj5bor4HvvIzlubblkJHlrabnlJ/lpITmiJbogIXnoJTnqbbnlJ/lt6XkvZzpg6jmj5Dlh7rlpITnkIblu7rorq7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnlrabnlJ/ov53lj43npL7lm6LnrqHnkIbop4TlrprnmoTooYzkuLrvvIznlLHmoKHlm6Llp5TotJ/otKPosIPmn6XjgIHlj5bor4HvvIzlubblkJHlrabnlJ/lpITmiJbnoJTnqbbnlJ/lt6XkvZzpg6jmj5Dlh7rlpITnkIblu7rorq7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnlrabnlJ/ov53lj43msrvlronnrqHnkIblpITnvZrms5XmiJbogIXmnInlhbbku5bov53ms5Xniq/nvarooYzkuLrnmoTvvIznlLHkv53ljavlpITkvp3mja7lj7jms5XmnLrlhbPlpITnkIbnu5PmnpzvvIzlubblkJHlrabnlJ/lpITmiJbnoJTnqbbnlJ/lt6XkvZzpg6jmj5Dlh7rlpITnkIblu7rorq7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnlrabnlJ/lhbbku5bov53nuqrooYzkuLrnlLHlrabpmaLvvIjns7vjgIHmiYDvvInkvJrlkIznm7jlhbPpg6jpl6josIPmn6XjgIHlj5bor4HvvIzlubblkJHlrabnlJ/lpITmiJbogIXnoJTnqbbnlJ/lt6XkvZzpg6jmj5Dlh7rlpITnkIblu7rorq7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlha3ljYHkuozmnaEmbmJzcDvkuIvliJflkITpobnor4Hmja7vvIznu4/ov4fmn6Xor4HmoLjlrp7lkI7vvIzlj6/ku6XkvZzkuLrlpITliIbov53nuqrlrabnlJ/nmoTkvp3mja7vvJoNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIDvvInkuabor4HvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuozvvInnianor4HvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuInvvInor4Hkurror4HoqIDvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlm5vvvInlvZPkuovkurrnmoTpmYjov7DvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkupTvvInop4blkKzotYTmlpnvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlha3vvInpibTlrprnu5PorrrvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjkuIPvvInli5jpqoznrJTlvZXjgIHnjrDlnLrnrJTlvZXvvJsNCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnvvIjlhavvvInlhbbku5bmnInlhbPpg6jpl6jkvp3ms5XlgZrlh7rnmoTpibTlrprmgKfnu5PorrrjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlha3ljYHkuInmnaEmbmJzcDvlnKjlr7nlrabnlJ/lgZrlh7rlpITliIblhrPlrprkuYvliY3vvIzlupTlvZPkuabpnaLlkYrnn6Xmi5/lpITliIblrabnlJ/osIPmn6XmiYDorqTlrprnmoTlhbbov53nuqrkuovlrp7jgIHmi5/nu5nlpITliIbjgIHlpITliIbkvp3mja7vvIzlkYrnn6Xmi5/lpITliIblrabnlJ/lhbblupTkuqvmnInnmoTmnYPliKnvvIzlkKzlj5blrabnlJ/vvIjmiJbogIXlhbbku6PnkIbkurrvvInnmoTpmYjov7DlkoznlLPovqnvvIzlubborqTnnJ/lgZrlpb3orrDlvZXjgILmi5/lpITliIblrabnlJ/miJbogIXlhbbku6PnkIbkurrlupTlvZPlnKjorrDlvZXkuIrnrb7lrZfvvJvmi5Lnu53nrb7lrZfnmoTvvIznlLHorrDlvZXkurrlgZrlh7rmloflrZfor7TmmI7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzlha3ljYHlm5vmnaEmbmJzcDvlrabmoKHmi5/lr7nlrabnlJ/lpITku6XlvIDpmaTlrabnsY3lpITliIbml7bvvIzlrabnlJ/lj6/ku6XlnKjmjqXliLDmi5/lpITliIbpgJrnn6XkuabkuYvml6Xotbc15Liq5bel5L2c5pel5YaF77yM5ZCR5a2m5qCh5o+Q5Ye65Lmm6Z2i55Sz6K+36KaB5rGC5ZCs6K+B77yb6LaF6L+H5pyf6ZmQ5pyq5o+Q5Ye65ZCs6K+B6KaB5rGC55qE77yM5oiW6ICF5peg5q2j5b2T55CG55Sx5pyq5oyJ5pe25Y+C5Yqg5ZCs6K+B55qE77yM6KeG5Li65pS+5byD5ZCs6K+B5p2D5Yip44CC5pS+5byD5ZCs6K+B5p2D5Yip55qE77yM5LiN5b6X5YaN5qyh5o+Q5Ye65ZCs6K+B6KaB5rGC44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5YWt5Y2B5LqU5p2hJm5ic3A76K2m5ZGK5ZKM5Lil6YeN6K2m5ZGK5aSE5YiG55Sx5a2m55Sf5aSE44CB56CU56m255Sf5bel5L2c6YOo5ZKM56CU56m255Sf6Zmi5Yaz5a6a44CC6K6w6L+H5ZKM55WZ5qCh5a+f55yL5aSE5YiG55Sx5a2m55Sf5aSE44CB56CU56m255Sf5bel5L2c6YOo5ZKM56CU56m255Sf6Zmi5o+Q5Ye65aSE55CG5oSP6KeB77yM5oql5Li7566h5qCh6aKG5a+85om55YeG44CC5byA6Zmk5a2m57GN5aSE5YiG55Sx5a2m55Sf5aSE44CB56CU56m255Sf5bel5L2c6YOo5ZKM56CU56m255Sf6Zmi5o+Q5Ye65aSE55CG5oSP6KeB77yM5qCh6ZW/5Yqe5YWs5Lya5Yaz5a6a44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5YWt5Y2B5YWt5p2hJm5ic3A75a2m5qCh5a+55Y+X5aSE5YiG5a2m55Sf5Ye65YW35aSE5YiG5Yaz5a6a5Lmm44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ5aSE5YiG5Yaz5a6a5Lmm55Sx5a2m55Sf5aSE44CB56CU56m255Sf6Zmi5YiG5Yir6LW36I2J77yM57yW5Y+377yM5Yqg55uW5a2m5qCh5YWs56ug5ZCO5LiL5Y+R77yM5bm25a2Y5YWl5paH5Lmm5qGj5qGI5ZKM5Y+X5aSE5YiG5a2m55Sf5Liq5Lq65qGj5qGI44CC5byA6Zmk5a2m57GN5aSE5YiG5ZCM5pe25oql5YyX5Lqs5biC5pWZ5aeU5aSH5qGI44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ5aSE5YiG5Yaz5a6a5Lmm5bqU5b2T5YyF5ous5aSE5YiG5ZKM5aSE5YiG5LqL5a6e44CB55CG55Sx5Y+K5L6d5o2u77yM5bm25ZGK55+l5a2m55Sf5Y+v5Lul5o+Q5Ye655Sz6K+J5Y+K55Sz6K+J55qE5pyf6ZmQ44CCDQo8L3A+DQo8cCBzdHlsZT0idGV4dC1pbmRlbnQ6MmVtOyI+DQoJ56ys5YWt5Y2B5LiD5p2hJm5ic3A75aSE5YiG5Yaz5a6a5Lmm5bqU5b2T5Zyo5aSE5YiG5Yaz5a6a5YGa5Ye65ZCOMTDkuKrlt6XkvZzml6XlhoXjgIHnlLHlrabnlJ/miYDlnKjlrabpmaLvvIjns7vjgIHmiYDvvInpgIHovr7lj5flpITliIblrabnlJ/mnKzkurrvvIzlubbnlLHlhbblnKjlm57miafkuIrnrb7lrZfjgILlpoLlrabnlJ/mnKzkurrmi5Lnu53nrb7lrZfvvIzliJnnlLHpgIHovr7kurrlnKjlm57miafkuIror7TmmI7mi5Lnu53nrb7lrZfnmoTmg4XlhrXvvIzlubbnlLHlnKjlnLrnmoTkuKTlkI3op4Hor4Hkurrnrb7lrZfor4HmmI7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnoi6Xlj5flpITliIblrabnlJ/mnKrlnKjlrabmoKHvvIznlLHlrabpmaLvvIjns7vjgIHmiYDvvInku6XmjILlj7fkv6HlvaLlvI/lsIblpITliIblhrPlrprkuabmjInov53nuqrlrabnlJ/mj5DkvpvnmoTlnLDlnYDpgq7lr4Tnu5nlhbbmnKzkurrjgILoi6Xkv6Hku7bpgIDlm57vvIzliJnlnKjlm57miafkuIrlgZrlpb3orrDlvZXvvIzlubbnlLHkuKTlkI3op4Hor4Hkurrnrb7lrZfor4HmmI7jgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnoi6Xlj5flpITliIblrabnlJ/kuIvokL3kuI3mmI7vvIzlj6/ku6XnlZnnva7pgIHovr7miJbogIXlhazlkYrpgIHovr7jgILlhazlkYrpgIHovr7lupTlvZPlnKjlrabmoKHmjIflrprnmoTlhazlkYrmoI/kuIrlvKDotLTlhazlkYrvvIzmiJbogIXlnKjlrabmoKHmjIflrprnmoTnvZHnq5nkuIrlj5HluIPlhazlkYrjgILoh6rlhazlkYrlj5HluIPkuYvml6XotbfvvIznu4/ov4c2MOaXpe+8jOWNs+inhuS4uumAgei+vuOAguWtpuagoeW3peS9nOS6uuWRmOW6lOW9k+WmguWunuiusOW9leWFrOWRiumAgei+vueahOi/h+eoi++8jOW5tueUseS4pOWQjeingeivgeS6uuetvuWtl+ivgeaYjuOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOWFreWNgeWFq+adoSZuYnNwO+WtpuagoeWvueWtpueUn+eahOWkhOWIhuiHquWkhOWIhuWGs+WumuWBmuWHuuS5i+aXpei1t+eUn+aViO+8m+WkhOWIhuWQjue7reW3peS9nOS4reS4juWPl+WkhOWIhuWtpueUn+adg+ebiuebtOaOpeebuOWFs+eahO+8jOW6lOW9k+iHquWGs+WumuS5pumAgei+vuS5i+aXpei1t+aJp+ihjOOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOWFreWNgeS5neadoSZuYnNwO+WPl+WIsOW8gOmZpOWtpuexjeWkhOWIhueahOWtpueUn++8jOWtpuagoeWPkee7meWtpuS5oOivgeaYju+8jOW5tuWwhuWtpueUn+aho+ahiOOAgeaIt+WPo+mAgOWbnuWFtuWutuW6reaIt+WPo+aJgOWcqOWcsOOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS4g+WNgeadoSZuYnNwO+WPl+WIsOW8gOmZpOWtpuexjeWkhOWIhueahOWtpueUn+aUtuWIsOWkhOWIhuWGs+WumuS5puWQju+8jOW6lOW9k+WcqOWkhOWIhuWGs+WumuS5puinhOWumueahOacn+mZkOWGhe+8iOS4gOiIrOS4jei2hei/h+S4pOWRqO+8ieWKnueQhuemu+agoeaJi+e7reemu+agoeOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS4g+WNgeS4gOadoSZuYnNwO+WtpuagoeaIkOeri+WtpueUn+eUs+ivieWkhOeQhuWnlOWRmOS8mu+8jOi0n+i0o+WtpueUn+eUs+ivieS6i+WunOOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS4g+WNgeS6jOadoSZuYnNwO+WtpueUn+WvueWkhOWIhuWGs+WumuacieW8guiurueahO+8jOWcqOaOpeWIsOWtpuagoeWkhOWIhuWGs+WumuS5puS5i+aXpei1tzXkuKrlt6XkvZzml6XlhoXvvIzlj6/ku6XmjInnhafjgIrljJfkuqzluIjojIPlpKflrablrabnlJ/nlLPor4nnrqHnkIblip7ms5XjgIvnmoTop4TlrprlkJHlrabmoKHlrabnlJ/nlLPor4nlpITnkIblp5TlkZjkvJrmj5Dlh7rkuabpnaLnlLPor4njgILpgL7mnJ/mnKrmj5Dlh7rkuabpnaLnlLPor4nnmoTvvIzop4bkuLroh6rliqjmlL7lvIPjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgnnrKzkuIPljYHkuInmnaEmbmJzcDvlrabnlJ/ov53nuqrlpITliIbnmoTmnInlhbPmnZDmlpnvvIzljIXmi6zljp/lp4vmnZDmlpnjgIHlpITliIblhrPlrprkuabjgIHpgIHovr7lm57miafnrYnvvIznu5/kuIDnlLHlrabnlJ/lpITjgIHnoJTnqbbnlJ/pmaLmlbTnkIbkv53lrZjlnKjmlofkuabmoaPmoYjkuK3jgILlpITliIblhrPlrprkuabnrKzkuozogZTlvZLlhaXlrabnlJ/mnKzkurrmoaPmoYjjgIINCjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgkmbmJzcDsNCjwvcD4NCjxwIGFsaWduPSJjZW50ZXIiIHN0eWxlPSJ0ZXh0LWluZGVudDoyZW07Ij4NCgk8c3Ryb25nPuesrOS6lOeroCZuYnNwOzwvc3Ryb25nPjxzdHJvbmc+6ZmEJm5ic3A75YiZPC9zdHJvbmc+IA0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS4g+WNgeWbm+adoSZuYnNwO+acrOWKnuazleS4reaJgOi/sOeahOS7peS4iuOAgeS7peS4i++8jOWdh+S4uuWMheWQq+aJgOi/sOeahOaVsOWtl+aIluiAheWkhOWIhueahOe6p+WIq+OAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS4g+WNgeS6lOadoSZuYnNwO+acrOWKnuazleiHquS6jOOAh+S4gOS6jOW5tOS5neaciOS4gOaXpei1t+aWveihjOOAguaIkeagoeWOn+OAiuWMl+S6rOW4iOiMg+Wkp+WtpuWtpueUn+i/nee6quWkhOWIhuWKnuazleOAi+WQjOaXtuW6n+atouOAgg0KPC9wPg0KPHAgc3R5bGU9InRleHQtaW5kZW50OjJlbTsiPg0KCeesrOS4g+WNgeWFreadoSZuYnNwO+acrOWKnuazleeUseWtpueUn+WkhOOAgeeglOeptueUn+W3peS9nOmDqOWSjOeglOeptueUn+mZoui0n+i0o+ino+mHiuOAgiZuYnNwOw0KPC9wPmRkAhIPFgIfAAIBFgJmD2QWAmYPFQMENDgzOAhpbmRleG1wYSfljJfkuqzluIjojIPlpKflrabnoJTnqbbnlJ/or7flgYfop4TlrppkAhQPFgIfAAIBFgJmD2QWAmYPFQMENDg0NQhpbmRleG1wYS1NUEHns7vliJfmtLvliqjkuYvotqPlkbPov5DliqjkvJrmiJDlip/kuL7lip5kGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYBBQxJbWFnZUJ1dHRvbjGhgiWUd30D4I6i9vSRRozBvr5+BA==" />
</div>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="1951E080" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEWAwKw/JHBAQLs0bLrBgLSwpnTCOXG3fyl+B9MKQh+U6+vhDAm+cxp" />
</div>
        <header>
            <!--top end-->
            <div class="logo-bg" style="padding: 0">
                <div class=" container" style="width: 980px; background-color: #fff">
                    <div class="row clearfix" style="margin: 1% 0">
                        <div class="col-md-4 column logo-box ">
                            <a href="index.aspx">
                                <img src="images/logo.png" title="logo" class="img-responsive" alt="Cinque Terre" /></a>
                        </div>
                        <div class="col-md-5 column"></div>
                        <div class="col-md-3 column pn">
                            <div class="top-tell">
                                <p>
                                    <a href="http://www.sg.bnu.edu.cn:8082/eng/eindex.jsp" target="_blank">English Version</a>
                                </p>
                            </div>
                            <!--中文版 英文版-->
                            <div class="top-search">

                                <div class="input-group">
                                      <input name="TextBox1" type="text" id="TextBox1" class="form-control input1" />
                                    <span class="input-group-addon">

                                        <input type="image" name="ImageButton1" id="ImageButton1" src="images/sousou.png" style="border-width:0px;" />
                                    </span>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row clearfix" style="background-color: #0035B4">
                        <nav class="navbar topnav" role="navigation" style="min-height: 0; padding: 10px 0">
                            <div class="container-fluid top-nav">
                                <div class="collapse navbar-collapse top-nav" id="example-navbar-collapse">
                                    <ul class=" navbar-nav cex-list">
                                      <li class=""><a href="index.aspx">首页</a></li>
                                            
                                                    <li class="dropdown">
                                                        <a href="about.aspx?cdss=19&cdbh=19" class="dropdown-toggle">学院介绍 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="about.aspx?cdss=19&cdbh=20">学院概述</a></li>
                                                                
                                                                    <li><a href="history.aspx?cdss=19&cdbh=21">历史沿革</a></li>
                                                                
                                                                    <li><a href="structure.aspx?cdss=19&cdbh=22">组织机构</a></li>
                                                                
                                                                    <li><a href="Subject.aspx?cdss=19&cdbh=23">学科设置</a></li>
                                                                
                                                                    <li><a href="Department.aspx?cdss=19&cdbh=24">系所介绍</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="personnel.aspx?cdss=25&cdbh=25" class="dropdown-toggle">人才培养 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="undergraduate.aspx?cdss=25&cdbh=26">本科生</a></li>
                                                                
                                                                    <li><a href="Master.aspx?cdss=25&cdbh=27">硕士生</a></li>
                                                                
                                                                    <li><a href="Masterb.aspx?cdss=25&cdbh=28">博士生</a></li>
                                                                
                                                                    <li><a href="Masterbh.aspx?cdss=25&cdbh=29">博士后</a></li>
                                                                
                                                                    <li><a href="index-mpa.aspx?cdss=25&cdbh=30">MPA</a></li>
                                                                
                                                                    <li><a href="practice.aspx?cdss=25&cdbh=31">实习基地</a></li>
                                                                
                                                                    <li><a href="laboratory.aspx?cdss=25&cdbh=32">实验室</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="r-about.aspx?cdss=33&cdbh=33" class="dropdown-toggle">招生就业 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="r-about.aspx?cdss=33&cdbh=34">学院简介</a></li>
                                                                
                                                                    <li><a href="professional.aspx?cdss=33&cdbh=35">专业介绍</a></li>
                                                                
                                                                    <li><a href="register.aspx?cdss=33&cdbh=36">报考指南</a></li>
                                                                
                                                                    <li><a href="employment.aspx?cdss=33&cdbh=37">就业指导</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="teacherstaff.aspx?cdss=38&cdbh=38" class="dropdown-toggle">师资队伍 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="Tadministrative.aspx?cdss=38&cdbh=39">行政管理</a></li>
                                                                
                                                                    <li><a href="Thuman.aspx?cdss=38&cdbh=40">人力资源</a></li>
                                                                
                                                                    <li><a href="Tinformation.aspx?cdss=38&cdbh=41">信息管理</a></li>
                                                                
                                                                    <li><a href="Tmanagement.aspx?cdss=38&cdbh=42">管理科学与工程</a></li>
                                                                
                                                                    <li><a href="Tland.aspx?cdss=38&cdbh=43">土地资源管理</a></li>
                                                                
                                                                    <li><a href="Tpolitical.aspx?cdss=38&cdbh=44">政治学</a></li>
                                                                
                                                                    <li><a href="Tinternational.aspx?cdss=38&cdbh=45">国际关系</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="research.aspx?cdss=46&cdbh=46" class="dropdown-toggle">学术科研 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="project.aspx?cdss=46&cdbh=47">科研项目</a></li>
                                                                
                                                                    <li><a href="academic.aspx?cdss=46&cdbh=48">学术论文</a></li>
                                                                
                                                                    <li><a href="monograph.aspx?cdss=46&cdbh=49">专著教材</a></li>
                                                                
                                                                    <li><a href="research-report.aspx?cdss=46&cdbh=50">研究报告</a></li>
                                                                
                                                                    <li><a href="system.aspx?cdss=46&cdbh=51">科研制度</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="Students-work.aspx?cdss=52&cdbh=52" class="dropdown-toggle">学生工作 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="announcement.aspx?cdss=52&cdbh=53">通知公告</a></li>
                                                                
                                                                    <li><a href="organization.aspx?cdss=52&cdbh=54">社团风采</a></li>
                                                                
                                                                    <li><a href="Party-Building.aspx?cdss=52&cdbh=55">党旗飘飘</a></li>
                                                                
                                                                    <li><a href="studentactivity.aspx?cdss=52&cdbh=56">班级建设</a></li>
                                                                
                                                                    <li><a href="Youth-activity.aspx?cdss=52&cdbh=57">团委工作</a></li>
                                                                
                                                                    <li><a href="student-act.aspx?cdss=52&cdbh=58">学生活动</a></li>
                                                                
                                                                    <li><a href="xiazai.aspx?cdss=52&cdbh=59">常用下载</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="services.aspx?cdss=60&cdbh=60" class="dropdown-toggle">社会服务 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="continuing.aspx?cdss=60&cdbh=61">继续教育</a></li>
                                                                
                                                                    <li><a href="training.aspx?cdss=60&cdbh=62">社会培训</a></li>
                                                                
                                                                    <li><a href="exchange.aspx?cdss=60&cdbh=63">对外交流</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="alumni.aspx?cdss=64&cdbh=64" class="dropdown-toggle">院友之窗 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="alumni.aspx?cdss=64&cdbh=65">院友活动</a></li>
                                                                
                                                                    <li><a href="alumnistyle.aspx?cdss=64&cdbh=66">院友风采</a></li>
                                                                
                                                                    <li><a href="alumniservice.aspx?cdss=64&cdbh=67">院友服务</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                        <!--8-->
                                    </ul>
                                </div>
                            </div>
                        </nav>
                        <!--顶部导航-->
                    </div>
                </div>


            </div>
            <!--logo-bg-->

        </header>
        <section>
            <div class="container" style="width: 980px; margin: 0% auto; background-color: #fff; border-radius: 3px">
                <div style="width: 97%; margin: 1% auto; text-align: right">当前位置：<a href="index.aspx">首页</a>-><span id="Label5">MPA</span>->正文</div>

                <div id="right_center" class="right_center3 anli_lineheight" style="background: #fff; width: 97%; margin: 2% auto; border-radius: 5px; border: 1px solid #DCE6F0;">
                       <div class="program_dl" style="width: 90%; margin: 0 auto">
                        <div class="kec_s ">   
                            <h3 class="program_title" style="font-weight:bold;">
                                <span style="text-align: center; display: block; border-bottom: 1px solid #DCE6F0; color: #2C4A7E; padding-bottom: 1%">
                                    <span id="Label1">北京师范大学学生违纪处分办法</span></span>
                            </h3>
                            <h5 class="program_title" style="color: #999; padding-bottom: 2%;">
                                <span style="text-align: center; display: block;">
                                    <span id="Label2">2017-04-07</span>
                                    点击率：<span id="Label4">298</span>
                                </span>
                            </h5>
                            <span id="Label3"><p align="center" style="text-indent:2em;">
	2005年9月4日校长办公会讨论通过，2012年6月13日修订）
</p>
<p align="center" style="text-indent:2em;">
	&nbsp;
</p>
<p align="center" style="text-indent:2em;">
	<strong>第一章&nbsp;总 则</strong> 
</p>
<p style="text-indent:2em;">
	第一条&nbsp;为维护学校的教育教学秩序和生活秩序，维护学校和学生的合法权益，保障公共安全，根据《中华人民共和国教育法》、《中华人民共和国高等教育法》、《普通高等学校学生管理规定》（教育部[2005]第21号令）、《高等学校学生行为准则》(教育部教学[2005]5号)、《国家教育考试违规处理办法》（教育部[2012]第33号令），制定本办法。
</p>
<p style="text-indent:2em;">
	第二条&nbsp;本办法适用于具有北京师范大学学籍的学生、已经入学报到尚处在学籍审查期中的新生。非学历教育的学生参照执行。
</p>
<p style="text-indent:2em;">
	第三条&nbsp;本办法中的违纪行为，是指违反法律、法规、规章或者学校各项管理制度的行为。
</p>
<p style="text-indent:2em;">
	第四条&nbsp;学校对违纪学生坚持批评教育与惩戒相结合的原则。对违纪学生的处理要合法、公开、公平、公正，做到程序正当、证据充分、依据明确、定性准确、处分适当。
</p>
<p style="text-indent:2em;">
	第五条&nbsp;学生对违纪处分有按程序进行陈述、申辩、申诉的权利。
</p>
<p style="text-indent:2em;">
	&nbsp;
</p>
<p align="center" style="text-indent:2em;">
	<strong>第二章&nbsp;违纪处分的种类与适用</strong> 
</p>
<p style="text-indent:2em;">
	第六条&nbsp;违纪处分包括以下五种：
</p>
<p style="text-indent:2em;">
	（一）警告；（二）严重警告；（三）记过；（四）留校察看；（五）开除学籍。
</p>
<p style="text-indent:2em;">
	第七条&nbsp;留校察看处分的察看期从做出处分决定之日起计算，期限为一年。
</p>
<p style="text-indent:2em;">
	留校察看期满须由学生本人提交申请，院（系、所）提出意见，学生处、研究生工作部或者研究生院决定按时或延期解除察看。留校察看期间又发生违纪行为的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	留校察看期间进步明显并有突出表现的，可申请提前解除察看。留察期原则上不得少于半年。
</p>
<p style="text-indent:2em;">
	解除留校察看不是撤销处分。
</p>
<p style="text-indent:2em;">
	第八条&nbsp;违纪情节特别轻微，经批评教育改正的，可以免予纪律处分。
</p>
<p style="text-indent:2em;">
	第九条&nbsp;违纪后主动承认错误的，主动消除影响或者减轻违纪行为后果的，或者主动配合违纪调查且对调查取证有贡献的，可以从轻或者减轻处分。
</p>
<p style="text-indent:2em;">
	第十条&nbsp;&nbsp;受胁迫或者受诱骗违纪的，或者因过失违纪的，可以从轻、减轻或者免予处分。
</p>
<p style="text-indent:2em;">
	第十一条&nbsp;受处分的学生，经教育后，对自己所犯错误有深刻认识，并有真诚改正错误的行动，且表现突出的，可酌情减轻处分。
</p>
<p style="text-indent:2em;">
	第十二条&nbsp;有以下情形之一的，应当从重处分：
</p>
<p style="text-indent:2em;">
	（一）违纪行为影响恶劣或者严重破坏学校声誉的；
</p>
<p style="text-indent:2em;">
	（二）违纪后恶意串通，故意提供虚假证据，妨碍调查取证的；
</p>
<p style="text-indent:2em;">
	（三）对检举人、证人或者其他有关人员进行威胁、侮辱、诽谤、诬陷或者打击报复的；
</p>
<p style="text-indent:2em;">
	（四）教唆、胁迫、诱骗、指使他人违纪的；
</p>
<p style="text-indent:2em;">
	（五）策划或者组织群体违纪的；
</p>
<p style="text-indent:2em;">
	（六）参加涉外活动违纪的；
</p>
<p style="text-indent:2em;">
	（七）在校期间曾受过处分的。
</p>
<p style="text-indent:2em;">
	第十三条&nbsp;违纪学生应赔偿违纪行为造成的经济损失。
</p>
<p style="text-indent:2em;">
	&nbsp;
</p>
<p align="center" style="text-indent:2em;">
	<strong>第三章&nbsp;违纪行为与</strong><strong>处分</strong> 
</p>
<p style="text-indent:2em;">
	第十四条&nbsp;有以下情形之一的，给予开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）违反宪法，反对四项基本原则，破坏安定团结，扰乱社会秩序的；
</p>
<p style="text-indent:2em;">
	（二）故意危害国家安全，泄露国家机密，颠覆国家政权，破坏国家统一的；
</p>
<p style="text-indent:2em;">
	（三）触犯国家法律，构成刑事犯罪的。
</p>
<p style="text-indent:2em;">
	第十五条&nbsp;违反国家有关法律、法规，受到治安管理处罚的，给予以下处分：
</p>
<p style="text-indent:2em;">
	（一）被处以警告处罚的，给予警告处分；
</p>
<p style="text-indent:2em;">
	（二）被处以罚款处罚的，视其情节给予警告或者严重警告处分；
</p>
<p style="text-indent:2em;">
	（三）被处以拘留五天以下处罚的，给予记过处分；
</p>
<p style="text-indent:2em;">
	（四）被处以拘留六天以上十天以下处罚的，给予留校察看处分；
</p>
<p style="text-indent:2em;">
	（五）被处以拘留十一天以上处罚或者劳动教养的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第十六条&nbsp;将枪支、弹药、管制刀具或者易燃、易爆、有毒、放射性、腐蚀性物质或者传染病病原体等危险品擅自带入学校或者带出实验室、仓库等规定保管场所，造成严重公共安全隐患的，给予记过处分；情节严重的，给予留校察看处分；造成人身财产损失的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第十七条&nbsp;有下列行为之一的，给予记过处分；情节严重的，给予留校察看处分；由此造成严重后果的，给予开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）移动或者破坏消防设施或者各种安全、指示标志的；
</p>
<p style="text-indent:2em;">
	（二）堵塞消防通道、无火情况下触发报警装置、谎报火情的；
</p>
<p style="text-indent:2em;">
	（三）阻碍消防车辆、人员通行的；
</p>
<p style="text-indent:2em;">
	（四）扰乱火灾现场秩序的；
</p>
<p style="text-indent:2em;">
	（五）在重点防火单位或者场所擅自使用明火的。
</p>
<p style="text-indent:2em;">
	第十八条&nbsp;在宿舍、教室、图书馆等场所吸烟、私拉电线或者违章使用电器不听劝阻的，给予警告或者严重警告处分；因此导致火灾险情的，给予记过或者留校察看处分；造成严重后果的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第十九条&nbsp;所在地区或者学校发生火灾、地震、疫情等紧急情况时，不服从政府或者学校依法发布的命令、决定、规定，且不听劝阻的，给予记过处分；情节严重的，给予留校察看处分；严重扰乱紧急状态下公共秩序的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十条&nbsp;有下列扰乱文化、体育、学术报告等大型活动或者食堂、会场等公共场所秩序、危害公共安全行为之一的，给予严重警告处分；情节严重的，给予记过处分；由此造成人身财产损失的，给予记过至开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）强行进入场内，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（二）违反规定，在场内燃放烟花爆竹或者其他物品的；
</p>
<p style="text-indent:2em;">
	（三）展示侮辱性标语、条幅等物品的；
</p>
<p style="text-indent:2em;">
	（四）故意以拥挤、起哄、散布谣言等方式造成公共场所秩序混乱的；
</p>
<p style="text-indent:2em;">
	（五）向场内投掷杂物，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（六）其他在大型集体活动中或者公共场所采取可能危害公共安全行为的。
</p>
<p style="text-indent:2em;">
	第二十一条&nbsp;煽动民族仇恨、民族歧视，或者在出版物、计算机信息网络中刊载有民族歧视、侮辱内容的，给予留校察看处分；情节严重的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十二条&nbsp;煽动、策划非法集会、游行、示威，不听劝阻的，给予留校察看处分；情节严重的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十三条&nbsp;组织、教唆、胁迫、诱骗、煽动他人从事邪教、会道门活动或者参与、利用邪教、会道门、迷信活动，扰乱社会秩序、损害他人身体健康的，给予留校察看处分；情节严重的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十四条&nbsp;在校内进行宗教活动，不听劝阻的，给予严重警告或者记过处分；造成严重不良影响的，给予留校察看或者开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十五条&nbsp;参加或者成立非法组织、刊印非法刊物的，或者利用某种活动或者组织发展、控制成员，危害学校及社会正常秩序的，给予留校察看处分；情节严重的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十六条&nbsp;在校内私设广播站、电台的，给予留校察看处分；情节严重的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十七条&nbsp;故意散布谣言，破坏社会和校园稳定的，给予严重警告处分；煽动或者组织聚众闹事的，给予记过处分。其中具有暴力、侮辱诽谤、迷信等严重情节的，或者由此严重扰乱社会秩序的，给予留校察看或者开除学籍处分。
</p>
<p style="text-indent:2em;">
	第二十八条&nbsp;有下列行为之一的，对当事人或者学生团体负责人给予警告处分；情节严重的，给予严重警告处分；造成不良后果的，给予记过或者留校察看处分：
</p>
<p style="text-indent:2em;">
	（一）未注册成立学生团体，以学生团体名义从事各种活动的；
</p>
<p style="text-indent:2em;">
	（二）已注册成立的学生团体成员和负责人，严重违反社团管理规定的；
</p>
<p style="text-indent:2em;">
	（三）未经审批擅自组织募捐、收取活动经费、协会会费的。
</p>
<p style="text-indent:2em;">
	第二十九条&nbsp;有下列扰乱学校公共秩序行为之一的，给予以下处分：
</p>
<p style="text-indent:2em;">
	（一）未经批准，在教学楼、宿舍楼等公共场所喧哗或者举行娱乐活动，妨碍他人工作、学习和休息，且不听劝阻的，给予严重警告处分；情节严重的，给予记过至留校察看处分；
</p>
<p style="text-indent:2em;">
	（二）严重扰乱课堂、实验室等场所教学秩序或者食堂、宿舍等生活场所秩序不听劝阻的，给予严重警告处分；情节严重的，或者屡次扰乱上述场所的教学秩序、生活秩序，不听劝阻的，给予记过至开除学籍处分；
</p>
<p style="text-indent:2em;">
	（三）举（承）办大型活动，未按要求进行报批的，或者虽经批准，不按要求采取必要的安全管理措施的，给予举（承）办活动的负责人严重警告处分；由此造成不良后果的，根据情节轻重，给予其记过至开除学籍处分；
</p>
<p style="text-indent:2em;">
	（四）利用其他形式扰乱学校秩序的，给予严重警告处分；情节严重的，给予记过至开除学籍处分。
</p>
<p style="text-indent:2em;">
	第三十条&nbsp;有下列行为之一的，给予警告处分；情节较重的，给予严重警告处分：
</p>
<p style="text-indent:2em;">
	（一）在非指定地点张贴通知、路标、海报、启事、通告等各类宣传品，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（二）在课桌、厕所以及校内建筑物等公共场所刻划、涂画，或者损坏草坪、花卉树木，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（三）将宠物带入教室、办公室、实验室、宿舍等场所，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（四）在宿舍、教室、图书馆或者其他禁止吸烟的地方吸烟，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（五）在校内无照经营的，或者未在学校指定地点设摊转卖个人物品的；
</p>
<p style="text-indent:2em;">
	（六）擅自调换或者占用学生宿舍的；
</p>
<p style="text-indent:2em;">
	（七）擅自在宿舍中留宿校外人员的。
</p>
<p style="text-indent:2em;">
	第三十一条&nbsp;在学生宿舍内留宿异性或者在异性学生宿舍内留宿的，给予记过处分；情节严重的，给予留校察看处分；造成恶劣影响的，或者屡次违反的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第三十二条&nbsp;饮酒滋事，扰乱社会场所或者学校秩序的，给予严重警告处分；情节严重的，给予记过至留校察看处分。
</p>
<p style="text-indent:2em;">
	第三十三条&nbsp;有下列行为之一的，给予警告或者严重警告处分；情节较重的，给予记过或者留校察看处分；由此造成严重后果的，给予开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）写恐吓信或者以其他方法威胁他人人身安全的；
</p>
<p style="text-indent:2em;">
	（二）公然侮辱他人或者捏造事实诽谤他人的；
</p>
<p style="text-indent:2em;">
	（三）发送淫秽、侮辱、恐吓或者其他信息，干扰他人正常生活的；
</p>
<p style="text-indent:2em;">
	（四）偷窥、偷拍、窃听、散布或者以其他方式侵犯他人隐私的；
</p>
<p style="text-indent:2em;">
	（五）猥亵他人的，或者在公共场所故意裸露身体，情节恶劣的；
</p>
<p style="text-indent:2em;">
	（六）纠缠或者骚扰他人，影响他人正常生活、学习的；
</p>
<p style="text-indent:2em;">
	（七）有其他干扰他人正常生活行为的。
</p>
<p style="text-indent:2em;">
	第三十四条&nbsp;有下列行为之一的，给予以下处分：
</p>
<p style="text-indent:2em;">
	（一）故意伤害他人身体的，给予记过处分；造成轻微伤的，给予留校察看处分；造成轻伤的，给予开除学籍处分；
</p>
<p style="text-indent:2em;">
	（二）虽未动手打人，但寻衅滋事、挑起打架等事端的，给予严重警告处分；情节严重的，给予记过处分；
</p>
<p style="text-indent:2em;">
	（三）动手打人，视其情节，给予严重警告处分，直至开除学籍；
</p>
<p style="text-indent:2em;">
	（四）以“劝架”为名，偏袒一方，促使事态扩大的，给予记过处分；由此造成他人轻微伤害的，给予留校察看或者开除学籍处分；
</p>
<p style="text-indent:2em;">
	（五）持械打人或者为打人者提供凶器，未造成伤害的，给予留校察看处分；致他人轻微伤害的，给予开除学籍处分；
</p>
<p style="text-indent:2em;">
	（六）多次殴打、伤害他人或者一次殴打、伤害多人的，给予留校察看处分；情节严重的，给予开除学籍处分；
</p>
<p style="text-indent:2em;">
	（七）结伙斗殴，未直接造成他人伤害的，给予留校察看处分；直接造成他人人身伤害的，给予开除学籍处分；结伙斗殴为首或者先动手打人的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第三十五条&nbsp;隐匿、毁弃、非法占有、私自开拆或者以其他方式非法处理他人邮件的，给予警告或者严重警告处分；造成严重后果的，给予记过或者留校察看处分。
</p>
<p style="text-indent:2em;">
	第三十六条&nbsp;冒用他人名义从事违法违纪或者其他不正当行为，给他人造成名誉或者经济损失的，给予警告或者严重警告处分；造成严重后果的，给予记过以上处分。
</p>
<p style="text-indent:2em;">
	第三十七条&nbsp;卖淫、嫖娼的，引诱或者介绍他人卖淫的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第三十八条&nbsp;制作、运输、复制、出售、出租、发布或者播放淫秽书刊、图片、影片、音像制品等淫秽物品的，或者利用计算机信息网络、电话以及其他通讯工具传播淫秽信息的，给予留校察看处分；情节严重的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第三十九条&nbsp;参与赌博的，给予记过处分；参与赌博赌资较大的，以营利为目的为赌博提供条件的，聚众赌博的，或者勾结校外人员赌博的，给予留校察看或者开除学籍处分。
</p>
<p style="text-indent:2em;">
	第四十条&nbsp;吸食、注射或者参与非法制造、买卖、传播毒品或者其他禁用药品的，视情节轻重，给予留校察看或者开除学籍处分。
</p>
<p style="text-indent:2em;">
	第四十一条&nbsp;参加或者介绍他人参加非法传销等非法商业活动，不听劝阻的，给予严重警告处分；由此造成恶劣影响的，给予记过至开除学籍处分。
</p>
<p style="text-indent:2em;">
	第四十二条&nbsp;盗窃、诈骗、哄抢、敲诈勒索公私财物，在国家立案标准以下的，给予记过处分；在国家立案标准以上定罪标准以下的，给予留校察看处分；在国家定罪标准以上的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第四十三条&nbsp;有下列行为之一的，给予严重警告处分；情节较重的，给予记过处分；由此造成严重后果的，给予留校察看或者开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）弄虚作假，谎报家庭经济状况，骗领奖助学金、困难补助或者助学贷款的；
</p>
<p style="text-indent:2em;">
	（二）盗用他人（含单位）各种证卡账号和密码（含网络用户的账号和密码）的；
</p>
<p style="text-indent:2em;">
	（三）转借学生证、校园卡或者其他仅限校内个人使用的证卡账号和密码（含网络用户的账号和密码）并造成不良后果的；
</p>
<p style="text-indent:2em;">
	（四）偷窃公章、保密文件、档案等物品的；
</p>
<p style="text-indent:2em;">
	（五）私自涂改、伪造证件、公章的；
</p>
<p style="text-indent:2em;">
	（六）伪造、篡改或者冒用学校文件或者记录的；
</p>
<p style="text-indent:2em;">
	（七）谎报丢失及冒名补办证件的；
</p>
<p style="text-indent:2em;">
	（八）伪造或者非法倒卖学校各种证卡的。
</p>
<p style="text-indent:2em;">
	第四十四条&nbsp;有下列行为之一的，给予严重警告处分；情节较重的，给予记过处分；由此造成严重后果的，给予留校察看或者开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）故意损坏公共门窗、玻璃、照明设备、公共计算机及网络设施、音像播放设备等各种学校公共物品的；
</p>
<p style="text-indent:2em;">
	（二）偷窃或者故意撕毁、损坏图书馆、资料室的图书、报刊的，或者未经许可恶意下载图书电子资源的；
</p>
<p style="text-indent:2em;">
	（三）未经允许，侵入他人或者公共计算机网络系统，对计算机信息系统、应用程序、数据、信息存储或者网络等进行操作，造成损害的；
</p>
<p style="text-indent:2em;">
	（四）故意制作、传播计算机病毒等破坏性程序，影响计算机网络系统正常运行的；
</p>
<p style="text-indent:2em;">
	（五）为侵犯国家、集体或者他人财产者提供信息、工具的；
</p>
<p style="text-indent:2em;">
	（六）明知是赃物而购买的，帮助或者有掩盖、窝藏、销毁、转移赃物等行为的；
</p>
<p style="text-indent:2em;">
	（七）未尽管理责任，致使公物毁损、丢失或者管理公物有浮报、挪用、账目不清的；
</p>
<p style="text-indent:2em;">
	（八）其他侵犯公私财产权利的行为。
</p>
<p style="text-indent:2em;">
	第四十五条&nbsp;有下列行为之一的，给予以下处分：
</p>
<p style="text-indent:2em;">
	（一）泄露学校科技成果、技术资料等秘密资料的，给予严重警告处分；情节严重的，给予记过以上处分；
</p>
<p style="text-indent:2em;">
	（二）未经许可，私自转让、使用学校知识产权的，给予记过处分；情节严重的，给予留校察看处分；
</p>
<p style="text-indent:2em;">
	（三）未经允许，擅自将他人的或者自己只是作为成员之一的集体的科研成果、实验数据、研究报告等以自己个人名义公开发表的，给予警告或者严重警告处分；情节严重的，给予记过至开除学籍处分。
</p>
<p style="text-indent:2em;">
	第四十六条&nbsp;有下列行为之一的，给予警告或者严重警告处分；情节严重的，给予记过处分；从中谋取个人利益的，给予留校察看或者开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）未经批准擅自以学校名义对外发布公告、新闻，或者擅自代表学校做出承诺，或者擅自代表学校在社会上参加活动的；
</p>
<p style="text-indent:2em;">
	（二）在个人的商业活动中，公开在招牌、广告、海报、文件等有关宣传材料上使用学校的名称或者标识，造成不良影响的；
</p>
<p style="text-indent:2em;">
	（三）未经批准擅自以学校、院（系、所）等机构或者学生组织的名义在社会上活动，造成不良影响的。
</p>
<p style="text-indent:2em;">
	第四十七条&nbsp;妨碍学校教职员工按照规定实施管理，破坏学校管理秩序的，给予警告或者严重警告处分；情节严重的，给予记过或者留校察看处分。
</p>
<p style="text-indent:2em;">
	第四十八条&nbsp;旷课，一学期内第一次累计达到20学时的，给予警告处分；第二次累计旷课20学时的，给予记过处分；第三次累计旷课20学时的，给予留校察看处分。留校察看期间旷课累计达到20学时的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	按周计算的实践环节在累计学时时，每天按6学时计算。
</p>
<p style="text-indent:2em;">
	无课期间未经批准擅自离校的，按照旷课处理。旷课时数按每天5学时计算。
</p>
<p style="text-indent:2em;">
	第四十九条&nbsp;未经批准，连续离校天数4天以下的，给予警告处分；达到5至6天的，给予严重警告处分；达到7至8天的，给予记过处分；达到9至10天的，给予留校察看处分；达到11天以上的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	连续天数的计算中不计周六、周日、法定节假日和学校规定的假期。
</p>
<p style="text-indent:2em;">
	第五十条&nbsp;屡次迟到、早退等违反考勤纪律的，给予警告处分；情节严重的，给予记过处分。
</p>
<p style="text-indent:2em;">
	第五十一条&nbsp;有下列行为之一的，给予以下处分：
</p>
<p style="text-indent:2em;">
	（一）与学校约定承担助教、助管、助研或者其他教学科研活动，未经批准，擅自不参加或者终止参加，情节严重的，给予警告或者严重警告处分；由此给相关工作带来重大损失的，给予记过至开除学籍处分；
</p>
<p style="text-indent:2em;">
	（二）参加学校组织的社会实践等活动，未经批准，擅自不参加或者终止参加，情节严重的，给予警告或者严重警告处分；由此给相关活动造成重大损失的，视情节轻重，给予记过至开除学籍处分；
</p>
<p style="text-indent:2em;">
	（三）参加上述活动期间故意违反有关规定、影响活动正常开展，情节严重的，给予警告至记过处分。
</p>
<p style="text-indent:2em;">
	第五十二条&nbsp;考试中不遵守考试纪律，不服从考试工作人员的安排和要求，有下列违纪行为之一的，给予警告或者严重警告处分；屡次违反，不听劝阻的，或者情节严重的，给予记过以上处分：
</p>
<p style="text-indent:2em;">
	（一）未携带规定的准考证、学生证、身份证等身份证件强行进入考场参加考试，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（二）携带规定以外的物品进入考场或者未放在指定位置的；
</p>
<p style="text-indent:2em;">
	（三）未在规定的座位参加考试，不听劝阻的；
</p>
<p style="text-indent:2em;">
	（四）考试开始信号发出前答题或者结束信号发出后继续答题的；
</p>
<p style="text-indent:2em;">
	（五）在考试过程中旁窥、交头接耳、互打暗号或者手势的；
</p>
<p style="text-indent:2em;">
	（六）在考场或者学校禁止的范围内，喧哗、吸烟或者实施其他扰乱考场秩序的行为的；
</p>
<p style="text-indent:2em;">
	（七）未经考试工作人员同意在考试过程中擅自离开考场的；
</p>
<p style="text-indent:2em;">
	（八）未经允许，将试卷、答卷（含答题卡、答题纸等，下同）、草稿纸等考试用纸带出考场的；
</p>
<p style="text-indent:2em;">
	（九）用规定以外的笔或者纸答题或者在试卷规定以外的地方书写姓名、考号或者以其他方式在答卷上标记信息的；
</p>
<p style="text-indent:2em;">
	（十） 交卷后强行拿回试卷修改的；
</p>
<p style="text-indent:2em;">
	（十一）故意扰乱考点、考场、评卷场所等考试工作场所秩序，拒绝或者妨碍考试工作人员履行工作职责的。
</p>
<p style="text-indent:2em;">
	（十二）其他违反考场规则但尚未构成作弊的行为。
</p>
<p style="text-indent:2em;">
	第五十三条&nbsp;考试中违背考试公平、公正原则，有下列作弊行为之一的，给予留校察看处分；情节严重的，给予开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）在闭卷考试中，携带与考试内容相关的材料或者存储有与考试内容相关资料的电子设备参加考试的；
</p>
<p style="text-indent:2em;">
	（二）在闭卷考试中，使用相关设备搜索、浏览与考试内容相关的网络信息的；
</p>
<p style="text-indent:2em;">
	（三）在闭卷考试中，携带具有发送或者接收信息功能的设备的；
</p>
<p style="text-indent:2em;">
	（四）抄袭或者协助他人抄袭试题答案或者与考试内容相关的资料的；
</p>
<p style="text-indent:2em;">
	（五）抢夺、窃取他人试卷、答卷或者胁迫他人为自己抄袭提供方便的；
</p>
<p style="text-indent:2em;">
	（六）考试期间在考场外偷看或者与他人交流考试有关内容的；
</p>
<p style="text-indent:2em;">
	（七）故意销毁试卷、答卷或者考试材料的；
</p>
<p style="text-indent:2em;">
	（八）在答卷上填写与本人身份不符的姓名、学号等信息的；
</p>
<p style="text-indent:2em;">
	（九）传、接物品或者交换试卷、答卷、草稿纸的；
</p>
<p style="text-indent:2em;">
	（十）其他以不正当手段获得或者试图获得试题答案、考试成绩的行为。
</p>
<p style="text-indent:2em;">
	第五十四条&nbsp;考试中有下列作弊行为之一的，给予开除学籍处分：
</p>
<p style="text-indent:2em;">
	（一）&nbsp;&nbsp;考试过程中，向场外发送、传递试题信息的；
</p>
<p style="text-indent:2em;">
	（二）&nbsp;&nbsp;考试过程中，使用相关设备接收信息实施作弊的；
</p>
<p style="text-indent:2em;">
	（三）由他人代替参加考试的；
</p>
<p style="text-indent:2em;">
	（四）代替他人参加考试的；
</p>
<p style="text-indent:2em;">
	（五）组织团伙作弊的；
</p>
<p style="text-indent:2em;">
	（六）为作弊组织者提供试题信息、答案及相应设备等参与团伙作弊行为的；
</p>
<p style="text-indent:2em;">
	（七）偷盗试卷的；
</p>
<p style="text-indent:2em;">
	（八）第二次作弊的。
</p>
<p style="text-indent:2em;">
	第五十五条&nbsp;在各种体育竞赛中有服用违禁药物等欺骗行为的，给予记过处分；其中在校级以上比赛中发生的，给予留校察看处分。
</p>
<p style="text-indent:2em;">
	第五十六条&nbsp;由他人代替或者代替他人参加各种体育竞赛的，给予留校察看处分；在校级以上比赛中发生的，给予开除学籍处分。
</p>
<p style="text-indent:2em;">
	第五十七条&nbsp;有下列违反学术规范行为之一的，给予以下处分：
</p>
<p style="text-indent:2em;">
	（一）在课程作业、科学研究报告或者其他未正式发表的学术成果中，有剽窃、造假等违反学术规范行为的，视其情节轻重，给予严重警告至开除学籍处分；
</p>
<p style="text-indent:2em;">
	（二）在撰写毕业论文（设计）或者学位论文过程中有剽窃、造假等违反学术规范行为的，视情节轻重，给予记过至开除学籍处分；
</p>
<p style="text-indent:2em;">
	（三）在校学习期间发表的学术论文、专著，主编、参编书籍中有剽窃、造假等行为的，视其情节轻重，给予记过以上处分；在学术界和社会上产生恶劣影响的，给予留校察看至开除学籍处分。
</p>
<p style="text-indent:2em;">
	第五十八条&nbsp;涂改、伪造成绩单、签字、印章、推荐信或者其他有关学业、学术水平证明的，给予记过处分；情节严重的，给予留校察看处分。
</p>
<p style="text-indent:2em;">
	&nbsp;
</p>
<p align="center" style="text-indent:2em;">
	<strong>第四章&nbsp;处分</strong><strong>程序</strong> 
</p>
<p style="text-indent:2em;">
	第五十九条&nbsp;学生处负责处理本科生违纪行为；研究生工作部、研究生院负责处理研究生违纪行为。
</p>
<p style="text-indent:2em;">
	第六十条&nbsp;发现学生违纪事件后，由相关部门指定人员组成调查小组（成员不少于2人），采取合法的方式查清事实，收集证据，并作调查记录。
</p>
<p style="text-indent:2em;">
	与学生有利害关系或者直接涉及违纪事件的当事人应当回避。
</p>
<p style="text-indent:2em;">
	第六十一条&nbsp;学生违反学习纪律的行为，本科生由教务处负责调查、取证，并向学生处提出处理建议；研究生由研究生院调查、取证，并提出处理建议。
</p>
<p style="text-indent:2em;">
	学生违反宿舍管理规定的行为，由校宿舍管理中心负责调查、取证，并向学生处或者研究生工作部提出处理建议。
</p>
<p style="text-indent:2em;">
	学生违反社团管理规定的行为，由校团委负责调查、取证，并向学生处或研究生工作部提出处理建议。
</p>
<p style="text-indent:2em;">
	学生违反治安管理处罚法或者有其他违法犯罪行为的，由保卫处依据司法机关处理结果，并向学生处或研究生工作部提出处理建议。
</p>
<p style="text-indent:2em;">
	学生其他违纪行为由学院（系、所）会同相关部门调查、取证，并向学生处或者研究生工作部提出处理建议。
</p>
<p style="text-indent:2em;">
	第六十二条&nbsp;下列各项证据，经过查证核实后，可以作为处分违纪学生的依据：
</p>
<p style="text-indent:2em;">
	（一）书证；
</p>
<p style="text-indent:2em;">
	（二）物证；
</p>
<p style="text-indent:2em;">
	（三）证人证言；
</p>
<p style="text-indent:2em;">
	（四）当事人的陈述；
</p>
<p style="text-indent:2em;">
	（五）视听资料；
</p>
<p style="text-indent:2em;">
	（六）鉴定结论；
</p>
<p style="text-indent:2em;">
	（七）勘验笔录、现场笔录；
</p>
<p style="text-indent:2em;">
	（八）其他有关部门依法做出的鉴定性结论。
</p>
<p style="text-indent:2em;">
	第六十三条&nbsp;在对学生做出处分决定之前，应当书面告知拟处分学生调查所认定的其违纪事实、拟给处分、处分依据，告知拟处分学生其应享有的权利，听取学生（或者其代理人）的陈述和申辩，并认真做好记录。拟处分学生或者其代理人应当在记录上签字；拒绝签字的，由记录人做出文字说明。
</p>
<p style="text-indent:2em;">
	第六十四条&nbsp;学校拟对学生处以开除学籍处分时，学生可以在接到拟处分通知书之日起5个工作日内，向学校提出书面申请要求听证；超过期限未提出听证要求的，或者无正当理由未按时参加听证的，视为放弃听证权利。放弃听证权利的，不得再次提出听证要求。
</p>
<p style="text-indent:2em;">
	第六十五条&nbsp;警告和严重警告处分由学生处、研究生工作部和研究生院决定。记过和留校察看处分由学生处、研究生工作部和研究生院提出处理意见，报主管校领导批准。开除学籍处分由学生处、研究生工作部和研究生院提出处理意见，校长办公会决定。
</p>
<p style="text-indent:2em;">
	第六十六条&nbsp;学校对受处分学生出具处分决定书。
</p>
<p style="text-indent:2em;">
	处分决定书由学生处、研究生院分别起草，编号，加盖学校公章后下发，并存入文书档案和受处分学生个人档案。开除学籍处分同时报北京市教委备案。
</p>
<p style="text-indent:2em;">
	处分决定书应当包括处分和处分事实、理由及依据，并告知学生可以提出申诉及申诉的期限。
</p>
<p style="text-indent:2em;">
	第六十七条&nbsp;处分决定书应当在处分决定做出后10个工作日内、由学生所在学院（系、所）送达受处分学生本人，并由其在回执上签字。如学生本人拒绝签字，则由送达人在回执上说明拒绝签字的情况，并由在场的两名见证人签字证明。
</p>
<p style="text-indent:2em;">
	若受处分学生未在学校，由学院（系、所）以挂号信形式将处分决定书按违纪学生提供的地址邮寄给其本人。若信件退回，则在回执上做好记录，并由两名见证人签字证明。
</p>
<p style="text-indent:2em;">
	若受处分学生下落不明，可以留置送达或者公告送达。公告送达应当在学校指定的公告栏上张贴公告，或者在学校指定的网站上发布公告。自公告发布之日起，经过60日，即视为送达。学校工作人员应当如实记录公告送达的过程，并由两名见证人签字证明。
</p>
<p style="text-indent:2em;">
	第六十八条&nbsp;学校对学生的处分自处分决定做出之日起生效；处分后续工作中与受处分学生权益直接相关的，应当自决定书送达之日起执行。
</p>
<p style="text-indent:2em;">
	第六十九条&nbsp;受到开除学籍处分的学生，学校发给学习证明，并将学生档案、户口退回其家庭户口所在地。
</p>
<p style="text-indent:2em;">
	第七十条&nbsp;受到开除学籍处分的学生收到处分决定书后，应当在处分决定书规定的期限内（一般不超过两周）办理离校手续离校。
</p>
<p style="text-indent:2em;">
	第七十一条&nbsp;学校成立学生申诉处理委员会，负责学生申诉事宜。
</p>
<p style="text-indent:2em;">
	第七十二条&nbsp;学生对处分决定有异议的，在接到学校处分决定书之日起5个工作日内，可以按照《北京师范大学学生申诉管理办法》的规定向学校学生申诉处理委员会提出书面申诉。逾期未提出书面申诉的，视为自动放弃。
</p>
<p style="text-indent:2em;">
	第七十三条&nbsp;学生违纪处分的有关材料，包括原始材料、处分决定书、送达回执等，统一由学生处、研究生院整理保存在文书档案中。处分决定书第二联归入学生本人档案。
</p>
<p style="text-indent:2em;">
	&nbsp;
</p>
<p align="center" style="text-indent:2em;">
	<strong>第五章&nbsp;</strong><strong>附&nbsp;则</strong> 
</p>
<p style="text-indent:2em;">
	第七十四条&nbsp;本办法中所述的以上、以下，均为包含所述的数字或者处分的级别。
</p>
<p style="text-indent:2em;">
	第七十五条&nbsp;本办法自二〇一二年九月一日起施行。我校原《北京师范大学学生违纪处分办法》同时废止。
</p>
<p style="text-indent:2em;">
	第七十六条&nbsp;本办法由学生处、研究生工作部和研究生院负责解释。&nbsp;
</p></span>
                        </div>
                        <div style="border-top: 1px solid #DCE6F0; padding: 1% 0; width: 100%; overflow: hidden; margin-top: 5%">
                            
                                    <a href="newshow.aspx?newid=4838&wzlx=indexmpa" class="pres" style="float: left; width: 45%;">上一篇：北京师范大学研究生请假规定</a>
                                
                            

                                    <a href="newshow.aspx?newid=4845&wzlx=indexmpa" class="pres" style="float: right; width: 45%;">下一篇：MPA系列活动之趣味运动会成功举办</a>

                                
                        </div>


                        
                    </div>

                </div>
            </div>
        </section>
        <!--section中间部分-->
        <footer>
            <div class="container">
                <div class="row clearfix">
                    <div class="col-md-12 column">
                        <div class="row clearfix">
                            <div class="col-md-9 column">
                               <p>
                                    学院地址：北京市海淀区新街口外大街19号 北京师范大学前主楼A区5层 
                                </p>
                                <p>
                                    联系电话：010-58808256 &nbsp; MPA咨询电话：010-58808176
                                </p>
                                <p>
                                    Copyright@2016 北京师范大学政府管理学院版权所有 &nbsp;All Rights Reserved 
                                </p>
                                <p>
                                    设计与开发：<a href="http://www.ixingzhi.cn" target="_blank" style="color:white">行知睿思 </a> 
                                </p>
                            </div>
                         <div class="col-md-3 column ">
                                <dl class="caption">
                                    <dt>
                                        <img src="images/weixin.png" alt="Cinque Terre" class="img-responsive" />
                                    </dt>
                                    <dd>公众号
                                    </dd>
                                </dl>
                                <dl class="caption">
                                    <dt>
                                        <img src="images/er.png" alt="Cinque Terre" class="img-responsive" />
                                    </dt>
                                    <dd>手机版
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </footer>
    </form>
</body>
</html>
