

<!DOCTYPE html>
<html>
<head><meta http-equiv="pragma" content="no-cache" /><meta name="renderer" content="webkit|ie-comp|ie-stand" /><meta http-equiv="cache-control" content="no-cache" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="expires" content="0" /><meta http-equiv="keywords" content="北京师范大学政府管理学院,政府管理学院,北师大政府管理学院,北师大政府管理学院,www.heu.edu.cn" /><meta http-equiv="description" content="欢迎访问北京师范大学政府管理学院" /><meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" /><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" /><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta http-equiv="X-UA-Compatible" content="IE=9" /><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" /><title>
	北京师范大学政府管理学院
</title>
    <script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/slider.js"></script>
    <script type="text/javascript" src="js/dropdown.js"></script>
    <script src="js/jquery-accordion-menu.js" type="text/javascript"></script>
    <script src="js/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="css/bootstrap.min.css" /><link rel="stylesheet" href="css/css.css" /><link rel="stylesheet" href="css/style.css" /><link rel="stylesheet" href="fonts/iconfont.css" /><link href="css/jquery-accordion-menu.css" rel="stylesheet" type="text/css" />
    <script src="js/responsive-util2.js"></script>
    <script src="js/scrolltopcontrol.js"></script>
    <script src="js/caidan.js"></script>
    <!--让bootstrap兼容ie8 
[if lte IE 8]-->
    <script type="text/javascript" src="js/respond.min.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <!--  [endif]
 [if lt IE 9]-->

    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <!-- [endif]-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <script type="text/javascript">
        $(function () {
            $('#demo01').flexslider({
                animation: "slide",
                direction: "horizontal",
                easing: "swing",
            });
            $('#demo02').flexslider({
                animation: "slide",
                direction: "vertical",
                easing: "swing"
            });

            // 使用说明
            /*
                animation: "slide", //转换方式 fade淡入淡出 slide滚动
                direction:"horizontal", //滚动方向 horizontal左右 vertical上下
                slideshowSpeed: 3000, //停留时间
                directionNav: true, //是否显示左右控制按钮 true&false
                controlNav: true, //是否显示下方控制按钮 true&false
                mousewheel: false, //是否允许鼠标控制滚动 true&fals
            */

        });
        function _openSelectLink(selecto, linkname, addclicktimename) {
            if (linkname == undefined || linkname == "")
                linkname = "value";


            var index = selecto.selectedIndex;
            var option = selecto.options[index];

            var url = option.getAttribute("value");
            if (addclicktimename != undefined && addclicktimename != "") {
                try {
                    eval(option.getAttribute(addclicktimename))
                }
                catch (e) {
                }
            }

            window.open(url);

            if (selecto.selectedIndex != 0) {
                selecto.selectedIndex = 0;
            }
        }
    </script>




    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery("#jquery-accordion-menu").jqueryAccordionMenu();

        });

        $(function () {
            //顶部导航切换

        })
        //banner轮播

    </script>
    <style>
.cex-list>li>a{
	color:#fff;
	padding:10px 19.8px;
}
</style>

</head>
<body style="background-color: #eee">
    <form name="form1" method="post" action="newshow.aspx?newid=5977&amp;wzlx=announcement" id="form1">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTAyOTU0NDI0OA9kFgICAw9kFhICBQ8WAh4LXyFJdGVtQ291bnQCCBYQZg9kFgRmDxUCGmFib3V0LmFzcHg/Y2Rzcz0xOSZjZGJoPTE5DOWtpumZouS7i+e7jWQCAQ8WAh8AAgUWCmYPZBYCZg8VAhphYm91dC5hc3B4P2Nkc3M9MTkmY2RiaD0yMAzlrabpmaLmpoLov7BkAgEPZBYCZg8VAhxoaXN0b3J5LmFzcHg/Y2Rzcz0xOSZjZGJoPTIxDOWOhuWPsuayv+mdqWQCAg9kFgJmDxUCHnN0cnVjdHVyZS5hc3B4P2Nkc3M9MTkmY2RiaD0yMgznu4Tnu4fmnLrmnoRkAgMPZBYCZg8VAhxTdWJqZWN0LmFzcHg/Y2Rzcz0xOSZjZGJoPTIzDOWtpuenkeiuvue9rmQCBA9kFgJmDxUCH0RlcGFydG1lbnQuYXNweD9jZHNzPTE5JmNkYmg9MjQM57O75omA5LuL57uNZAIBD2QWBGYPFQIecGVyc29ubmVsLmFzcHg/Y2Rzcz0yNSZjZGJoPTI1DOS6uuaJjeWfueWFu2QCAQ8WAh8AAgcWDmYPZBYCZg8VAiJ1bmRlcmdyYWR1YXRlLmFzcHg/Y2Rzcz0yNSZjZGJoPTI2CeacrOenkeeUn2QCAQ9kFgJmDxUCG01hc3Rlci5hc3B4P2Nkc3M9MjUmY2RiaD0yNwnnoZXlo6vnlJ9kAgIPZBYCZg8VAhxNYXN0ZXJiLmFzcHg/Y2Rzcz0yNSZjZGJoPTI4CeWNmuWjq+eUn2QCAw9kFgJmDxUCHU1hc3RlcmJoLmFzcHg/Y2Rzcz0yNSZjZGJoPTI5CeWNmuWjq+WQjmQCBA9kFgJmDxUCHmluZGV4LW1wYS5hc3B4P2Nkc3M9MjUmY2RiaD0zMANNUEFkAgUPZBYCZg8VAh1wcmFjdGljZS5hc3B4P2Nkc3M9MjUmY2RiaD0zMQzlrp7kuaDln7rlnLBkAgYPZBYCZg8VAh9sYWJvcmF0b3J5LmFzcHg/Y2Rzcz0yNSZjZGJoPTMyCeWunumqjOWupGQCAg9kFgRmDxUCHHItYWJvdXQuYXNweD9jZHNzPTMzJmNkYmg9MzMM5oub55Sf5bCx5LiaZAIBDxYCHwACBBYIZg9kFgJmDxUCHHItYWJvdXQuYXNweD9jZHNzPTMzJmNkYmg9MzQM5a2m6Zmi566A5LuLZAIBD2QWAmYPFQIhcHJvZmVzc2lvbmFsLmFzcHg/Y2Rzcz0zMyZjZGJoPTM1DOS4k+S4muS7i+e7jWQCAg9kFgJmDxUCHXJlZ2lzdGVyLmFzcHg/Y2Rzcz0zMyZjZGJoPTM2DOaKpeiAg+aMh+WNl2QCAw9kFgJmDxUCH2VtcGxveW1lbnQuYXNweD9jZHNzPTMzJmNkYmg9MzcM5bCx5Lia5oyH5a+8ZAIDD2QWBGYPFQIhdGVhY2hlcnN0YWZmLmFzcHg/Y2Rzcz0zOCZjZGJoPTM4DOW4iOi1hOmYn+S8jWQCAQ8WAh8AAgcWDmYPZBYCZg8VAiRUYWRtaW5pc3RyYXRpdmUuYXNweD9jZHNzPTM4JmNkYmg9MzkM6KGM5pS/566h55CGZAIBD2QWAmYPFQIbVGh1bWFuLmFzcHg/Y2Rzcz0zOCZjZGJoPTQwDOS6uuWKm+i1hOa6kGQCAg9kFgJmDxUCIVRpbmZvcm1hdGlvbi5hc3B4P2Nkc3M9MzgmY2RiaD00MQzkv6Hmga/nrqHnkIZkAgMPZBYCZg8VAiBUbWFuYWdlbWVudC5hc3B4P2Nkc3M9MzgmY2RiaD00MhXnrqHnkIbnp5HlrabkuI7lt6XnqItkAgQPZBYCZg8VAhpUbGFuZC5hc3B4P2Nkc3M9MzgmY2RiaD00MxLlnJ/lnLDotYTmupDnrqHnkIZkAgUPZBYCZg8VAh9UcG9saXRpY2FsLmFzcHg/Y2Rzcz0zOCZjZGJoPTQ0CeaUv+ayu+WtpmQCBg9kFgJmDxUCI1RpbnRlcm5hdGlvbmFsLmFzcHg/Y2Rzcz0zOCZjZGJoPTQ1DOWbvemZheWFs+ezu2QCBA9kFgRmDxUCHXJlc2VhcmNoLmFzcHg/Y2Rzcz00NiZjZGJoPTQ2DOWtpuacr+enkeeglGQCAQ8WAh8AAgUWCmYPZBYCZg8VAhxwcm9qZWN0LmFzcHg/Y2Rzcz00NiZjZGJoPTQ3DOenkeeglOmhueebrmQCAQ9kFgJmDxUCHWFjYWRlbWljLmFzcHg/Y2Rzcz00NiZjZGJoPTQ4DOWtpuacr+iuuuaWh2QCAg9kFgJmDxUCHm1vbm9ncmFwaC5hc3B4P2Nkc3M9NDYmY2RiaD00OQzkuJPokZfmlZnmnZBkAgMPZBYCZg8VAiRyZXNlYXJjaC1yZXBvcnQuYXNweD9jZHNzPTQ2JmNkYmg9NTAM56CU56m25oql5ZGKZAIED2QWAmYPFQIbc3lzdGVtLmFzcHg/Y2Rzcz00NiZjZGJoPTUxDOenkeeglOWItuW6pmQCBQ9kFgRmDxUCIlN0dWRlbnRzLXdvcmsuYXNweD9jZHNzPTUyJmNkYmg9NTIM5a2m55Sf5bel5L2cZAIBDxYCHwACBxYOZg9kFgJmDxUCIWFubm91bmNlbWVudC5hc3B4P2Nkc3M9NTImY2RiaD01MwzpgJrnn6XlhazlkYpkAgEPZBYCZg8VAiFvcmdhbml6YXRpb24uYXNweD9jZHNzPTUyJmNkYmg9NTQM56S+5Zui6aOO6YeHZAICD2QWAmYPFQIjUGFydHktQnVpbGRpbmcuYXNweD9jZHNzPTUyJmNkYmg9NTUM5YWa5peX6aOY6aOYZAIDD2QWAmYPFQIkc3R1ZGVudGFjdGl2aXR5LmFzcHg/Y2Rzcz01MiZjZGJoPTU2DOePree6p+W7uuiuvmQCBA9kFgJmDxUCI1lvdXRoLWFjdGl2aXR5LmFzcHg/Y2Rzcz01MiZjZGJoPTU3DOWbouWnlOW3peS9nGQCBQ9kFgJmDxUCIHN0dWRlbnQtYWN0LmFzcHg/Y2Rzcz01MiZjZGJoPTU4DOWtpueUn+a0u+WKqGQCBg9kFgJmDxUCG3hpYXphaS5hc3B4P2Nkc3M9NTImY2RiaD01OQzluLjnlKjkuIvovb1kAgYPZBYEZg8VAh1zZXJ2aWNlcy5hc3B4P2Nkc3M9NjAmY2RiaD02MAznpL7kvJrmnI3liqFkAgEPFgIfAAIDFgZmD2QWAmYPFQIfY29udGludWluZy5hc3B4P2Nkc3M9NjAmY2RiaD02MQznu6fnu63mlZnogrJkAgEPZBYCZg8VAh10cmFpbmluZy5hc3B4P2Nkc3M9NjAmY2RiaD02MgznpL7kvJrln7norq1kAgIPZBYCZg8VAh1leGNoYW5nZS5hc3B4P2Nkc3M9NjAmY2RiaD02Mwzlr7nlpJbkuqTmtYFkAgcPZBYEZg8VAhthbHVtbmkuYXNweD9jZHNzPTY0JmNkYmg9NjQM6Zmi5Y+L5LmL56qXZAIBDxYCHwACAxYGZg9kFgJmDxUCG2FsdW1uaS5hc3B4P2Nkc3M9NjQmY2RiaD02NQzpmaLlj4vmtLvliqhkAgEPZBYCZg8VAiBhbHVtbmlzdHlsZS5hc3B4P2Nkc3M9NjQmY2RiaD02NgzpmaLlj4vpo47ph4dkAgIPZBYCZg8VAiJhbHVtbmlzZXJ2aWNlLmFzcHg/Y2Rzcz02NCZjZGJoPTY3DOmZouWPi+acjeWKoWQCBw8WAh4EaHJlZgUec2RkbGlzdC5hc3B4P2NkaWQ9YW5ub3VuY2VtZW50ZAIIDw8WAh4EVGV4dAUM6YCa55+l5YWs5ZGKZGQCCg8PFgIfAgVY5pS/5bqc566h55CG5a2m6Zmi5YWz5LqO57uE57uHMjAxN+WxiuacrOenkeavleS4mueUn+mbhuS9k+WQiOW9seWSjOavleS4muWFuOekvOeahOmAmuefpWRkAgwPDxYCHwIFCjIwMTctMDYtMTRkZAIODw8WAh8CBQQxMjg2ZGQCEA8PFgIfAgWV1QE8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0iY2VudGVyIiBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7Ij4NCgk8YnIgLz4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lkITmnKznp5Hmr5XkuJrnj63vvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaMieeFp+WtpuagoeWFs+S6jjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yMDE3PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWxiuavleS4mueUn+aVmeiCsuOAgeemu+agoeW3peS9nOeahOe7n+S4gOWuieaOku+8jOWtpuagoeWumuS6jjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij42PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaciDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml6XvvIjlkajkuozvvInkuIrljYjnu4Tnu4c8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MjAxNzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lsYrmnKznp5Hmr5XkuJrnlJ/pm4bkvZPlkIjlvbHvvIzkuo48L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij42PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaciDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjIyPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaXpe+8iOWRqOWbm++8ieS4iuWNiDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjg6MDA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5Zyo6YKx5a2j56uv5L2T6IKy6aaG5Li+6KGMPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+MjAxNzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lsYrmnKznp5HnlJ/mr5XkuJrlhbjnpLzmmqjlrabkvY3mjojkuojku6rlvI/jgILkuLrkv53or4HlkITpobnlt6XkvZzog73lpJ/pobrliKnmnInluo/lnLDov5vooYzvvIzor7flkITnj63lgZrlpb3nm7jlhbPlt6XkvZzvvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPuS4gOOAgeWtpuS9jeacjeWPkeaUvjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pe26Ze077yaPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjY8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pyIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjE1PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaXpe+8iOWRqOWbm++8ieS4iuWNiDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij44PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4zMC05PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4wMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5Zyw54K577ya5Li75qW85bm/5Zy65Lic5L6nPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5YW35L2T6KaB5rGC77yaPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInor7fku6Xnj63nuqfkuLrljZXkvY3pooblj5blrabkvY3mnI3vvIzmr4/nj63kuIDlkI3otJ/otKPlkIzlrablhajnqIvotJ/otKPlgJ/ov5jlt6XkvZzjgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieWQhOePreiHquWkh+i/kOi+k+W3peWFt++8jOW9k+mdoueCuea4heaVsOmHj++8jOWmguWPkeeOsOegtOaNn++8jOW9k+Wcuuiwg+aNouOAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjM8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJ5ZCE54+t5bqU56Gu5L+d5LqOPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+Njwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7mnIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij4yMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml6XmnKznp5HlkIjlvbHkuYvliY3liIblj5Hlrozmr5XjgILor7flkITnj63liqHlv4Xmj5DphpLlkIzlrablpqXlloTkv53nrqHlrabkvY3mnI3vvIzkuI3opoHpmo/mhI/pq5jmipvlrabkvY3luL3vvIzku6XlhY3mjZ/lnY/jgIHlvbHlk43mr5XkuJrlhbjnpLznmoTkvb/nlKjjgILlpoLlrabkvY3mnI3mnInmjZ/lnY/miJbkuKLlpLHvvIznlLHotJ/otKPlkIzlrabotJ/otKPmnKznj63otZTlgb/vvIjotZTlgb/moIflh4bvvJrlrabkvY3mnI08L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MTQwPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWFgzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4vPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWll++8jOmFjeS7tjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lhYM8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Lzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ku7bvvJvphY3ku7bljIXmi6zlrabkvY3luL3jgIHlnoLluIPjgIHmtYHoi4/nrYnvvInjgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPuS6jOOAgeWtpumZouavleS4muaWh+WMluihq+WPkeaUvjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaXtumXtO+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjY8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pyIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+MTY8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pel77yI5ZGo5LqU77yJ5LiK5Y2I77yM5pe26Ze05Y+m6KGM6YCa55+lPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5Zyw54K577ya5Li75qW8PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+QTUwMUI8L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lhbfkvZPopoHmsYLvvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4xPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieivt+S7peePree6p+S4uuWNleS9jemihuWPluaWh+WMluihq+OAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJ5ZCE54+t6Ieq5aSH6L+Q6L6T5bel5YW377yM5b2T6Z2i54K55riF5pWw6YeP77yM5aaC5Y+R546w56C05o2f77yM5b2T5Zy66LCD5o2i44CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjIxcHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+Jm5ic3A7PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk66buR5L2TOyI+5LiJ44CB5q+V5Lia55Sf6ZuG5L2T5ZCI5b2xPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml7bpl7TvvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Njwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7mnIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MjA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pel77yI5ZGo5LqM77yJ5pep5LiKPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+ODwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij4wMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5Zyw54K577ya5Lqs5biI5bm/5Zy6PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lhbfkvZPopoHmsYLvvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4xPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieWPguWKoOWQiOW9seeahOavleS4mueUn+W/hemhu+epv+edgOWtpuS9jeacje+8jOimgeaxguedgOijheinhOiMg++8jOS7quaAgeWkp+aWue+8jOWQpuWImeS4jeW+l+WPguWKoOWQiOW9seOAgu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrmpbfkvZNfR0IyMzEyOyI+5a2m5L2N5pyN552A6KOF6KeE6IyD6KeB6ZmE5Lu2PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInlkITnj63lupTkuo7kuIrljYg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij44PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjAwPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWJjeWcqOS4u+alvOW5v+WcuuS4nOS+p+aMieeFp+WtpumZouagh+ivhueJjOaMh+WumuWMuuWfn+mbhuWQiOWujOavle+8jOWIhjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjM8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5YiX5o6S5YiX5aW96Zif5b2i77yM5pW055CG5aW9552A6KOF77yM5YGa5aW95ZCI5b2x5YeG5aSH44CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Mzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInmjInml7blgJnlnLrvvIw8L3NwYW4+PGI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPuWQiOW9seWujOavleWQjui/hemAn+emu+Wcujwvc3Bhbj48L2I+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yM56Gu5L+d5pW05Liq6L+H56iL57Sn5YeR5pyJ5bqP77yb6L+f5Yiw55qE5q+V5Lia55Sf5LiN5LqI6KGl5ouN44CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrpu5HkvZM7Ij7lm5vjgIHmnKznp5HnlJ/mr5XkuJrlhbjnpLw8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPumbhuWQiOaXtumXtO+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij42PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaciDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yMjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml6XvvIjlkajlm5vvvInkuIrljYg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij44OjAwPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lnLDngrnvvJrpgrHlraPnq6/kvZPogrLppoY8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWFt+S9k+imgeaxgu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJ5q+V5Lia55Sf5Li65a6M5oiQ5YWo6YOo5a2m5Lia77yM5YeG5LqI5q+V5Lia55qE5a2m55Sf77yb57uT5Lia55Sf5ZKM6IKE5Lia55Sf5Li65pyq5a6M5oiQ5YWo6YOo5a2m5Lia77yM5pyq6L6+5Yiw5q+V5Lia6KaB5rGC55qE5a2m55Sf44CC5q+V5Lia55Sf5Y+v5Y+C5Yqg5q+V5Lia5YW456S85ZKM5a2m5L2N5o6I5LqI5Luq5byP77yM57uT5Lia55Sf5ZKM6IKE5Lia55Sf5LiN5Y+C5Yqg5q+V5Lia5YW456S85ZKM5a2m5L2N5o6I5LqI5Luq5byP44CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+Mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInlhaXlnLrliLjkuLrlj5Hnu5nlj4LliqDmr5XkuJrlhbjnpLzmr5XkuJrnlJ/nmoTlhaXlnLrlh63or4HvvJvop4LnpLzliLjkuLrlj5Hnu5nlj4LliqDmr5XkuJrlhbjnpLznmoTmr5XkuJrnlJ/lrrbplb/nmoTlhaXlnLrlh63or4HjgILor7flkITnj63kuo48L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij42PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaciDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjIwPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaXpe+8iOWRqOS6jO+8iTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjk6MDA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+4oCUPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+MTE6MDA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5Yiw5Li75qW8PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+QTUwMTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7pooblj5bmr5XkuJrlhbjnpLzlhaXlnLrliLjjgIHop4LnpLzliLjjgILkuLrnoa7kv53kvJrlnLrlronlhajlkozlhbjnpLznjrDlnLrnp6nluo/vvIzkuKXmoLzlrp7ooYzkuIDkurrkuIDliLjvvIjor4HvvInliLbvvIzml6DliLjvvIjor4HvvInogIXkuIDlvovkuI3lvpfov5vlhaXjgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij4zPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieWQhOePreS6jjwvc3Bhbj48Yj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjc6MjA8L3NwYW4+PC9iPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWJjeWcqOmCseWto+err+S9k+iCsummhuWNl+S+p+S4gOWxguWNl+mXqOaUv+W6nOeuoeeQhuWtpumZouagh+ivhueJjOWkhOmbhuWQiOWujOavleOAguavleS4mueUn+W6lOedgOWFqOWll+WtpuS9jeacje+8iOWtpuS9jeacjeedgOijheinhOiMg+ingemZhOS7tjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJ77yM6ZqP6Lqr5pC65bim5YWl5Zy65Yi477yI5aGr5YaZ5a6M5pW077yJ77yM5o6S5oiQPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+Mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7liJfjgILlnKjlv5fmhL/ogIXnmoTlvJXlr7zkuIvov5vlhaXkvZPogrLppobvvIzlubbov4XpgJ/liLDmjIflrprljLrln5/lsLHlnZDvvIzlhaXlnLrml7blupTkv53mjIHlhaXlnLrnp6nluo/vvIzkuI3mi6XmjKTvvIzkuI3lgZzpob/jgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij40PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieehruS/neaJgOacieWtpueUn+WcqOWFuOekvOi/h+eoi+S4reWwhuaJi+acuue9ruS6jumdmemfs+eKtuaAge+8jOehruS/neaJgOacieWtpueUn+S4jeaQuuW4puS4juavleS4muWFuOekvOaXoOWFs+eahOeJqeWTge+8jOehruS/neaJgOacieWtpueUn+WcqOS4iuWPsOaOpeWPl+WtpuS9jeOAgeWQiOW9seeVmeW/teWQjuaMieeoi+W6j+WbnuWIsOiHquW3seeahOW6p+S9jeOAguWcqOavleS4muWFuOekvOi/m+ihjOi/h+eoi+S4re+8jOS4jeWFgeiuuOWtpueUn+aPkOWJjeemu+Wcuu+8jOS4jeWFgeiuuOWtpueUn+maj+aEj+i1sOWKqO+8jOehruS/neWFuOekvOeOsOWcuuenqeW6j+iJr+WlveOAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgc3R5bGU9InRleHQtaW5kZW50OjI0LjBwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjU8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJ5q+V5Lia5YW456S85pqo5a2m5L2N5o6I5LqI5Luq5byP57uT5p2f5ZCO77yM6K+35ZCM5a2m5Lus5oyJ54Wn5YWl5Zy66YCa6YGT5L6d5qyh56a75Zy644CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgc3R5bGU9InRleHQtaW5kZW50OjI0LjBwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk66buR5L2TOyI+5LqU44CB5a2m6ZmiPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+MjAxNzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrpu5HkvZM7Ij7lsYrmr5XkuJrnlJ/lkIjlvbE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaXtumXtO+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij42PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaciDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yMTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml6XvvIjlkajkuInvvInkuIrljYg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij4xMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij4wMDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5Zyw54K577ya5Lqs5biI5bm/5Zy65Za35rOJ5aSE5ZCI5b2x6ZOB5p625a2Q5YmNPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5YW35L2T6KaB5rGC77yaPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+MTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInlhajkvZPmnKznp5HjgIHnoJTnqbbnlJ/mr5XkuJrnlJ/lj4LkuI7vvIzlubbkuo48L3NwYW4+PGI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij45OjQwPC9zcGFuPjwvYj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7liY3lnKjlkIjlvbHlpITpm4blkIjlrozmr5XvvIzpgL7mnJ/kuI3kuojooaXmi43jgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij4yPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieepv+edgOWtpumZouavleS4muaWh+WMluihq++8iOa1quiKseasvu+8ieOAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk66buR5L2TOyI+5YWt44CB54Wn54mH6aKG5Y+WPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml7bpl7TvvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Njwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7mnIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MjY8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pel77yI5ZGo5LiA77yJPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjE1PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4wMC0xNzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MDA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWcsOeCue+8muS4u+alvDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPkE1MDE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWFt+S9k+imgeaxgu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yIPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjE8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yJ6K+35ZCE54+t5aeU5rS+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjEtMjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lkI3otJ/otKPlkIzlrabku6Xnj63nuqfkuLrljZXkvY3pooblj5bmr5XkuJrnhafvvJs8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8iDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4yPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8ieivt+eOsOWcuua4heeCueeFp+eJh+aVsOmHj++8jOmAvuacn+S4jeWGjeihpeWPkeOAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk66buR5L2TOyI+5LiD44CB5a2m5L2N5pyN5Zue5pS2PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7ml7bpl7TvvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Njwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7mnIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Mjc8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pel77yI5ZGo5LqM77yJ5LiL5Y2IPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjE0PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4zMC0xNTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvJo8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MDA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWcsOeCue+8muS4u+alvOW5v+WcuuS4nOS+pzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5YW35L2T6KaB5rGC77yaPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInor7flkITnj63lsIblrabkvY3mnI3nmoTlrabkvY3ooo3jgIHlnoLluIPjgIHlrabkvY3luL3kuo7lm57kuqTliY08L3NwYW4+PGI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPuWIhuWIqzwvc3Bhbj48L2I+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5pW055CG5aW977ybPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvIg8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+Mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7vvInor7flkITnj63noa7kv508L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+MTU8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+77yaPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPjAwPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuS5i+WJjeWbnuS6pO+8jOe7j+aguOWvuemqjOaUtuaXoOivr+WQjuaWueWPr+emu+W8gOOAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuiBlOezu+S6uu+8muiwoue+mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPiZuYnNwOyZuYnNwOyA1ODgwOTI0NTwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249InJpZ2h0IiBzdHlsZT0idGV4dC1hbGlnbjpyaWdodDt0ZXh0LWluZGVudDoyNC4wcHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7mlL/lupznrqHnkIblrabpmaI8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0icmlnaHQiIHN0eWxlPSJ0ZXh0LWFsaWduOnJpZ2h0O3RleHQtaW5kZW50OjI0LjBwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+MjAxNzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lubQ8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij42PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaciDwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjE0PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuaXpTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTomcXVvdDsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OiZxdW90OyI+PC9zcGFuPg0KPC9wPg0KPHU+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk6JnF1b3Q7Ij48YnIgLz4NCjwvc3Bhbj48L3U+IA0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPumZhOS7tjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij4xPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPu+8mjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTQuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPuWtpuS9jeacjeedgOijheinhOiMg+ivtOaYjjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk66buR5L2TOyI+5LiA44CB5a2m5L2N5bi9PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lrabkvY3luL3kuLrmlrnlnovpu5HoibLjgILmiLTlrabkvY3luL3ml7bvvIzluL3lrZDlvIDlj6PnmoTpg6jkvY3nva7kuo7ohJHlkI7mraPkuK3vvIzluL3pobbkuI7nnYDoo4XkurrnmoTop4bnur/lubPooYzjgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPuS6jOOAgea1geiLjzwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5a2m5aOr5a2m5L2N5rWB6IuP5Li66buR6Imy77yM6Zmi6ZW/5bi95rWB6IuP5Li66buE6Imy44CC5rWB6IuP57O75oyC5Zyo5bi96aG255qE5bi957uT5LiK77yM5rK/5bi95qqQ6Ieq54S25LiL5Z6C44CC5pyq5o6I5LqI5a2m5L2N5pe277yM5rWB6IuP5Z6C5Zyo552A6KOF5Lq65omA5oi05a2m5L2N5bi95Y+z5YmN5L6n5Lit6YOo77yb5a2m5L2N5o6I5LqI5Luq5byP5LiK77yM5o6I5LqI5a2m5L2N5ZCO77yM55Sx6Zmi6ZW/5oqK5rWB6IuP5LuO552A6KOF5Lq655qE5bi95qqQ5Y+z5YmN5L6n56e75Yiw5bem5YmN5L6n5Lit6YOo77yM5bm25ZGI6Ieq54S25LiL5Z6C54q244CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrpu5HkvZM7Ij7kuInjgIHlrabkvY3ooo08L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPuWtpuWjq+WtpuS9jeiijeS4uum7keiJsu+8jOagoemVv+acjeS4uue6ouOAgem7hOS4pOiJsuOAguepv+edgOWtpuS9jeiije+8jOW6lOiHqueEtuWQiOS9k+OAguWtpuS9jeiijeWkluS4jeW+l+WKoOWll+WFtuS7luacjeijheOAgjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk66buR5L2TOyI+5Zub44CB5Z6C5biDPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7lnoLluIPkuLrlpZflpLTkuInop5LlhZzlnovvvIzppbDovrnlpITmjInmlofjgIHnkIbjgIHlt6XjgIHlhpzjgIHljLvjgIHlhpvkuovlha3lpKfnsbvliIbliKvkuLrnsonjgIHngbDjgIHpu4TjgIHnu7/jgIHnmb3jgIHnuqLpopzoibLjgILlnoLluIPkvanmiLTlnKjlrabkvY3ooo3lpJbvvIzlpZflpLTmiqvlnKjogqnog4zlpITvvIzpk7rlubPov4fogqnvvIzmiaPnu4rmiaPlnKjlrabkvY3ooo3mnIDkuIrpnaLnmoTnur3miaPkuIrvvIzkuInop5LlhZzoh6rnhLblnoLlnKjog4zlkI7jgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5Oum7keS9kzsiPuS6lOOAgemZhOWxnuedgOijhTwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk65a6L5L2TOyI+PC9zcGFuPg0KPC9wPg0KPHAgY2xhc3M9Ik1zb05vcm1hbCIgYWxpZ249ImxlZnQiIHN0eWxlPSJ0ZXh0LWluZGVudDoyNHB0OyI+DQoJPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZToxMi4wcHQ7Zm9udC1mYW1pbHk65a6L5L2TOyI+5YaF6KGj77ya5bqU552A55m95oiW5rWF6Imy6KGs6KGr44CCPC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTrlrovkvZM7Ij48L3NwYW4+DQo8L3A+DQo8cCBjbGFzcz0iTXNvTm9ybWFsIiBhbGlnbj0ibGVmdCIgc3R5bGU9InRleHQtaW5kZW50OjI0cHQ7Ij4NCgk8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEyLjBwdDtmb250LWZhbWlseTrlrovkvZM7Ij7oo6TlrZDvvJrnlLflo6vnnYDmt7HoibLoo6TlrZDvvIzlpbPlo6vnnYDmt7HoibLoo6TlrZDmiJbmt7HjgIHntKDoibLoo5nlrZDjgII8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OuWui+S9kzsiPjwvc3Bhbj4NCjwvcD4NCjxwIGNsYXNzPSJNc29Ob3JtYWwiIGFsaWduPSJsZWZ0IiBzdHlsZT0idGV4dC1pbmRlbnQ6MjRwdDsiPg0KCTxzcGFuIHN0eWxlPSJmb250LXNpemU6MTIuMHB0O2ZvbnQtZmFtaWx5OuWui+S9kzsiPumei+WtkO+8muW6lOedgOa3seiJsuearumei+OAgjwvc3Bhbj4NCjwvcD5kZAISDxYCHwACARYCZg9kFgJmDxUDBDU5NjQMYW5ub3VuY2VtZW50NOWFs+S6juaIkemZojIwMTflubTluqbmnKznp5HnlJ/lsI/lrabmnJ/nj6DmtbfnpL4uLi5kAhQPFgIfAAIBFgJmD2QWAmYPFQMENjk2MQxhbm5vdW5jZW1lbnQ86K6y5bqn6aKE5ZGK77ya5Lit5Zu95piv5ZCm5Y+v5Lul5Y+W5Luj576O5Zu96YeN5aGR5LiW55WMLi4uZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WAQUMSW1hZ2VCdXR0b24xZWhbr1OTadCnRQkJk3vok04nNNI=" />
</div>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="1951E080" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEWAwL0/7CzBALs0bLrBgLSwpnTCN5zaa3MouSkWTGnd0VSj/UxVXJF" />
</div>
        <header>
            <!--top end-->
            <div class="logo-bg" style="padding: 0">
                <div class=" container" style="width: 980px; background-color: #fff">
                    <div class="row clearfix" style="margin: 1% 0">
                        <div class="col-md-4 column logo-box ">
                            <a href="index.aspx">
                                <img src="images/logo.png" title="logo" class="img-responsive" alt="Cinque Terre" /></a>
                        </div>
                        <div class="col-md-5 column"></div>
                        <div class="col-md-3 column pn">
                            <div class="top-tell">
                                <p>
                                    <a href="http://www.sg.bnu.edu.cn:8082/eng/eindex.jsp" target="_blank">English Version</a>
                                </p>
                            </div>
                            <!--中文版 英文版-->
                            <div class="top-search">

                                <div class="input-group">
                                      <input name="TextBox1" type="text" id="TextBox1" class="form-control input1" />
                                    <span class="input-group-addon">

                                        <input type="image" name="ImageButton1" id="ImageButton1" src="images/sousou.png" style="border-width:0px;" />
                                    </span>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row clearfix" style="background-color: #0035B4">
                        <nav class="navbar topnav" role="navigation" style="min-height: 0; padding: 10px 0">
                            <div class="container-fluid top-nav">
                                <div class="collapse navbar-collapse top-nav" id="example-navbar-collapse">
                                    <ul class=" navbar-nav cex-list">
                                      <li class=""><a href="index.aspx">首页</a></li>
                                            
                                                    <li class="dropdown">
                                                        <a href="about.aspx?cdss=19&cdbh=19" class="dropdown-toggle">学院介绍 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="about.aspx?cdss=19&cdbh=20">学院概述</a></li>
                                                                
                                                                    <li><a href="history.aspx?cdss=19&cdbh=21">历史沿革</a></li>
                                                                
                                                                    <li><a href="structure.aspx?cdss=19&cdbh=22">组织机构</a></li>
                                                                
                                                                    <li><a href="Subject.aspx?cdss=19&cdbh=23">学科设置</a></li>
                                                                
                                                                    <li><a href="Department.aspx?cdss=19&cdbh=24">系所介绍</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="personnel.aspx?cdss=25&cdbh=25" class="dropdown-toggle">人才培养 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="undergraduate.aspx?cdss=25&cdbh=26">本科生</a></li>
                                                                
                                                                    <li><a href="Master.aspx?cdss=25&cdbh=27">硕士生</a></li>
                                                                
                                                                    <li><a href="Masterb.aspx?cdss=25&cdbh=28">博士生</a></li>
                                                                
                                                                    <li><a href="Masterbh.aspx?cdss=25&cdbh=29">博士后</a></li>
                                                                
                                                                    <li><a href="index-mpa.aspx?cdss=25&cdbh=30">MPA</a></li>
                                                                
                                                                    <li><a href="practice.aspx?cdss=25&cdbh=31">实习基地</a></li>
                                                                
                                                                    <li><a href="laboratory.aspx?cdss=25&cdbh=32">实验室</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="r-about.aspx?cdss=33&cdbh=33" class="dropdown-toggle">招生就业 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="r-about.aspx?cdss=33&cdbh=34">学院简介</a></li>
                                                                
                                                                    <li><a href="professional.aspx?cdss=33&cdbh=35">专业介绍</a></li>
                                                                
                                                                    <li><a href="register.aspx?cdss=33&cdbh=36">报考指南</a></li>
                                                                
                                                                    <li><a href="employment.aspx?cdss=33&cdbh=37">就业指导</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="teacherstaff.aspx?cdss=38&cdbh=38" class="dropdown-toggle">师资队伍 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="Tadministrative.aspx?cdss=38&cdbh=39">行政管理</a></li>
                                                                
                                                                    <li><a href="Thuman.aspx?cdss=38&cdbh=40">人力资源</a></li>
                                                                
                                                                    <li><a href="Tinformation.aspx?cdss=38&cdbh=41">信息管理</a></li>
                                                                
                                                                    <li><a href="Tmanagement.aspx?cdss=38&cdbh=42">管理科学与工程</a></li>
                                                                
                                                                    <li><a href="Tland.aspx?cdss=38&cdbh=43">土地资源管理</a></li>
                                                                
                                                                    <li><a href="Tpolitical.aspx?cdss=38&cdbh=44">政治学</a></li>
                                                                
                                                                    <li><a href="Tinternational.aspx?cdss=38&cdbh=45">国际关系</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="research.aspx?cdss=46&cdbh=46" class="dropdown-toggle">学术科研 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="project.aspx?cdss=46&cdbh=47">科研项目</a></li>
                                                                
                                                                    <li><a href="academic.aspx?cdss=46&cdbh=48">学术论文</a></li>
                                                                
                                                                    <li><a href="monograph.aspx?cdss=46&cdbh=49">专著教材</a></li>
                                                                
                                                                    <li><a href="research-report.aspx?cdss=46&cdbh=50">研究报告</a></li>
                                                                
                                                                    <li><a href="system.aspx?cdss=46&cdbh=51">科研制度</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="Students-work.aspx?cdss=52&cdbh=52" class="dropdown-toggle">学生工作 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="announcement.aspx?cdss=52&cdbh=53">通知公告</a></li>
                                                                
                                                                    <li><a href="organization.aspx?cdss=52&cdbh=54">社团风采</a></li>
                                                                
                                                                    <li><a href="Party-Building.aspx?cdss=52&cdbh=55">党旗飘飘</a></li>
                                                                
                                                                    <li><a href="studentactivity.aspx?cdss=52&cdbh=56">班级建设</a></li>
                                                                
                                                                    <li><a href="Youth-activity.aspx?cdss=52&cdbh=57">团委工作</a></li>
                                                                
                                                                    <li><a href="student-act.aspx?cdss=52&cdbh=58">学生活动</a></li>
                                                                
                                                                    <li><a href="xiazai.aspx?cdss=52&cdbh=59">常用下载</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="services.aspx?cdss=60&cdbh=60" class="dropdown-toggle">社会服务 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="continuing.aspx?cdss=60&cdbh=61">继续教育</a></li>
                                                                
                                                                    <li><a href="training.aspx?cdss=60&cdbh=62">社会培训</a></li>
                                                                
                                                                    <li><a href="exchange.aspx?cdss=60&cdbh=63">对外交流</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                                    <li class="dropdown">
                                                        <a href="alumni.aspx?cdss=64&cdbh=64" class="dropdown-toggle">院友之窗 <b class="caret"></b>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            
                                                                    <li><a href="alumni.aspx?cdss=64&cdbh=65">院友活动</a></li>
                                                                
                                                                    <li><a href="alumnistyle.aspx?cdss=64&cdbh=66">院友风采</a></li>
                                                                
                                                                    <li><a href="alumniservice.aspx?cdss=64&cdbh=67">院友服务</a></li>
                                                                
                                                        </ul>
                                                    </li>
                                                
                                        <!--8-->
                                    </ul>
                                </div>
                            </div>
                        </nav>
                        <!--顶部导航-->
                    </div>
                </div>


            </div>
            <!--logo-bg-->

        </header>
        <section>
            <div class="container" style="width: 980px; margin: 0% auto; background-color: #fff; border-radius: 3px">
                <div style="width: 97%; margin: 1% auto; text-align: right">当前位置：<a href="index.aspx">首页</a>-><span id="Label5">通知公告</span>->正文</div>

                <div id="right_center" class="right_center3 anli_lineheight" style="background: #fff; width: 97%; margin: 2% auto; border-radius: 5px; border: 1px solid #DCE6F0;">
                       <div class="program_dl" style="width: 90%; margin: 0 auto">
                        <div class="kec_s ">   
                            <h3 class="program_title" style="font-weight:bold;">
                                <span style="text-align: center; display: block; border-bottom: 1px solid #DCE6F0; color: #2C4A7E; padding-bottom: 1%">
                                    <span id="Label1">政府管理学院关于组织2017届本科毕业生集体合影和毕业典礼的通知</span></span>
                            </h3>
                            <h5 class="program_title" style="color: #999; padding-bottom: 2%;">
                                <span style="text-align: center; display: block;">
                                    <span id="Label2">2017-06-14</span>
                                    点击率：<span id="Label4">1286</span>
                                </span>
                            </h5>
                            <span id="Label3"><p class="MsoNormal" align="center" style="text-align:center;">
	<br />
</p>
<p class="MsoNormal" align="left">
	<span style="font-size:12.0pt;font-family:宋体;">各本科毕业班：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">按照学校关于</span><span style="font-size:12.0pt;font-family:宋体;">2017</span><span style="font-size:12.0pt;font-family:宋体;">届毕业生教育、离校工作的统一安排，学校定于</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">20</span><span style="font-size:12.0pt;font-family:宋体;">日（周二）上午组织</span><span style="font-size:12.0pt;font-family:宋体;">2017</span><span style="font-size:12.0pt;font-family:宋体;">届本科毕业生集体合影，于</span><span style="font-size:12.0pt;font-family:&quot;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:&quot;">22</span><span style="font-size:12.0pt;font-family:宋体;">日（周四）上午</span><span style="font-size:12.0pt;font-family:&quot;">8:00</span><span style="font-size:12.0pt;font-family:宋体;">在邱季端体育馆举行</span><span style="font-size:12.0pt;font-family:&quot;">2017</span><span style="font-size:12.0pt;font-family:宋体;">届本科生毕业典礼暨学位授予仪式。为保证各项工作能够顺利有序地进行，请各班做好相关工作：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">一、学位服发放</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">时间：</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">15</span><span style="font-size:12.0pt;font-family:宋体;">日（周四）上午</span><span style="font-size:12.0pt;font-family:宋体;">8</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">30-9</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">00</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：主楼广场东侧</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:宋体;">）请以班级为单位领取学位服，每班一名负责同学全程负责借还工作。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">2</span><span style="font-size:12.0pt;font-family:宋体;">）各班自备运输工具，当面点清数量，如发现破损，当场调换。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">3</span><span style="font-size:12.0pt;font-family:宋体;">）各班应确保于</span><span style="font-size:12.0pt;font-family:&quot;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:&quot;">20</span><span style="font-size:12.0pt;font-family:宋体;">日本科合影之前分发完毕。请各班务必提醒同学妥善保管学位服，不要随意高抛学位帽，以免损坏、影响毕业典礼的使用。如学位服有损坏或丢失，由负责同学负责本班赔偿（赔偿标准：学位服</span><span style="font-size:12.0pt;font-family:宋体;">140</span><span style="font-size:12.0pt;font-family:宋体;">元</span><span style="font-size:12.0pt;font-family:宋体;">/</span><span style="font-size:12.0pt;font-family:宋体;">套，配件</span><span style="font-size:12.0pt;font-family:宋体;">20</span><span style="font-size:12.0pt;font-family:宋体;">元</span><span style="font-size:12.0pt;font-family:宋体;">/</span><span style="font-size:12.0pt;font-family:宋体;">件；配件包括学位帽、垂布、流苏等）。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">二、学院毕业文化衫发放</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">时间：</span><span style="font-size:12.0pt;font-family:&quot;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:&quot;">16</span><span style="font-size:12.0pt;font-family:宋体;">日（周五）上午，时间另行通知</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：主楼</span><span style="font-size:12.0pt;font-family:&quot;">A501B</span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:宋体;">）请以班级为单位领取文化衫。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">2</span><span style="font-size:12.0pt;font-family:宋体;">）各班自备运输工具，当面点清数量，如发现破损，当场调换。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:21pt;">
	<span style="font-family:宋体;">&nbsp;</span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">三、毕业生集体合影</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">时间：</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">20</span><span style="font-size:12.0pt;font-family:宋体;">日（周二）早上</span><span style="font-size:12.0pt;font-family:&quot;">8</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:&quot;">00</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：京师广场</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:宋体;">）参加合影的毕业生必须穿着学位服，要求着装规范，仪态大方，否则不得参加合影。（</span><span style="font-size:12.0pt;font-family:楷体_GB2312;">学位服着装规范见附件</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:宋体;">）</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">2</span><span style="font-size:12.0pt;font-family:宋体;">）各班应于上午</span><span style="font-size:12.0pt;font-family:&quot;">8</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:&quot;">00</span><span style="font-size:12.0pt;font-family:宋体;">前在主楼广场东侧按照学院标识牌指定区域集合完毕，分</span><span style="font-size:12.0pt;font-family:&quot;">3</span><span style="font-size:12.0pt;font-family:宋体;">列排列好队形，整理好着装，做好合影准备。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">3</span><span style="font-size:12.0pt;font-family:宋体;">）按时候场，</span><b><span style="font-family:宋体;">合影完毕后迅速离场</span></b><span style="font-size:12.0pt;font-family:宋体;">，确保整个过程紧凑有序；迟到的毕业生不予补拍。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">四、本科生毕业典礼</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">集合时间：</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">22</span><span style="font-size:12.0pt;font-family:宋体;">日（周四）上午</span><span style="font-size:12.0pt;font-family:&quot;">8:00</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：邱季端体育馆</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">1</span><span style="font-size:12.0pt;font-family:宋体;">）毕业生为完成全部学业，准予毕业的学生；结业生和肄业生为未完成全部学业，未达到毕业要求的学生。毕业生可参加毕业典礼和学位授予仪式，结业生和肄业生不参加毕业典礼和学位授予仪式。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">2</span><span style="font-size:12.0pt;font-family:宋体;">）入场券为发给参加毕业典礼毕业生的入场凭证；观礼券为发给参加毕业典礼的毕业生家长的入场凭证。请各班于</span><span style="font-size:12.0pt;font-family:&quot;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:&quot;">20</span><span style="font-size:12.0pt;font-family:宋体;">日（周二）</span><span style="font-size:12.0pt;font-family:&quot;">9:00</span><span style="font-size:12.0pt;font-family:宋体;">—</span><span style="font-size:12.0pt;font-family:&quot;">11:00</span><span style="font-size:12.0pt;font-family:宋体;">到主楼</span><span style="font-size:12.0pt;font-family:&quot;">A501</span><span style="font-size:12.0pt;font-family:宋体;">领取毕业典礼入场券、观礼券。为确保会场安全和典礼现场秩序，严格实行一人一券（证）制，无券（证）者一律不得进入。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">3</span><span style="font-size:12.0pt;font-family:宋体;">）各班于</span><b><span style="font-size:12.0pt;font-family:&quot;">7:20</span></b><span style="font-size:12.0pt;font-family:宋体;">前在邱季端体育馆南侧一层南门政府管理学院标识牌处集合完毕。毕业生应着全套学位服（学位服着装规范见附件</span><span style="font-size:12.0pt;font-family:&quot;">1</span><span style="font-size:12.0pt;font-family:宋体;">），随身携带入场券（填写完整），排成</span><span style="font-size:12.0pt;font-family:&quot;">2</span><span style="font-size:12.0pt;font-family:宋体;">列。在志愿者的引导下进入体育馆，并迅速到指定区域就坐，入场时应保持入场秩序，不拥挤，不停顿。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">4</span><span style="font-size:12.0pt;font-family:宋体;">）确保所有学生在典礼过程中将手机置于静音状态，确保所有学生不携带与毕业典礼无关的物品，确保所有学生在上台接受学位、合影留念后按程序回到自己的座位。在毕业典礼进行过程中，不允许学生提前离场，不允许学生随意走动，确保典礼现场秩序良好。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" style="text-indent:24.0pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">5</span><span style="font-size:12.0pt;font-family:宋体;">）毕业典礼暨学位授予仪式结束后，请同学们按照入场通道依次离场。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" style="text-indent:24.0pt;">
	<span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">五、学院</span><span style="font-size:12.0pt;font-family:&quot;">2017</span><span style="font-size:12.0pt;font-family:黑体;">届毕业生合影</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">时间：</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">21</span><span style="font-size:12.0pt;font-family:宋体;">日（周三）上午</span><span style="font-size:12.0pt;font-family:&quot;">10</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:&quot;">00</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：京师广场喷泉处合影铁架子前</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">1</span><span style="font-size:12.0pt;font-family:宋体;">）全体本科、研究生毕业生参与，并于</span><b><span style="font-size:12.0pt;font-family:&quot;">9:40</span></b><span style="font-size:12.0pt;font-family:宋体;">前在合影处集合完毕，逾期不予补拍。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:&quot;">2</span><span style="font-size:12.0pt;font-family:宋体;">）穿着学院毕业文化衫（浪花款）。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">六、照片领取</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">时间：</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">26</span><span style="font-size:12.0pt;font-family:宋体;">日（周一）</span><span style="font-size:12.0pt;font-family:宋体;">15</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">00-17</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">00</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：主楼</span><span style="font-size:12.0pt;font-family:&quot;">A501</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:宋体;">）请各班委派</span><span style="font-size:12.0pt;font-family:宋体;">1-2</span><span style="font-size:12.0pt;font-family:宋体;">名负责同学以班级为单位领取毕业照；</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">2</span><span style="font-size:12.0pt;font-family:宋体;">）请现场清点照片数量，逾期不再补发。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">七、学位服回收</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">时间：</span><span style="font-size:12.0pt;font-family:宋体;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:宋体;">27</span><span style="font-size:12.0pt;font-family:宋体;">日（周二）下午</span><span style="font-size:12.0pt;font-family:宋体;">14</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">30-15</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">00</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">地点：主楼广场东侧</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">具体要求：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:宋体;">）请各班将学位服的学位袍、垂布、学位帽于回交前</span><b><span style="font-family:宋体;">分别</span></b><span style="font-size:12.0pt;font-family:宋体;">整理好；</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">（</span><span style="font-size:12.0pt;font-family:宋体;">2</span><span style="font-size:12.0pt;font-family:宋体;">）请各班确保</span><span style="font-size:12.0pt;font-family:宋体;">15</span><span style="font-size:12.0pt;font-family:宋体;">：</span><span style="font-size:12.0pt;font-family:宋体;">00</span><span style="font-size:12.0pt;font-family:宋体;">之前回交，经核对验收无误后方可离开。</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">联系人：谢羚</span><span style="font-size:12.0pt;font-family:&quot;">&nbsp;&nbsp; 58809245</span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="right" style="text-align:right;text-indent:24.0pt;">
	<span style="font-size:12.0pt;font-family:宋体;">政府管理学院</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="right" style="text-align:right;text-indent:24.0pt;">
	<span style="font-size:12.0pt;font-family:&quot;">2017</span><span style="font-size:12.0pt;font-family:宋体;">年</span><span style="font-size:12.0pt;font-family:&quot;">6</span><span style="font-size:12.0pt;font-family:宋体;">月</span><span style="font-size:12.0pt;font-family:&quot;">14</span><span style="font-size:12.0pt;font-family:宋体;">日</span><span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:&quot;"></span>
</p>
<u><span style="font-size:12.0pt;font-family:&quot;"><br />
</span></u> 
<p class="MsoNormal" align="left">
	<span style="font-size:12.0pt;font-family:黑体;">附件</span><span style="font-size:12.0pt;font-family:宋体;">1</span><span style="font-size:12.0pt;font-family:黑体;">：</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left">
	<span style="font-size:14.0pt;font-family:黑体;">学位服着装规范说明</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">一、学位帽</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">学位帽为方型黑色。戴学位帽时，帽子开口的部位置于脑后正中，帽顶与着装人的视线平行。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">二、流苏</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">学士学位流苏为黑色，院长帽流苏为黄色。流苏系挂在帽顶的帽结上，沿帽檐自然下垂。未授予学位时，流苏垂在着装人所戴学位帽右前侧中部；学位授予仪式上，授予学位后，由院长把流苏从着装人的帽檐右前侧移到左前侧中部，并呈自然下垂状。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">三、学位袍</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">学士学位袍为黑色，校长服为红、黄两色。穿着学位袍，应自然合体。学位袍外不得加套其他服装。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">四、垂布</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">垂布为套头三角兜型，饰边处按文、理、工、农、医、军事六大类分别为粉、灰、黄、绿、白、红颜色。垂布佩戴在学位袍外，套头披在肩背处，铺平过肩，扣绊扣在学位袍最上面的纽扣上，三角兜自然垂在背后。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:黑体;">五、附属着装</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">内衣：应着白或浅色衬衫。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">裤子：男士着深色裤子，女士着深色裤子或深、素色裙子。</span><span style="font-family:宋体;"></span>
</p>
<p class="MsoNormal" align="left" style="text-indent:24pt;">
	<span style="font-size:12.0pt;font-family:宋体;">鞋子：应着深色皮鞋。</span>
</p></span>
                        </div>
                        <div style="border-top: 1px solid #DCE6F0; padding: 1% 0; width: 100%; overflow: hidden; margin-top: 5%">
                            
                                    <a href="newshow.aspx?newid=5964&wzlx=announcement" class="pres" style="float: left; width: 45%;">上一篇：关于我院2017年度本科生小学期珠海社...</a>
                                
                            

                                    <a href="newshow.aspx?newid=6961&wzlx=announcement" class="pres" style="float: right; width: 45%;">下一篇：讲座预告：中国是否可以取代美国重塑世界...</a>

                                
                        </div>


                        
                    </div>

                </div>
            </div>
        </section>
        <!--section中间部分-->
        <footer>
            <div class="container">
                <div class="row clearfix">
                    <div class="col-md-12 column">
                        <div class="row clearfix">
                            <div class="col-md-9 column">
                               <p>
                                    学院地址：北京市海淀区新街口外大街19号 北京师范大学前主楼A区5层 
                                </p>
                                <p>
                                    联系电话：010-58808256 &nbsp; MPA咨询电话：010-58808176
                                </p>
                                <p>
                                    Copyright@2016 北京师范大学政府管理学院版权所有 &nbsp;All Rights Reserved 
                                </p>
                                <p>
                                    设计与开发：<a href="http://www.ixingzhi.cn" target="_blank" style="color:white">行知睿思 </a> 
                                </p>
                            </div>
                         <div class="col-md-3 column ">
                                <dl class="caption">
                                    <dt>
                                        <img src="images/weixin.png" alt="Cinque Terre" class="img-responsive" />
                                    </dt>
                                    <dd>公众号
                                    </dd>
                                </dl>
                                <dl class="caption">
                                    <dt>
                                        <img src="images/er.png" alt="Cinque Terre" class="img-responsive" />
                                    </dt>
                                    <dd>手机版
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </footer>
    </form>
</body>
</html>
